# abrt-action-trim-files
# Autogenerated from man page /usr/share/man/man1/abrt-action-trim-files.1.gz
complete -c abrt-action-trim-files -s v -d 'Be more verbose.  Can be given multiple times'
complete -c abrt-action-trim-files -s d -d 'Delete problem directories in DIR'
complete -c abrt-action-trim-files -s f -d 'Delete files in DIR'
complete -c abrt-action-trim-files -s p -d 'Preserve DIR (never consider it for deletion)'

