# abrt-dbus
# Autogenerated from man page /usr/share/man/man8/abrt-dbus.8.gz
complete -c abrt-dbus -s v -d 'Log more detailed debugging information'
complete -c abrt-dbus -s t -d 'Exit after NUM seconds of inactivity'

