# abrt-server
# Autogenerated from man page /usr/share/man/man1/abrt-server.1.gz
complete -c abrt-server -s u -d 'Use UID as client uid'
complete -c abrt-server -s s -d 'Log to system log'
complete -c abrt-server -s p -d 'Add program names to log'
complete -c abrt-server -s v -d 'Log more detailed debugging information'
complete -c abrt-server -s '>'

