# abrt
# Autogenerated from man page /usr/share/man/man1/abrt.1.gz
complete -c abrt -s a -l auth -d 'Authenticate and show all problems on this machine'
complete -c abrt -s v -l version -d 'Show program\'s version number and exit'
complete -c abrt -s h -l help -d 'Show help message'

