# abrt-dump-journal-oops
# Autogenerated from man page /usr/share/man/man1/abrt-dump-journal-oops.1.gz
complete -c abrt-dump-journal-oops -s v -l verbose -d 'Be more verbose.  Can be given multiple times'
complete -c abrt-dump-journal-oops -s s -d 'Log to syslog'
complete -c abrt-dump-journal-oops -s o -d 'Print found oopses on standard output'
complete -c abrt-dump-journal-oops -s d -d 'Create new problem directory in DIR for every oops found'
complete -c abrt-dump-journal-oops -s D -d 'Same as -d DumpLocation, DumpLocation is specified in abrt. conf'
complete -c abrt-dump-journal-oops -s e -d 'Starts following systemd-journal from the end'
complete -c abrt-dump-journal-oops -s x -d 'Make the problem directory world readable.  Usable only with -d/-D'
complete -c abrt-dump-journal-oops -s t -d 'Throttle problem directory creation to 1 per second'
complete -c abrt-dump-journal-oops -s f -d 'Follow systemd-journal'

