# abrt-dump-journal-xorg
# Autogenerated from man page /usr/share/man/man1/abrt-dump-journal-xorg.1.gz
complete -c abrt-dump-journal-xorg -s v -l verbose -d 'Be more verbose.  Can be given multiple times'
complete -c abrt-dump-journal-xorg -s s -d 'Log to syslog'
complete -c abrt-dump-journal-xorg -s o -d 'Print found Xorg crashes on standard output'
complete -c abrt-dump-journal-xorg -s d -d 'Create new problem directory in DIR for every Xorg crash found'
complete -c abrt-dump-journal-xorg -s D -d 'Same as -d DumpLocation, DumpLocation is specified in abrt. conf'
complete -c abrt-dump-journal-xorg -s e -d 'Starts following systemd-journal from the end'
complete -c abrt-dump-journal-xorg -s x -d 'Make the problem directory world readable.  Usable only with -d/-D'
complete -c abrt-dump-journal-xorg -s t -d 'Throttle problem directory creation to 1 per second'
complete -c abrt-dump-journal-xorg -s f -d 'Follow systemd-journal'
complete -c abrt-dump-journal-xorg -s j -d 'Set journal filter (may be given many times)'

