# abrt-action-analyze-python
# Autogenerated from man page /usr/share/man/man1/abrt-action-analyze-python.1.gz
complete -c abrt-action-analyze-python -s d -d 'Path to a problem directory'
complete -c abrt-action-analyze-python -s v -d 'Be more verbose.  Can be given multiple times'

