# abrt-action-list-dsos
# Autogenerated from man page /usr/share/man/man1/abrt-action-list-dsos.1.gz
complete -c abrt-action-list-dsos -s o -d 'Output file, if not specified, it is printed to stdout'
complete -c abrt-action-list-dsos -s m -d 'File containing the mapped memory regions'

