# abrt-dump-oops
# Autogenerated from man page /usr/share/man/man1/abrt-dump-oops.1.gz
complete -c abrt-dump-oops -s v -l verbose -d 'Be more verbose.  Can be given multiple times'
complete -c abrt-dump-oops -s s -d 'Log to syslog'
complete -c abrt-dump-oops -s o -d 'Print found oopses on standard output'
complete -c abrt-dump-oops -s d -d 'Create new problem directory in DIR for every oops found'
complete -c abrt-dump-oops -s D -d 'Same as -d DumpLocation, DumpLocation is specified in abrt. conf'
complete -c abrt-dump-oops -s u -d 'Save the extracted information in PROBLEM directory'
complete -c abrt-dump-oops -s x -d 'Make the problem directory world readable.  Usable only with -d/-D'
complete -c abrt-dump-oops -s t -d 'Throttle problem directory creation to 1 per second'
complete -c abrt-dump-oops -s m -d 'Print search string(s) for abrt-watch-log to stdout and exit'

