# abrt-dump-journal-core
# Autogenerated from man page /usr/share/man/man1/abrt-dump-journal-core.1.gz
complete -c abrt-dump-journal-core -s v -l verbose -d 'Be more verbose.  Can be given multiple times'
complete -c abrt-dump-journal-core -s s -d 'Log to syslog'
complete -c abrt-dump-journal-core -s d -d 'Create new problem directory in DIR for every coredump'
complete -c abrt-dump-journal-core -s D -d 'Same as -d DumpLocation, DumpLocation is specified in abrt. conf'
complete -c abrt-dump-journal-core -s e -d 'Starts following systemd-journal from the end'
complete -c abrt-dump-journal-core -s t -d 'Throttle problem directory creation to 1 per INT second'
complete -c abrt-dump-journal-core -s T -d 'Same as -t INT, INT is specified in plugins/CCpp. conf'
complete -c abrt-dump-journal-core -s f -d 'Follow systemd-journal from the last seen position (if available)'
complete -c abrt-dump-journal-core -s c

