# abrt-action-analyze-c
# Autogenerated from man page /usr/share/man/man1/abrt-action-analyze-c.1.gz
complete -c abrt-action-analyze-c -s d -d 'Path to a problem directory'
complete -c abrt-action-analyze-c -s v -d 'Be more verbose.  Can be given multiple times'

