# abrt-action-analyze-xorg
# Autogenerated from man page /usr/share/man/man1/abrt-action-analyze-xorg.1.gz
complete -c abrt-action-analyze-xorg -s d -d 'Path to a problem directory'
complete -c abrt-action-analyze-xorg -s v -d 'Be more verbose.  Can be given multiple times'

