# abrt-cli
# Autogenerated from man page /usr/share/man/man1/abrt-cli.1.gz
complete -c abrt-cli -s a -l auth -d 'Authenticate and show all problems on this machine'
complete -c abrt-cli -s v -l version -d 'Show program\'s version number and exit'
complete -c abrt-cli -s h -l help -d 'Show help message'

