# abrt-action-analyze-backtrace
# Autogenerated from man page /usr/share/man/man1/abrt-action-analyze-backtrace.1.gz
complete -c abrt-action-analyze-backtrace -s d -d 'Path to problem directory'
complete -c abrt-action-analyze-backtrace -s v -d 'Be more verbose.  Can be given multiple times'

