# abrt-action-generate-core-backtrace
# Autogenerated from man page /usr/share/man/man1/abrt-action-generate-core-backtrace.1.gz
complete -c abrt-action-generate-core-backtrace -s d -d 'Path to problem directory'
complete -c abrt-action-generate-core-backtrace -s r -d 'Do not hash function fingerprints.  Useful for debugging'
complete -c abrt-action-generate-core-backtrace -s v -d 'Be more verbose.  Can be given multiple times'

