# abrt-handle-upload
# Autogenerated from man page /usr/share/man/man1/abrt-handle-upload.1.gz
complete -c abrt-handle-upload -s v -d 'Be more verbose.  Can be given multiple times'
complete -c abrt-handle-upload -s d -d 'Delete uploaded archive'

