# abrt-action-notify
# Autogenerated from man page /usr/share/man/man1/abrt-action-notify.1.gz
complete -c abrt-action-notify -s v -l verbose -d 'Be verbose'
complete -c abrt-action-notify -s d -l problem-dir -d 'Problem directory [Default: current directory]'
complete -c abrt-action-notify -s h -l help -d 'Show help message'
complete -c abrt-action-notify -s a -l autoreporting -d 'Force to run autoreporting event'
complete -c abrt-action-notify -s e -l autoreporting-event -d 'Overwrite autoreporting event name'

