# abrt-merge-pstoreoops
# Autogenerated from man page /usr/share/man/man1/abrt-merge-pstoreoops.1.gz
complete -c abrt-merge-pstoreoops -s o -d 'Print found oopses'
complete -c abrt-merge-pstoreoops -s d -d 'Delete files with found oopses'
complete -c abrt-merge-pstoreoops -s v -l verbose -d 'Be more verbose.  Can be given multiple times'

