# abrt-action-analyze-vmcore
# Autogenerated from man page /usr/share/man/man1/abrt-action-analyze-vmcore.1.gz
complete -c abrt-action-analyze-vmcore -s d -d 'Path to a problem directory'
complete -c abrt-action-analyze-vmcore -s v -d 'Be more verbose.  Can be given multiple times'
complete -c abrt-action-analyze-vmcore -l core -d 'Path to vmcore to analyze (Default: . /vmcore)'

