# abrt-dump-xorg
# Autogenerated from man page /usr/share/man/man1/abrt-dump-xorg.1.gz
complete -c abrt-dump-xorg -s v -l verbose -d 'Be more verbose.  Can be given multiple times'
complete -c abrt-dump-xorg -s s -d 'Log to syslog'
complete -c abrt-dump-xorg -s o -d 'Print found crash data on standard output'
complete -c abrt-dump-xorg -s d -d 'Create new problem directory in DIR for every crash found'
complete -c abrt-dump-xorg -s D -d 'Same as -d DumpLocation, DumpLocation is specified in abrt. conf'
complete -c abrt-dump-xorg -s x -d 'Make the problem directory world readable.  Usable only with -d/-D'
complete -c abrt-dump-xorg -s m -d 'Print search string(s) for abrt-watch-log to stdout and exit'

