# abrtd
# Autogenerated from man page /usr/share/man/man8/abrtd.8.gz
complete -c abrtd -s v -d 'Log more detailed debugging information'
complete -c abrtd -s d -d 'Stay in the foreground and log to standard error'
complete -c abrtd -s s -d 'Log to system log even with option -d'
complete -c abrtd -s t -d 'Exit after NUM seconds of inactivity'
complete -c abrtd -s p -d 'Add program names to log'

