# abrt-action-generate-backtrace
# Autogenerated from man page /usr/share/man/man1/abrt-action-generate-backtrace.1.gz
complete -c abrt-action-generate-backtrace -s d -d 'Path to problem directory'
complete -c abrt-action-generate-backtrace -s v -d 'Be more verbose.  Can be given multiple times'
complete -c abrt-action-generate-backtrace -s t -d 'Kill gdb if it runs for more than NUM seconds'

