# abrt-action-analyze-oops
# Autogenerated from man page /usr/share/man/man1/abrt-action-analyze-oops.1.gz
complete -c abrt-action-analyze-oops -s d -d 'Path to a problem directory'
complete -c abrt-action-analyze-oops -s v -d 'Be more verbose.  Can be given multiple times'

