# abrt-action-analyze-ccpp-local
# Autogenerated from man page /usr/share/man/man1/abrt-action-analyze-ccpp-local.1.gz
complete -c abrt-action-analyze-ccpp-local -l without-bz -d 'Don\'t search bugzilla for existing duplicates'
complete -c abrt-action-analyze-ccpp-local -l without-bodhi -d 'Don\'t search bodhi for existing updates'

