# abrt-action-save-package-data
# Autogenerated from man page /usr/share/man/man1/abrt-action-save-package-data.1.gz
complete -c abrt-action-save-package-data -s v -l verbose -d 'Be verbose'
complete -c abrt-action-save-package-data -s c -d 'Path to configuration file'
complete -c abrt-action-save-package-data -s r -d 'Force RPM to use CHROOT for root directory'
complete -c abrt-action-save-package-data -s d -d 'Path to problem directory'

