# abrt-watch-log
# Autogenerated from man page /usr/share/man/man1/abrt-watch-log.1.gz
complete -c abrt-watch-log -s F -d 'Don\'t run PROG if STRs aren\'t found'
complete -c abrt-watch-log -s v -l verbose -d 'Be more verbose.  Can be given multiple times'
complete -c abrt-watch-log -s s -d 'Log to syslog'

