# abrt-bodhi
# Autogenerated from man page /usr/share/man/man1/abrt-bodhi.1.gz
complete -c abrt-bodhi -s v -l verbose -d 'Be verbose'
complete -c abrt-bodhi -s r -l release -d 'Specify a release (f36|rawhide)'
complete -c abrt-bodhi -s d -l problem-dir -d 'Path to problem directory'
complete -c abrt-bodhi -s u -l url -d 'Specify a bodhi server url'
complete -c abrt-bodhi -s b -l bugs -l bugs

