# abrt-action-find-bodhi-update
# Autogenerated from man page /usr/share/man/man1/abrt-action-find-bodhi-update.1.gz
complete -c abrt-action-find-bodhi-update -s v -l verbose -d 'Be verbose'
complete -c abrt-action-find-bodhi-update -s b -l without-bodhi -d 'Run without abrt-bodhi'
complete -c abrt-action-find-bodhi-update -s d -l problem-dir -d 'Problem directory [Default: current directory]'

