# ac
# Autogenerated from man page /usr/share/man/man1/ac.1.gz
complete -c ac -s d -l daily-totals -d 'Print totals for each day rather than just one big total at the end'
complete -c ac -s p -l individual-totals -d 'Print time totals for each user in addition to the usual everything-lumped-in…'
complete -c ac -s f -l file -d 'Read from the file   filename instead of the system\'s   wtmp file'
complete -c ac -l complain -d 'When the   wtmp file has a problem (a time-warp, missing record, or whatever)…'
complete -c ac -l reboots -d 'Reboot records are NOT written at the time of a reboot, but when the system r…'
complete -c ac -l supplants -d 'Sometimes, a logout record is not written for a specific terminal, so the tim…'
complete -c ac -l timewarps -d 'Sometimes, entries in a  wtmp file will suddenly jump back into the past with…'
complete -c ac -l compatibility -d 'This is shorthand for typing out the three above options'
complete -c ac -s a -l all-days -d 'If we\'re printing daily totals, print a record for every day instead of skipp…'
complete -c ac -l tw-leniency -d 'Set the time warp leniency to   num  seconds'
complete -c ac -l tw-suspicious -d 'Set the time warp suspicious value to   num  seconds'
complete -c ac -s y -l print-year -d 'Print year when displaying dates'
complete -c ac -s z -l print-zeros -d 'If a total for any category (save the grand total) is zero, print it'
complete -c ac -l debug -d 'Print verbose internal information'
complete -c ac -s V -l version -d 'Print the version number of   ac to standard output and quit'
complete -c ac -s h -l help -d 'Prints the usage string and default locations of system files to standard out…'

