# accton
# Autogenerated from man page /usr/share/man/man8/accton.8.gz
complete -c accton -s V -l version -d 'Print the version number of   ac to standard output and quit'
complete -c accton -s h -l help -d 'Prints the usage string and default locations of system files to standard out…'

