# aha
# Autogenerated from man page /usr/share/man/man1/aha.1.gz
complete -c aha -s b -d 'Style HTML output to use a black background with white text'
complete -c aha -s c -d 'Adds the given css file to the output'
complete -c aha -s f -d 'Read from file instead of from the standard input'
complete -c aha -s h -d 'Print help for aha to the standard output'
complete -c aha -s i -d 'Use the ISO-8859- Ns Ar X character encoding instead of UTF-8 for the output,…'
complete -c aha -s l -d 'Use a fix for inputs using control sequences to change the cursor position'
complete -c aha -s L -d 'Uses the ISO-639-1 Ns code LANG for the language'
complete -c aha -s n -d 'Do not enclose HTML output in <html> , <head> and <body> tags'
complete -c aha -s p -d 'Style HTML output to use a pink background'
complete -c aha -s r -d 'Ignore all carriage-returns (ASCII sign 13, \\\\r) which may lead to double new…'
complete -c aha -s s -d 'Use a stylesheet instead of inline styles'
complete -c aha -s t -d 'Set the HTML document title to TITLE instead of stdin or the filename'
complete -c aha -s v -d 'Print version number of aha to the standard output and exit'
complete -c aha -s w -d 'Wrap long lines in the html output'
complete -c aha -s x -d 'Don\'t use doctype xml but html (may useful for old browsers like IE)'
complete -c aha -s y -d 'Sets the style used in the <body> element to STYLE after styles set by other …'

