# akmods
# Autogenerated from man page /usr/share/man/man1/akmods.1.gz
complete -c akmods -l force
complete -c akmods -l kernels -d '(formatted the same as \'uname -r\' would produce)'
complete -c akmods -l akmod

