# akmodsbuild
# Autogenerated from man page /usr/share/man/man1/akmodsbuild.1.gz
complete -c akmodsbuild -s k -l kernels -o 'r\''
complete -c akmodsbuild -s l -l logfile
complete -c akmodsbuild -s o -l outputdir
complete -c akmodsbuild -s t -l target -o 'm\''
complete -c akmodsbuild -s v -l verbose
complete -c akmodsbuild -s q -l quiet
complete -c akmodsbuild -s h -l help
complete -c akmodsbuild -s V -l version

