# anacron
# Autogenerated from man page /usr/share/man/man8/anacron.8.gz
complete -c anacron -s f -d 'Forces execution of all jobs, ignoring any timestamps'
complete -c anacron -s u -d 'Updates the timestamps of all jobs to the current date, but does not run any'
complete -c anacron -s s -d 'Serializes execution of jobs'
complete -c anacron -s n -d 'Runs jobs immediately and ignores the specified delays in the  /etc/anacronta…'
complete -c anacron -s d -d 'Does not fork Anacron to the background'
complete -c anacron -s q -d 'Suppresses any messages to standard error.   Only applicable with  -d '
complete -c anacron -s t -d 'Uses the specified anacrontab, rather than the  /etc/anacrontab default one'
complete -c anacron -s T -d 'Anacrontab testing'
complete -c anacron -s S -d 'Uses the specified spooldir to store timestamps in'
complete -c anacron -s V -d 'Prints version information, and exits'
complete -c anacron -s h -d 'Prints short usage message, and exits'

