# antiword
# Autogenerated from man page /usr/share/man/man1/antiword.1.gz
complete -c antiword -s a -d 'Output in Adobe PDF form'
complete -c antiword -s f -d 'Output in formatted text form'
complete -c antiword -s h -d 'Give a help message'
complete -c antiword -s i -d 'The image level determines how images will be shown. RS'
complete -c antiword -s m -d 'This file is used to map Unicode characters to your local character set'
complete -c antiword -s p -d 'Output in PostScript form'
complete -c antiword -s r -d 'Include text removed by the revisioning system'
complete -c antiword -s s -d 'Include text with the so-called "hidden text" attribute'
complete -c antiword -s t -d 'Output in text form.  (default)'
complete -c antiword -s w -d 'In text mode this is the line width in characters'
complete -c antiword -s x -d 'Output in XML form'
complete -c antiword -s L -d 'In PostScript mode: use landscape mode'

