# aria_ftdump
# Autogenerated from man page /usr/share/man/man1/aria_ftdump.1.gz
complete -c aria_ftdump -s '?' -s h -l help -d 'Display help and exit'
complete -c aria_ftdump -s c -l count -d 'Calculate per-word stats (counts and global weights)'
complete -c aria_ftdump -s d -l dump -d 'Dump index (incl.  data offsets and word weights)'
complete -c aria_ftdump -s l -l length -d 'Report length distribution'
complete -c aria_ftdump -s s -l stats -d 'Report global stats'
complete -c aria_ftdump -s v -l verbose -d 'Be verbose'

