# ark
# Autogenerated from man page /usr/share/man/man1/ark.1.gz
complete -c ark -s d -l dialog -d 'Show a dialog for specifying the options for a batch or add operation'
complete -c ark -s m -l mimetypes -d 'List supported MIME types'
complete -c ark -s o -l destination -d 'Default the extraction directory to directory'
complete -c ark -s c -l add -d 'Query the user for an archive filename and add specified files to it'
complete -c ark -s t -l add-to -d 'Add the specified files to filename.  Create archive if it does not exist'
complete -c ark -s p -l changetofirstpath -d 'Change the current directory to the first entry and add all other entries rel…'
complete -c ark -s f -l autofilename -d 'Automatically choose a filename, with the selected suffix (for example rar, t…'
complete -c ark -s b -l batch -d 'Use the batch interface instead of the usual dialog'
complete -c ark -s e -l autodestination -d 'The destination argument will be set to the path of the first file supplied'
complete -c ark -s a -l autosubfolder -d 'Archive contents will be read, and if detected to not be a single folder arch…'
complete -c ark -s O -l opendestination -d 'Open the destination folder when the extraction is complete'

