# atd
# Autogenerated from man page /usr/share/man/man8/atd.8.gz
complete -c atd -s l -d 'Specifies a limiting load factor, over which batch jobs should not be run, in…'
complete -c atd -s b -d 'Specify the minimum interval in seconds between the start of two batch jobs (…'
complete -c atd -s d -d 'Debug; print error messages to standard error instead of using  syslog (3) '
complete -c atd -s f -d 'Run  atd in the foreground'
complete -c atd -s s -d 'Process the at/batch queue only once'
complete -c atd -s n -d 'Append the hostname of the system to the subject of the e-mails sent by atd '

