# atrm
# Autogenerated from man page /usr/share/man/man1/atrm.1.gz
complete -c atrm -s V -d 'prints the version number to standard error and exit successfully'
complete -c atrm -s q -d 'uses the specified queue'
complete -c atrm -s m -d 'Send mail to the user when the job has completed even if there was no output'
complete -c atrm -s M -d 'Never send mail to the user'
complete -c atrm -s u -d 'Sends mail to   username rather than the current user'
complete -c atrm -s f -d 'Reads the job from  file rather than standard input'
complete -c atrm -s t -d 'run the job at R time , given in the format [[CC]YY]MMDDhhmm[. ss]'
complete -c atrm -s l -d 'Is an alias for  atq'
complete -c atrm -s r -d 'Is an alias for  atrm'
complete -c atrm -s d -d 'Is an alias for  atrm'
complete -c atrm -s b -d 'is an alias for  batch '
complete -c atrm -s v -d 'Shows the time the job will be executed before reading the job'
complete -c atrm -s c -d 'cats the jobs listed on the command line to standard output'
complete -c atrm -s o -d 'strftime-like time format used for the job list FILES /var/spool/at'

