# b43-fwcutter
# Autogenerated from man page /usr/share/man/man1/b43-fwcutter.1.gz
complete -c b43-fwcutter -s l -l list -d 'List supported driver versions'
complete -c b43-fwcutter -s i -l identify -d 'Only identify the driver file (don\'t extract)'
complete -c b43-fwcutter -s w -l target-dir -d 'Extract and write firmware to DIR'
complete -c b43-fwcutter -s a -l alt-iv -d 'Extract alternative initvals (only 3. 10. x. x)'
complete -c b43-fwcutter -s v -l version -d 'Print b43-fwcutter version'
complete -c b43-fwcutter -s h -l help -d 'Print help information AUTHORS b43 development team, http://wireless. kernel'

