# bcache-status
# Autogenerated from man page /usr/share/man/man8/bcache-status.8.gz
complete -c bcache-status -l -help -d 'Print help message and exit'
complete -c bcache-status -s f -l five-minute -d 'Print the last five minutes of stats'
complete -c bcache-status -s h -l hour -d 'Print the last hour of stats'
complete -c bcache-status -s d -l day -d 'Print the last day of stats'
complete -c bcache-status -s t -l total -d 'Print total stats'
complete -c bcache-status -s a -l all -d 'Print all stats'
complete -c bcache-status -s r -l reset-stats -d 'Reset stats after printing them'
complete -c bcache-status -s s -l sub-status -d 'Print subdevice status'
complete -c bcache-status -s g -l gc -d 'Invoke GC before printing status (root only)'

