# blivet-gui
# Autogenerated from man page /usr/share/man/man1/blivet-gui.1.gz
complete -c blivet-gui -s h -l help -d 'show this help information and exit'
complete -c blivet-gui -s v -l version -d 'show version information and exit'

