# cancel-cups
# Autogenerated from man page /usr/share/man/man1/cancel-cups.1.gz
complete -c cancel-cups -s a -d 'Cancel all jobs on the named destination, or all jobs on all destinations if …'
complete -c cancel-cups -s E -d 'Forces encryption when connecting to the server'
complete -c cancel-cups -s h -d 'Specifies an alternate server'
complete -c cancel-cups -s U -d 'Specifies the username to use when connecting to the server'
complete -c cancel-cups -s u -d 'Cancels jobs owned by username'
complete -c cancel-cups -s x -d 'Deletes job data files in addition to canceling'

