# cardos-tool
# Autogenerated from man page /usr/share/man/man1/cardos-tool.1.gz
complete -c cardos-tool -l format -s f -d 'Format the card or token'
complete -c cardos-tool -l help -s h -d 'Print help message on screen'
complete -c cardos-tool -l info -s i -d 'Display information about the card or token'
complete -c cardos-tool -l reader -s r -d 'Number of the reader to use'
complete -c cardos-tool -l startkey -s s -d 'Specify startkey for format'
complete -c cardos-tool -l change-startkey -s S -d 'Change Startkey with given APDU command'
complete -c cardos-tool -l verbose -s v -d 'Causes cardos-tool to be more verbose'
complete -c cardos-tool -l wait -s w -d 'Causes cardos-tool to wait for the token to be inserted into reader'

