# ccrewrite
# Autogenerated from man page /usr/share/man/man1/ccrewrite.1.gz
complete -c ccrewrite -l assembly -d 'The assembly to rewrite'
complete -c ccrewrite -l debug -d 'Use debug information if available to improve the usefulness of contract fail…'
complete -c ccrewrite -l help -d 'Show help for ccrewrite, listing configuration options'
complete -c ccrewrite -l level -d 'Set which contract types are present in rewritten assembly: 0 = No contracts;…'
complete -c ccrewrite -l output -d 'Write the rewritten assembly to the specified file'
complete -c ccrewrite -l rewrite -d 'Rewrite the assembly.  If false, then nothing is done'
complete -c ccrewrite -l throwOnFailure -d 'Throw a ContractException on unhandled contract failure'

