# certmgr
# Autogenerated from man page /usr/share/man/man1/certmgr.1.gz
complete -c certmgr -s m -d 'Use the machine\'s certificate stores (instead of the default user\'s stores)'
complete -c certmgr -s v -d 'More details displayed on the console'
complete -c certmgr -s p -d 'Use the specified password when accessing a pkcs12 file'
complete -c certmgr -o list -d 'List the certificates, CTL or CTL in the specified store'
complete -c certmgr -o add -d 'Add a certificate, CRL or CTL to specified store'
complete -c certmgr -o del -d 'Remove a certificate, CRL or CTL from specified store'
complete -c certmgr -o put -d 'Copy a certificate, CRL or CTL from a store to a file'
complete -c certmgr -o ssl -d 'Download and add the certificates from a SSL session'
complete -c certmgr -o importKey -d 'Allows importing a private key from a pkcs12 file into a local key pair store'
complete -c certmgr -s c -o cert -o certificate -d 'Add, Delete or Put certificates'
complete -c certmgr -o crl -d 'Add, Delete or Put certificate revocation lists (CRL)'
complete -c certmgr -o ctl -d 'Add, Delete or Put certificate trust lists (CRL).  UNSUPPORTED'
complete -c certmgr -o help -s h -s '?' -d 'Display help about this tool'

