# chardetect
# Autogenerated from man page /usr/share/man/man1/chardetect.1.gz
complete -c chardetect -s h -l help -d 'show a help message and exit'
complete -c chardetect -l minimal -d 'Print only the encoding to standard output'
complete -c chardetect -s l -l legacy -d 'Rename legacy encodings to more modern ones'
complete -c chardetect -l version -d 'show program\'s version number and exit'

