# chcat
# Autogenerated from man page /usr/share/man/man8/chcat.8.gz
complete -c chcat -s d -d 'delete the category from each FILE/USER'
complete -c chcat -s L -d 'list available categories'
complete -c chcat -s l -d 'Tells chcat to operate on users instead of files.  SEE ALSO'

