# checkmodule
# Autogenerated from man page /usr/share/man/man8/checkmodule.8.gz
complete -c checkmodule -s b -l binary -d 'Read an existing binary policy module file rather than a source policy module…'
complete -c checkmodule -s C -l cil -d 'Write CIL policy file rather than binary policy file'
complete -c checkmodule -s E -l werror -d 'Treat warnings as errors'
complete -c checkmodule -s h -l help -d 'Print usage'
complete -c checkmodule -s m -d 'Generate a non-base policy module'
complete -c checkmodule -s M -l mls -d 'Enable the MLS/MCS support when checking and compiling the policy module'
complete -c checkmodule -s V -l version -d 'Show policy versions created by this program'
complete -c checkmodule -s o -l output -d 'Write a binary policy module file to the specified filename'
complete -c checkmodule -s U -l handle-unknown -d 'Specify how the kernel should handle unknown classes or permissions (deny, al…'
complete -c checkmodule -s c -d 'Specify the policy version, defaults to the latest'

