# checkisomd5
# Autogenerated from man page /usr/share/man/man1/checkisomd5.1.gz
complete -c checkisomd5 -l md5sumonly -d 'Do not check the target'
complete -c checkisomd5 -l verbose -d 'Display human-readable progress as the target is checked'

