# chkconfig
# Autogenerated from man page /usr/share/man/man8/chkconfig.8.gz
complete -c chkconfig -l level -d 'Specifies the run levels an operation should pertain to'
complete -c chkconfig -l no-redirect -d 'When chkconfig is run on a system that uses systemd as its init system, chkco…'
complete -c chkconfig -l add -d 'This option adds a new service for management by chkconfig'
complete -c chkconfig -l del -d 'The service is removed from chkconfig management, and any symbolic links in /…'
complete -c chkconfig -l override -d 'If service name is configured exactly as it would be if the --add option had …'
complete -c chkconfig -l list -d 'This option lists all of the services which chkconfig knows about, and whethe…'

