# chktrust
# Autogenerated from man page /usr/share/man/man1/chktrust.1.gz
complete -c chktrust -s q -o quiet -d 'Quiet mode.  Limited display on console'
complete -c chktrust -s v -o verbose -d 'Verbose mode.  More details displayed on the console'
complete -c chktrust -o help -s h -s '?' -d 'Display help about this tool'

