# clinfo
# Autogenerated from man page /usr/share/man/man1/clinfo.1.gz
complete -c clinfo -s a -l all-props -d 'try to retrieve all properties, even those not officially supported (e. g'
complete -c clinfo -s A -l always-all-props -d 'like  -a , but also show errors;'
complete -c clinfo -l human -d 'produce human-friendly output; this is the default (except as noted below);'
complete -c clinfo -l raw -d 'produce machine-friendly output; this is the default if  clinfo is invoked wi…'
complete -c clinfo -l json -d 'outputs the raw data (cf'
complete -c clinfo -l offline -d 'shows also offline devices for platforms that expose this feature;'
complete -c clinfo -s l -l list -d 'list platforms and devices by name, with no (other) properties;'
complete -c clinfo -s d -d 'TQ  --device " platform_index" : device_index only show properties for the sp…'
complete -c clinfo -l prop -d 'only show properties whose symbolic name matches (contains as a substring) th…'
complete -c clinfo -s h -s '?' -d 'show usage;'
complete -c clinfo -l device -d 'only show properties for the specified device in the specified platform;'
complete -c clinfo -l version -s v -d 'show program version'

