# compsize
# Autogenerated from man page /usr/share/man/man8/compsize.8.gz
complete -c compsize -s b -l bytes -d 'Show raw byte counts rather than human-friendly sizes'
complete -c compsize -l reflink
complete -c compsize -s x -l one-file-system -d 'Skip files and directories on different file systems.  SIGNALS'

