# convertquota
# Autogenerated from man page /usr/share/man/man8/convertquota.8.gz
complete -c convertquota -s u -l user -d 'convert user quota file.  This is the default'
complete -c convertquota -s g -l group -d 'convert group quota file'
complete -c convertquota -s f -l convert-format -d 'convert quota file from  oldformat to R newformat '
complete -c convertquota -s e -l convert-endian -d 'convert vfsv0 file format from big endian to little endian (old kernels had a…'
complete -c convertquota -s V -l version -d 'print version information.  FILES'

