# crlupdate
# Autogenerated from man page /usr/share/man/man1/crlupdate.1.gz
complete -c crlupdate -s m -d 'Update CRL associated with certificates in the machine store'
complete -c crlupdate -s v -d 'Verbose mode'
complete -c crlupdate -s f -d 'Force the download of all CRL even if they are not normally due to be  update…'

