# cronnext
# Autogenerated from man page /usr/share/man/man1/cronnext.1.gz
complete -c cronnext -s i -d 'Consider only the crontabs of the specified users'
complete -c cronnext -s e -d 'Do not consider the crontabs of the specified users'
complete -c cronnext -s s -d 'Do not consider the system crontab, usually the  /etc/crontab file'
complete -c cronnext -s a -d 'Use the crontabs installed in the system in addition to the ones passed as fi…'
complete -c cronnext -s t -d 'Determine the next job from this time, instead of now'
complete -c cronnext -s q -d 'Do not check jobs over this time, expressed in the same way as in option  -t '
complete -c cronnext -s j -d 'Only look for jobs that contain command as a substring'
complete -c cronnext -s l -d 'Print the whole entries of the jobs that are the next to be executed by cron'
complete -c cronnext -s c -d 'Print every entry in every crontab with the next time it is executed'
complete -c cronnext -s f -d 'Print all jobs that are executed in the given interval.  Requires option -q'
complete -c cronnext -s h -d 'Print usage output and exit'
complete -c cronnext -s V -d 'Print version and exit.  AUTHOR'

