# cron
# Autogenerated from man page /usr/share/man/man8/cron.8.gz
complete -c cron -s h -d 'Prints a help message and exits'
complete -c cron -s i -d 'Disables inotify support'
complete -c cron -s m -d 'This option allows you to specify a shell command to use for sending  Cron ma…'
complete -c cron -s n -d 'Tells the daemon to run in the foreground'
complete -c cron -s f -d 'the same as -n, consistent with other crond implementations'
complete -c cron -s p -d 'Allows  Cron to accept any user set crontables'
complete -c cron -s P -d 'Don\'t set PATH.   PATH is instead inherited from the environment'
complete -c cron -s c -d 'This option enables clustering support, as described below'
complete -c cron -s s -d 'This option will direct  Cron to send the job output to the system log using …'
complete -c cron -s x -d 'This option allows you to set debug flags'

