# crontab
# Autogenerated from man page /usr/share/man/man1/crontab.1.gz
complete -c crontab -s u -d 'Specifies the name of the user whose crontab is to be modified'
complete -c crontab -s T -d 'Test the crontab file syntax without installing it'
complete -c crontab -s l -d 'Displays the current crontab on standard output'
complete -c crontab -s r -d 'Removes the current crontab'
complete -c crontab -s e -d 'Edits the current crontab using the editor specified by the  VISUAL or  EDITO…'
complete -c crontab -s i -d 'This option modifies the  "-r" option to prompt the user for a \'y/Y\' response…'
complete -c crontab -s s -d 'Appends the current SELinux security context string as an MLS_LEVEL setting t…'
complete -c crontab -s n -d 'This option is relevant only if  cron (8) was started with the  -c option, to…'
complete -c crontab -s c -d 'This option is only relevant if  cron (8) was started with the  -c option, to…'

