# cryfs
# Autogenerated from man page /usr/share/man/man1/cryfs.1.gz
complete -c cryfs -s h -l help -d ' Show a help message containing short descriptions for all options'
complete -c cryfs -l show-ciphers -d ' Show a list of all supported encryption ciphers'
complete -c cryfs -l version -d ' Show the CryFS version number. SS Encryption parameters '
complete -c cryfs -l blocksize -d ' Set the block size to arg bytes.  Defaults to  32768 '
complete -c cryfs -l cipher -d ' Use arg as the cipher for the encryption.  Defaults to  aes-256-gcm '
complete -c cryfs -s c -l config -d ' Use file as configuration file for this CryFS storage instead of basedir/cry…'
complete -c cryfs -s f -l foreground -d ' Run CryFS in the foreground.  Stop using CTRL-C'
complete -c cryfs -l allow-filesystem-upgrade -d ' Allow upgrading the file system if it was created with an old CryFS version'
complete -c cryfs -l allow-integrity-violations -d ' By default, CryFS checks for integrity violations, i. e'
complete -c cryfs -l allow-replaced-filesystem -d ' By default, CryFS remembers file systems it has seen in this base directory …'
complete -c cryfs -l create-missing-basedir -d ' Creates the base directory even if there is no directory currently there, sk…'
complete -c cryfs -l create-missing-mountpoint -d ' Creates the mountpoint even if there is no directory currently there, skippi…'
complete -c cryfs -l missing-block-is-integrity-violation -d ' When CryFS encounters a missing ciphertext block, it cannot cannot (yet) kno…'
complete -c cryfs -l logfile -d ' Write status information to file'
complete -c cryfs -l unmount-idle
complete -c cryfs -s o -l fuse-option

