# cryptoflex-tool
# Autogenerated from man page /usr/share/man/man1/cryptoflex-tool.1.gz
complete -c cryptoflex-tool -l app-df -s a -d 'Specifies the DF to operate in'
complete -c cryptoflex-tool -l create-key-files -s c -d 'Creates new RSA key files for arg keys'
complete -c cryptoflex-tool -l create-pin-files -s P -d 'Creates new PIN file for CHVid'
complete -c cryptoflex-tool -l exponent -s e -d 'Specifies the RSA exponent, exp, to use in key generation'
complete -c cryptoflex-tool -l generate-key -s g -d 'Generate a new RSA key pair'
complete -c cryptoflex-tool -l key-num -s k -d 'Specifies the key number to operate on.  The default is key number 1'
complete -c cryptoflex-tool -l list-keys -s l -d 'Lists all keys stored in a public key file'
complete -c cryptoflex-tool -l modulus-length -s m -d 'Specifies the modulus length to use in key generation'
complete -c cryptoflex-tool -l prkey-file -s p -d 'Specifies the private key file id, id, to use'
complete -c cryptoflex-tool -l pubkey-file -s u -d 'Specifies the public key file id, id, to use'
complete -c cryptoflex-tool -l read-key -s R -d 'Reads a public key from the card, allowing the user to extract and store or u…'
complete -c cryptoflex-tool -l reader -s r -d 'Number of the reader to use'
complete -c cryptoflex-tool -l verbose -s v -d 'Causes cryptoflex-tool to be more verbose'
complete -c cryptoflex-tool -l verify-pin -s V -d 'Verifies CHV1 before issuing commands'
complete -c cryptoflex-tool -l wait -s w -d 'Causes cryptoflex-tool to wait for a card insertion'

