# cryptsetup-ssh
# Autogenerated from man page /usr/share/man/man8/cryptsetup-ssh.8.gz
complete -c cryptsetup-ssh -l key-slot
complete -c cryptsetup-ssh -l ssh-keypath
complete -c cryptsetup-ssh -l ssh-path
complete -c cryptsetup-ssh -l ssh-server
complete -c cryptsetup-ssh -l ssh-user
complete -c cryptsetup-ssh -l debug
complete -c cryptsetup-ssh -l debug-json
complete -c cryptsetup-ssh -l verbose -s v
complete -c cryptsetup-ssh -l help -s '?'
complete -c cryptsetup-ssh -l version -s V

