# csharp
# Autogenerated from man page /usr/share/man/man1/csharp.1.gz
complete -c csharp -s s -d 'This option is ideal for authoring executable scripts that utilize the Unix s…'
complete -c csharp -l attach -d 'This is an advanced option and should only be used if you have a deep underst…'
complete -c csharp -s e -d 'This will evaluate the specified C# EXPRESSION and exit OPERATION Once you la…'

