# debugfs.ocfs2
# Autogenerated from man page /usr/share/man/man8/debugfs.ocfs2.8.gz
complete -c 'debugfs.ocfs2' -s d -l decode -d 'Display the information encoded in the lockname'
complete -c 'debugfs.ocfs2' -s e -l encode -d 'Display the lockname obtained by encoding the arguments provided'
complete -c 'debugfs.ocfs2' -s f -l file -d 'Executes the debugfs commands in cmdfile'
complete -c 'debugfs.ocfs2' -s i -l image -d 'Specifies device is an o2image file created by o2image tool'
complete -c 'debugfs.ocfs2' -s l -d 'Control OCFS2 filesystem tracing by enabling and disabling trace bits'
complete -c 'debugfs.ocfs2' -s n -l noprompt -d 'Hide prompt'
complete -c 'debugfs.ocfs2' -s R -l request -d 'Executes a single debugfs command'
complete -c 'debugfs.ocfs2' -s s -l superblock -d mkfs
complete -c 'debugfs.ocfs2' -s w -l write -d 'Opens the filesystem in RW mode'
complete -c 'debugfs.ocfs2' -s V -l version -d 'Display version and exit'

