# defragfs.ocfs2
# Autogenerated from man page /usr/share/man/man8/defragfs.ocfs2.8.gz
complete -c 'defragfs.ocfs2' -s c -d 'Print the numbers of files that should be processed'
complete -c 'defragfs.ocfs2' -s v -d 'verbose mode, the current fragmentation count and the ideal fragmentation cou…'
complete -c 'defragfs.ocfs2' -s l -d defragfs
complete -c 'defragfs.ocfs2' -s g -d 'defragfs. ocfs2 regularly records the current progress'
complete -c 'defragfs.ocfs2' -s h -d 'Print help info'

