# derdump
# Autogenerated from man page /usr/share/man/man1/derdump.1.gz
complete -c derdump -s r -d 'For formatted items, dump raw bytes as well'
complete -c derdump -s i -d 'Define an input file to use (default is stdin)'
complete -c derdump -s o -d 'Define an output file to use (default is stdout)'

