# desktoptojson
# Autogenerated from man page /usr/share/man/man8/desktoptojson.8.gz
complete -c desktoptojson -l input -d 'The . desktop file to convert'
complete -c desktoptojson -l output -d 'The file to write the generated JSON data to'
complete -c desktoptojson -l help -d 'Show a brief help text'
complete -c desktoptojson -l version -d 'Show version information'

