# disco
# Autogenerated from man page /usr/share/man/man1/disco.1.gz
complete -c disco -o nologo -d 'Suppress the startup logo'
complete -c disco -o nosave -d 'Do not save the discovered documents to disk'
complete -c disco -o o:directory -o out:directory -d 'The directory where to save the discovered documents'
complete -c disco -o u:username -o user:username -d 'The user name to use when connecting to the server'
complete -c disco -o p:password -o password:password -d 'The password to use when connecting to the server'
complete -c disco -o d:domain -o domain:domain -d 'The domain to use when connecting to the server'
complete -c disco -o proxy:url -d 'The url of the proxy server to use for http requests'
complete -c disco -o proxyusername:username -d 'The user name to use when connecting to the proxy'
complete -c disco -o proxypassword:password -d 'The password to use when connecting to the proxy'
complete -c disco -o proxydomain:domain -d 'The domain to use when connecting to the proxy'

