# dnfdragora
# Autogenerated from man page /usr/share/man/man8/dnfdragora.8.gz
complete -c dnfdragora -s h -l help -d 'Show help message and exit'
complete -c dnfdragora -l gtk -d 'Start using yui GTK+ plugin implementation'
complete -c dnfdragora -l ncurses -d 'Start using yui ncurses plugin implementation'
complete -c dnfdragora -l qt -d 'Start using yui Qt plugin implementation'
complete -c dnfdragora -l fullscreen -d 'Use full screen for dialogs'
complete -c dnfdragora -l update-only -d 'Show updates dialog only'
complete -c dnfdragora -l group-icons-path -d 'Force a new path for group icons (instead of /usr/share/icons)'
complete -c dnfdragora -l 'images-path*' -d 'Force a new path for all the needed images (instead of /usr/share/dnfdragora/…'
complete -c dnfdragora -l locales-dir -d 'Set path to the directory containing localization strings (developer option o…'
complete -c dnfdragora -l install -d 'Install local rpm packages'
complete -c dnfdragora -l version -d 'Show application version and exit'
complete -c dnfdragora -l exit -d 'Force dnfdaemon dbus services used by dnfdragora to exit'

