# dnie-tool
# Autogenerated from man page /usr/share/man/man1/dnie-tool.1.gz
complete -c dnie-tool -l idesp -s i -d 'Show the DNIe IDESP value'
complete -c dnie-tool -l data -s d -d 'Show DNIe personal information'
complete -c dnie-tool -l all -s a -d 'Displays every available information'
complete -c dnie-tool -l serial -s s -d 'Displays DNIe Serial Number'
complete -c dnie-tool -l version -s V -d 'Show DNIe sw version.  Displays software version for in-card DNIe OS'
complete -c dnie-tool -l pin -s p -d 'These options can be used to specify the PIN value on the command line'
complete -c dnie-tool -l reader -s r -d 'Number of the reader to use'
complete -c dnie-tool -l wait -s w -d 'Causes dnie-tool to wait for the token to be inserted into reader'
complete -c dnie-tool -l verbose -s v -d 'Causes dnie-tool to be more verbose'

