# dnstap-read
# Autogenerated from man page /usr/share/man/man1/dnstap-read.1.gz
complete -c dnstap-read -s m -d 'This option indicates trace memory allocations, and is used for debugging mem…'
complete -c dnstap-read -s p -d 'This option prints the text form of the DNS message that was encapsulated in …'
complete -c dnstap-read -s x -d 'This option prints a hex dump of the wire form of the DNS message that was en…'
complete -c dnstap-read -s y -d 'This option prints dnstap data in a detailed YAML format'

