# dpkg-realpath
# Autogenerated from man page /usr/share/man/man1/dpkg-realpath.1.gz
complete -c dpkg-realpath -s z -l zero -d 'X Item "-z, --zero" Use a NUL byte to end output lines instead of a new line …'
complete -c dpkg-realpath -l instdir -d 'X Item "--instdir directory"'
complete -c dpkg-realpath -l root -d 'X Item "--root directory" '
complete -c dpkg-realpath -s '?' -l help -d 'X Item "-?, --help" Show the usage message and exit'
complete -c dpkg-realpath -l version

