# dpkg-query
# Autogenerated from man page /usr/share/man/man1/dpkg-query.1.gz
complete -c dpkg-query -l admindir -d 'X Item "--admindir=dir" Change the location of the dpkg database'
complete -c dpkg-query -l root -d 'X Item "--root=directory" Set the root directory to directory, which sets the…'
complete -c dpkg-query -l load-avail -d 'X Item "--load-avail" Also load the available file when using the --show and …'
complete -c dpkg-query -l no-pager -d 'X Item "--no-pager" Disables the use of any pager when showing information (s…'
complete -c dpkg-query -s f -l showformat -d 'X Item "-f, --showformat=format" This option is used to specify the format of…'
complete -c dpkg-query -s l -l list
complete -c dpkg-query -s W -l show
complete -c dpkg-query -s s -l status
complete -c dpkg-query -s L -l listfiles
complete -c dpkg-query -l control-list
complete -c dpkg-query -l control-show
complete -c dpkg-query -s c -l control-path
complete -c dpkg-query -s S -l search
complete -c dpkg-query -s p -l print-avail
complete -c dpkg-query -s '?' -l help
complete -c dpkg-query -l version

