# dpkg
# Autogenerated from man page /usr/share/man/man1/dpkg.1.gz
complete -c dpkg -l abort-after -d 'X Item "--abort-after=number" Change after how many errors dpkg will abort'
complete -c dpkg -s B -l auto-deconfigure -d 'X Item "-B, --auto-deconfigure" When a package is removed, there is a possibi…'
complete -c dpkg -o Doctal -l debug -d 'X Item "-Doctal, --debug=octal" Switch debugging on'
complete -c dpkg -l force-things -d 'X Item "--force-things"'
complete -c dpkg -l no-force-things -l refuse-things -d 'X Item "--no-force-things, --refuse-things" '
complete -c dpkg -l ignore-depends -d 'X Item "--ignore-depends=package,'
complete -c dpkg -l no-act -l dry-run -l simulate -d 'X Item "--no-act, --dry-run, --simulate" Do everything which is supposed to b…'
complete -c dpkg -s R -l recursive -d 'X Item "-R, --recursive" Recursively handle all regular files matching patter…'
complete -c dpkg -s G -d 'X Item "-G" Don\'t install a package if a newer version of the same package is…'
complete -c dpkg -l admindir -d 'X Item "--admindir=dir" Set the administrative directory to directory'
complete -c dpkg -l instdir -d 'X Item "--instdir=dir" Set the installation directory, which refers to the di…'
complete -c dpkg -l root -d 'X Item "--root=dir" Set the root directory to directory, which sets the insta…'
complete -c dpkg -s O -l selected-only -d 'X Item "-O, --selected-only" Only process the packages that are selected for …'
complete -c dpkg -s E -l skip-same-version -d 'X Item "-E, --skip-same-version" Don\'t install the package if the same versio…'
complete -c dpkg -l pre-invoke -d 'X Item "--pre-invoke=command"'
complete -c dpkg -l post-invoke -d 'X Item "--post-invoke=command" '
complete -c dpkg -l path-exclude -d 'X Item "--path-exclude=glob-pattern"'
complete -c dpkg -l path-include -d 'X Item "--path-include=glob-pattern" '
complete -c dpkg -l verify-format -d 'X Item "--verify-format format-name" Sets the output format for the --verify …'
complete -c dpkg -l status-fd -d 'X Item "--status-fd n" Send machine-readable package status and progress info…'
complete -c dpkg -l status-logger -d 'X Item "--status-logger=command" Send machine-readable package status and pro…'
complete -c dpkg -l log -d 'X Item "--log=filename" Log status change updates and actions to filename, in…'
complete -c dpkg -l robot -d 'X Item "--robot" Use a machine-readable output format'
complete -c dpkg -l no-pager -d 'X Item "--no-pager" Disables the use of any pager when showing information (s…'
complete -c dpkg -l no-debsig -d 'X Item "--no-debsig" Do not try to verify package signatures'
complete -c dpkg -l no-triggers -d 'X Item "--no-triggers" Do not run any triggers in this run (since dpkg 1. 14'
complete -c dpkg -s i -l install
complete -c dpkg -l unpack
complete -c dpkg -l configure -s a -l pending
complete -c dpkg -l triggers-only
complete -c dpkg -s r -l remove
complete -c dpkg -s P -l purge
complete -c dpkg -s V -l verify
complete -c dpkg -s C -l audit
complete -c dpkg -l update-avail
complete -c dpkg -l merge-avail -d 'Update dpkg\'s and dselect\'s idea of which packages are available'
complete -c dpkg -s A -l record-avail
complete -c dpkg -l forget-old-unavail
complete -c dpkg -l clear-avail
complete -c dpkg -l get-selections
complete -c dpkg -l set-selections
complete -c dpkg -l clear-selections
complete -c dpkg -l yet-to-unpack
complete -c dpkg -l predep-package
complete -c dpkg -l add-architecture
complete -c dpkg -l remove-architecture
complete -c dpkg -l print-architecture
complete -c dpkg -l print-foreign-architectures
complete -c dpkg -l assert-help
complete -c dpkg -l assert-feature
complete -c dpkg -l validate-thing
complete -c dpkg -l compare-versions
complete -c dpkg -s '?' -l help
complete -c dpkg -l force-help
complete -c dpkg -o Dh
complete -c dpkg -l version
complete -c dpkg -s b -l build
complete -c dpkg -s c -l contents
complete -c dpkg -s e -l control
complete -c dpkg -s x -l extract
complete -c dpkg -s X -l vextract
complete -c dpkg -s f -l field
complete -c dpkg -l ctrl-tarfile
complete -c dpkg -l fsys-tarfile
complete -c dpkg -s I -l info
complete -c dpkg -s l -l list
complete -c dpkg -s s -l status
complete -c dpkg -s L -l listfiles
complete -c dpkg -s S -l search
complete -c dpkg -s p -l print-avail
complete -c dpkg -l force-confdef -d 'action is preferred'
complete -c dpkg -l force-confold -d 'that to decide the final action'
complete -c dpkg -l triggers

