# dpkg-divert
# Autogenerated from man page /usr/share/man/man1/dpkg-divert.1.gz
complete -c dpkg-divert -l admindir -d 'X Item "--admindir directory" Set the administrative directory to directory'
complete -c dpkg-divert -l instdir -d 'X Item "--instdir directory" Set the installation directory, which refers to …'
complete -c dpkg-divert -l root -d 'X Item "--root directory" Set the root directory to directory, which sets the…'
complete -c dpkg-divert -l divert -d 'X Item "--divert divert-to" divert-to is the location where the versions of f…'
complete -c dpkg-divert -l local -d 'X Item "--local" Specifies that all packages\' versions of this file are diver…'
complete -c dpkg-divert -l package -d 'X Item "--package package" package is the name of a package whose copy of fil…'
complete -c dpkg-divert -l quiet -d 'X Item "--quiet" Quiet mode, i. e.  no verbose output'
complete -c dpkg-divert -l rename -d 'X Item "--rename" Actually move the file aside (or back)'
complete -c dpkg-divert -l no-rename -d 'X Item "--no-rename" Specifies that the file should not be renamed while addi…'
complete -c dpkg-divert -l test -d 'X Item "--test" Test mode, i. e'
complete -c dpkg-divert -s '?' -l help -d 'X Item "-?, --help" Show the usage message and exit'
complete -c dpkg-divert -l remove
complete -c dpkg-divert -l list
complete -c dpkg-divert -l listpackage
complete -c dpkg-divert -l truename
complete -c dpkg-divert -l version
complete -c dpkg-divert -o old -d NOTES

