# dpkg-split
# Autogenerated from man page /usr/share/man/man1/dpkg-split.1.gz
complete -c dpkg-split -l depotdir -d 'X Item "--depotdir directory" Specifies an alternative directory for the queu…'
complete -c dpkg-split -l admindir -d 'X Item "--admindir directory" Set the administrative directory to directory (…'
complete -c dpkg-split -l root -d 'X Item "--root directory" Set the root directory to directory (since dpkg 1'
complete -c dpkg-split -s S -l partsize -d 'X Item "-S, --partsize kibibytes" Specifies the maximum part size when splitt…'
complete -c dpkg-split -s o -l output -d 'X Item "-o, --output complete-output" Specifies the output file name for a re…'
complete -c dpkg-split -s Q -l npquiet -d 'X Item "-Q, --npquiet" When doing automatic queue-or-reassembly dpkg-split us…'
complete -c dpkg-split -l split -l join -l info -d options
complete -c dpkg-split -l auto -d 'option, where it maintains a queue of parts seen but not yet reassembled and …'
complete -c dpkg-split -l listq -l discard -d 'options allow the management of the queue'
complete -c dpkg-split -s s
complete -c dpkg-split -s j
complete -c dpkg-split -s I
complete -c dpkg-split -s a
complete -c dpkg-split -s l
complete -c dpkg-split -s d
complete -c dpkg-split -s '?' -l help
complete -c dpkg-split -l version
complete -c dpkg-split -l msdos

