# dpkg-statoverride
# Autogenerated from man page /usr/share/man/man1/dpkg-statoverride.1.gz
complete -c dpkg-statoverride -l admindir -d 'X Item "--admindir directory" Set the administrative directory to directory'
complete -c dpkg-statoverride -l instdir -d 'X Item "--instdir directory" Set the installation directory, which refers to …'
complete -c dpkg-statoverride -l root -d 'X Item "--root directory" Set the root directory to directory, which sets the…'
complete -c dpkg-statoverride -l force-things -d 'X Item "--force-things"'
complete -c dpkg-statoverride -l no-force-things -l refuse-things -d 'X Item "--no-force-things, --refuse-things" '
complete -c dpkg-statoverride -l force -d 'X Item "--force" Force an action, even if a sanity check would otherwise proh…'
complete -c dpkg-statoverride -l update -d 'X Item "--update" Immediately try to change the path to the new owner and mod…'
complete -c dpkg-statoverride -l add
complete -c dpkg-statoverride -l remove
complete -c dpkg-statoverride -l list
complete -c dpkg-statoverride -l help
complete -c dpkg-statoverride -l force-help
complete -c dpkg-statoverride -l version
complete -c dpkg-statoverride -l force-all
complete -c dpkg-statoverride -l quiet

