# dpkg-deb
# Autogenerated from man page /usr/share/man/man1/dpkg-deb.1.gz
complete -c dpkg-deb -l showformat -d 'X Item "--showformat=format" This option is used to specify the format of the…'
complete -c dpkg-deb -o zcompress-level -d 'X Item "-zcompress-level" Specify which compression level to use on the compr…'
complete -c dpkg-deb -o Scompress-strategy -d 'X Item "-Scompress-strategy" Specify which compression strategy to use on the…'
complete -c dpkg-deb -o Zcompress-type -d 'X Item "-Zcompress-type" Specify which compression type to use when building …'
complete -c dpkg-deb -l uniform-compression -d 'X Item "--[no-]uniform-compression" Specify that the same compression paramet…'
complete -c dpkg-deb -l threads-max -d 'X Item "--threads-max=threads" Sets the maximum number of threads allowed for…'
complete -c dpkg-deb -l root-owner-group -d 'X Item "--root-owner-group" Set the owner and group for each entry in the fil…'
complete -c dpkg-deb -l deb-format -d 'X Item "--deb-format=format" Set the archive format version used when buildin…'
complete -c dpkg-deb -l nocheck -d 'X Item "--nocheck" Inhibits dpkg-deb --build\'s usual checks on the proposed c…'
complete -c dpkg-deb -s v -l verbose -d 'X Item "-v, --verbose" Enables verbose output (since dpkg 1. 16. 1)'
complete -c dpkg-deb -s b -l build
complete -c dpkg-deb -s I -l info
complete -c dpkg-deb -s W -l show
complete -c dpkg-deb -s f -l field
complete -c dpkg-deb -s c -l contents
complete -c dpkg-deb -s x -l extract
complete -c dpkg-deb -s X -l vextract
complete -c dpkg-deb -s R -l raw-extract
complete -c dpkg-deb -l ctrl-tarfile
complete -c dpkg-deb -l fsys-tarfile
complete -c dpkg-deb -s e -l control
complete -c dpkg-deb -s '?' -l help
complete -c dpkg-deb -l version
complete -c dpkg-deb -s D -l debug

