# dpkg-trigger
# Autogenerated from man page /usr/share/man/man1/dpkg-trigger.1.gz
complete -c dpkg-trigger -l admindir -d 'X Item "--admindir=dir" Change the location of the dpkg database'
complete -c dpkg-trigger -l root -d 'X Item "--root=directory" Set the root directory to directory, which sets the…'
complete -c dpkg-trigger -l by-package -d 'X Item "--by-package=package" Override trigger awaiter (normally set by dpkg …'
complete -c dpkg-trigger -l no-await -d 'X Item "--no-await" This option arranges that the calling package T (if any) …'
complete -c dpkg-trigger -l await -d 'X Item "--await" This option does the inverse of --no-await (since dpkg 1. 17'
complete -c dpkg-trigger -l check-supported
complete -c dpkg-trigger -s '?' -l help
complete -c dpkg-trigger -l version
complete -c dpkg-trigger -l no-act

