# dpkg-fsys-usrunmess
# Autogenerated from man page /usr/share/man/man8/dpkg-fsys-usrunmess.8.gz
complete -c dpkg-fsys-usrunmess -s p -l prompt -d 'X Item "-p, --prompt" Prompt at the time of no return, so that the debug outp…'
complete -c dpkg-fsys-usrunmess -l prevention -d 'X Item "--prevention"'
complete -c dpkg-fsys-usrunmess -l no-prevention -d 'X Item "--no-prevention" '
complete -c dpkg-fsys-usrunmess -s n -l no-act -d 'X Item "-n, --no-act"'
complete -c dpkg-fsys-usrunmess -l dry-run -d 'X Item "--dry-run" '
complete -c dpkg-fsys-usrunmess -s '?' -l help -d 'X Item "-?, --help" Show the usage message and exit'
complete -c dpkg-fsys-usrunmess -l version

