# dump_xsettings
# Autogenerated from man page /usr/share/man/man1/dump_xsettings.1.gz
complete -c dump_xsettings -s h -l help -d 'Display a help message and exit'
complete -c dump_xsettings -s s -l screen -d 'Use the X screen numbered SCREEN (default is 0)'

