# dump-acct
# Autogenerated from man page /usr/share/man/man8/dump-acct.8.gz
complete -c dump-acct -s r -l reverse -d 'Print the output in reverse order'
complete -c dump-acct -s R -l raw -d 'The records will be printed without any parsing'
complete -c dump-acct -s n -l num -d 'Display only the first NUMRECS number of records'
complete -c dump-acct -l byteswap -d 'Swap the bytes (relative to your system\'s native byte order) in --raw output'
complete -c dump-acct -l format -d 'Set output format with --raw option'
complete -c dump-acct -l ahz -d 'Set the AHZ (platform dependent frequency in Hertz) to FREQ'
complete -c dump-acct -s h -l help -d 'Print a help message and the default location of the process accounting file …'

