# dump-utmp
# Autogenerated from man page /usr/share/man/man8/dump-utmp.8.gz
complete -c dump-utmp -s h -l help -d 'Print a help message and the default location of the process accounting file …'
complete -c dump-utmp -s r -l reverse -d 'Print the output in reverse order'
complete -c dump-utmp -s R -l raw -d 'The records will be printed without any parsing'
complete -c dump-utmp -s n -l num -d 'Display only the first NUMRECS number of records'

