# dwz
# Autogenerated from man page /usr/share/man/man1/dwz.1.gz
complete -c dwz -o mFILE -l multifile -d 'Multifile mode'
complete -c dwz -o h--hardlink -d 'Look for executables or shared libraries hardlinked together, instead of rewr…'
complete -c dwz -s M -l multifile-name -d 'Specify the name of the common file that should be put into the '
complete -c dwz -s r -l relative -d 'Specify that the name of the common file to be put into the '
complete -c dwz -s p -l multifile-pointer-size -d 'Specify the pointer size of the multifile, in bytes'
complete -c dwz -l multifile-endian -d 'Specify the endianity of the multifile'
complete -c dwz -s q -l quiet -d 'Silence up some of the most common messages'
complete -c dwz -s o -l output -d 'This option instructs dwz not to overwrite the specified file, but instead st…'
complete -c dwz -s l -l low-mem-die-limit -d 'Handle executables or shared libraries containing more than COUNT debugging i…'
complete -c dwz -s L -l max-die-limit -d 'Don\'t attempt to optimize executables or shared libraries containing more tha…'
complete -c dwz -s 5 -l dwarf-5 -d 'Emit standard DWARF 5 Supplementary Object Files with '
complete -c dwz -s j -l jobs -d 'Process N files in parallel.   The default is processors / 2'
complete -c dwz -l odr -l no-odr -d Experimental
complete -c dwz -l odr-mode -d 'Set the One-Definition-Rule optimization aggressiveness: basic or link'
complete -c dwz -l import-optimize -l no-import-optimize -d 'Enable/disable optimization that reduces the number of DW_TAG_imported_unit D…'
complete -c dwz -s '?' -l help -d 'Print short help and exit'
complete -c dwz -s m -d 'given object (executable or shared library) individually, with the'
complete -c dwz -s h -l hardlink -d 'Look for executables or shared libraries hardlinked together, instead of rewr…'
complete -c dwz -s v -l version -d 'Print version number and short licensing notice and exit'

