# edquota
# Autogenerated from man page /usr/share/man/man8/edquota.8.gz
complete -c edquota -s r -l remote -d 'Edit also non-local quota use rpc. rquotad on remote server to set quota'
complete -c edquota -s m -l no-mixed-pathnames -d 'Currently, pathnames of NFSv4 mountpoints are sent without leading slash in t…'
complete -c edquota -s u -l user -d 'Edit the user quota.  This is the default'
complete -c edquota -s g -l group -d 'Edit the group quota'
complete -c edquota -s P -l project -d 'Edit the project quota'
complete -c edquota -s p -l prototype -d 'Duplicate the quotas of the prototypical user specified for each user specifi…'
complete -c edquota -l always-resolve -d 'Always try to translate user / group name to uid / gid even if the name is co…'
complete -c edquota -s F -l format -d 'Edit quota for specified format (ie.  don\'t perform format autodetection)'
complete -c edquota -s f -l filesystem -d 'Perform specified operations only for given filesystem (default is to perform…'
complete -c edquota -s t -l edit-period -d 'Edit the soft time limits for each filesystem'
complete -c edquota -s n -d 'option is equivalent, and is maintained for backward compatibility'
complete -c edquota -s T -l edit-times -d 'Edit time for the user/group/project when softlimit is enforced'

