# egk-tool
# Autogenerated from man page /usr/share/man/man1/egk-tool.1.gz
complete -c egk-tool -l help -s h -d 'Print help and exit'
complete -c egk-tool -l version -s V -d 'Print version and exit'
complete -c egk-tool -l reader -s r -d 'Number of the reader to use'
complete -c egk-tool -l verbose -s v -d 'Causes egk-tool to be more verbose'
complete -c egk-tool -l pd -d 'Show \\*(AqPersÃ¶nliche Versicherungsdaten\\*(Aq (XML)'
complete -c egk-tool -l vd -d 'Show \\*(AqAllgemeine Versicherungsdaten\\*(Aq (XML)'
complete -c egk-tool -l gvd -d 'Show \\*(AqGeschÃ¼tzte Versicherungsdaten\\*(Aq (XML)'
complete -c egk-tool -l vsd-status -d 'Show \\*(AqVersichertenstammdaten-Status\\*(Aq'

