# eidenv
# Autogenerated from man page /usr/share/man/man1/eidenv.1.gz
complete -c eidenv -l exec -s x -d 'Executes the given program with data in environment variables'
complete -c eidenv -l help -s h -d 'Print help message on screen'
complete -c eidenv -l print -s p -d 'Prints all data fields from the card, like validity period, document number e…'
complete -c eidenv -l reader -s r -d 'Number of the reader to use'
complete -c eidenv -l stats -s t -d 'Prints key usage statistics (only for Estonian ID card)'
complete -c eidenv -l version -s v -d 'Prints the version of the utility and exits'
complete -c eidenv -l wait -s w -d 'Wait for a card to be inserted'

