# epiphany
# Autogenerated from man page /usr/share/man/man1/epiphany.1.gz
complete -c epiphany -l new-window -d 'Open a new browser window instead of a new tab'
complete -c epiphany -s l -l load-session -d 'Load the given session state file'
complete -c epiphany -s i -l incognito-mode -d 'Start an instance with user data read-only'
complete -c epiphany -s p -l private-instance -d 'Start a private instance with separate user data'
complete -c epiphany -s a -l application-mode -d 'Start a private instance in web application mode (requires passing either des…'
complete -c epiphany -l automation-mode -d 'Start a private instance for WebDriver control'
complete -c epiphany -l profile -d 'Custom profile directory for private instance (optional)'
complete -c epiphany -l search -d 'Initiate search with given search term'
complete -c epiphany -s '?' -l help -d 'Show help options'
complete -c epiphany -l version -d 'Show version'

