# extresso
# Autogenerated from man page /usr/share/man/man1/extresso.1.gz
complete -c extresso -s o -l output -d 'Where to place extracted files (default `. \')'
complete -c extresso -l format -d 'Extraction format of icon resources, passed to icotool'
complete -c extresso -s b -l base -d 'Base directory of local files in scripts'
complete -c extresso -s i -l interactive -d 'Prompt before extraction'
complete -c extresso -s v -l verbose -d 'Explain what is being done'
complete -c extresso -l help -d 'Display a help message and exit'
complete -c extresso -l version -d 'Output version information and exit'

