# fedora-third-party
# Autogenerated from man page /usr/share/man/man1/fedora-third-party.1.gz
complete -c fedora-third-party -l verbose -d 'Print detailed information about what is being done'
complete -c fedora-third-party -l columns -l csv -d 'get stable output - the default set of columns may change'

