# flexiblas
# Autogenerated from man page /usr/share/man/man1/flexiblas.1.gz
complete -c flexiblas -s u -l user -d 'Edit the user\'s flexiblasrc configuration (default options, except of executi…'
complete -c flexiblas -s g -l global -d 'Edit the global flexiblasrc configuration (default in case of executing as ro…'
complete -c flexiblas -s H -l host -d 'Edit the host configuration file'
complete -c flexiblas -s E -l environment -d 'Edit the configuration file given by the environment variable FLEXIBLAS_CONFIG'
complete -c flexiblas -s p -l pipe -d 'Make the output of some commands, like list pipe compatible to use them in sc…'
complete -c flexiblas -s h -l help -d 'Print this information and exit'
complete -c flexiblas -s v -l version -d 'Print the versionformation and exit. SS Properties'

