# fsck.gfs2
# Autogenerated from man page /usr/share/man/man8/fsck.gfs2.8.gz
complete -c 'fsck.gfs2' -s a -d 'Same as the -p (preen) option'
complete -c 'fsck.gfs2' -s f -d 'Force checking even if the file system seems clean'
complete -c 'fsck.gfs2' -s h -d 'Help.   This prints out the proper command line usage syntax'
complete -c 'fsck.gfs2' -s q -d Quiet
complete -c 'fsck.gfs2' -s n -d 'No to all questions.  By specifying this option, fsck'
complete -c 'fsck.gfs2' -s p -d 'Automatically repair ("preen") the file system if it is dirty and safe to do …'
complete -c 'fsck.gfs2' -s V -d 'Print out the program version information'
complete -c 'fsck.gfs2' -s v -d 'Verbose operation.   Print more information while running'
complete -c 'fsck.gfs2' -s y -d 'Yes to all questions.  By specifying this option, fsck'

