# fsck.ocfs2
# Autogenerated from man page /usr/share/man/man8/fsck.ocfs2.8.gz
complete -c 'fsck.ocfs2' -s a -d 'This option does the same thing as the -p option'
complete -c 'fsck.ocfs2' -s b -d 'Normally, fsck'
complete -c 'fsck.ocfs2' -s B -d 'The block size, specified in bytes, can range from 512 to 4096'
complete -c 'fsck.ocfs2' -s D -d 'Optimize directories in filesystem.  This option causes fsck'
complete -c 'fsck.ocfs2' -s f -d 'Force checking even if the file system is clean'
complete -c 'fsck.ocfs2' -s F -d 'By default fsck'
complete -c 'fsck.ocfs2' -s G -d 'Usually fsck'
complete -c 'fsck.ocfs2' -s n -d 'Give the \'no\' answer to all questions that fsck will ask'
complete -c 'fsck.ocfs2' -s p -d 'Automatically repair ("preen") the file system.   This option will cause fsck'
complete -c 'fsck.ocfs2' -s P -d 'Show progress'
complete -c 'fsck.ocfs2' -s r -d mkfs
complete -c 'fsck.ocfs2' -s t -d 'Show I/O statistics'
complete -c 'fsck.ocfs2' -s y -d 'Give the \'yes\' answer to all questions that fsck will ask'
complete -c 'fsck.ocfs2' -s v -d 'This option causes fsck'

