# gacutil
# Autogenerated from man page /usr/share/man/man1/gacutil.1.gz
complete -c gacutil -o package
complete -c gacutil -s i -o root -o gacdir
complete -c gacutil -s l
complete -c gacutil -s u
complete -c gacutil -o us -d 'Uninstalls an assembly using the specified assembly\'s full name'
complete -c gacutil -o ul -d 'Uninstalls one or more assemblies from the global assembly cache'

