# genresscript
# Autogenerated from man page /usr/share/man/man1/genresscript.1.gz
complete -c genresscript -l type -d 'X list resources of this type instead of group_icon'
complete -c genresscript -l base -d 'X the default extraction name of all resources'
complete -c genresscript -l sort -d 'X sort alphabetically instead of using order in binary'
complete -c genresscript -l help -d 'X display this help and exit'
complete -c genresscript -s t
complete -c genresscript -s b
complete -c genresscript -s s
complete -c genresscript -l version

