# ges-launch-1.0
# Autogenerated from man page /usr/share/man/man1/ges-launch-1.0.1.gz
complete -c 'ges-launch-1.0' -s h -l help -d 'Show help options'
complete -c 'ges-launch-1.0' -l help-all -d 'Show all help options'
complete -c 'ges-launch-1.0' -l help-gst -d 'Show GStreamer Options'
complete -c 'ges-launch-1.0' -l help-GES -d 'Show GES Options'
complete -c 'ges-launch-1.0' -l help-project -d 'Show project-related options'
complete -c 'ges-launch-1.0' -l help-rendering -d 'Show rendering options'
complete -c 'ges-launch-1.0' -l help-playback -d 'Show playback options'

