# GET
# Autogenerated from man page /usr/share/man/man1/GET.1.gz
complete -c GET -s m
complete -c GET -s f
complete -c GET -s b
complete -c GET -s t
complete -c GET -s i
complete -c GET -s c
complete -c GET -s p
complete -c GET -s P
complete -c GET -s H
complete -c GET -s C
complete -c GET -s u
complete -c GET -s U
complete -c GET -s s
complete -c GET -s S
complete -c GET -s e
complete -c GET -s E
complete -c GET -s d
complete -c GET -s o
complete -c GET -s v
complete -c GET -s h
complete -c GET -s a

