# gfs2_grow
# Autogenerated from man page /usr/share/man/man8/gfs2_grow.8.gz
complete -c gfs2_grow -s D -d 'Print out debugging information about the filesystem layout'
complete -c gfs2_grow -s h -d 'Prints out a short usage message and exits'
complete -c gfs2_grow -s q -d 'Be quiet.   Don\'t print anything'
complete -c gfs2_grow -s T -d Test
complete -c gfs2_grow -s V -d 'Version.  Print out version information, then exit'

