# gfs2_edit
# Autogenerated from man page /usr/share/man/man8/gfs2_edit.8.gz
complete -c gfs2_edit -s p -d 'Print a gfs2 data structure in human-readable format to stdout'
complete -c gfs2_edit -o 's\\fs' -d 'Specify a starting block for interactive mode'
complete -c gfs2_edit -s h -o help -o usage -d 'Print help information'
complete -c gfs2_edit -s c -d 'Use alternate color scheme for interactive mode: 0=normal (dark colors on whi…'
complete -c gfs2_edit -s V -d 'Print program version information only'
complete -c gfs2_edit -s x -d 'Print in hex mode'
complete -c gfs2_edit -s z -d 'Compress metadata with gzip compression level 1 to 9 (default 9)'
complete -c gfs2_edit -s s -d 'Specify a starting block for interactive mode'

