# gfs2_jadd
# Autogenerated from man page /usr/share/man/man8/gfs2_jadd.8.gz
complete -c gfs2_jadd -s c -d 'Initial size of each journal\'s quota change file'
complete -c gfs2_jadd -s D -d 'Print out debugging information about the filesystem layout'
complete -c gfs2_jadd -s h -d 'Prints out a short usage message and exits'
complete -c gfs2_jadd -s J -d 'The size of the new journals in megabytes'
complete -c gfs2_jadd -s j -d 'The number of new journals to add'
complete -c gfs2_jadd -s q -d 'Be quiet.   Don\'t print anything'
complete -c gfs2_jadd -s V -d 'Version.  Print version information, then exit'

