# gfs2_convert
# Autogenerated from man page /usr/share/man/man8/gfs2_convert.8.gz
complete -c gfs2_convert -s h -d 'Help.   This prints out the proper command line usage syntax'
complete -c gfs2_convert -s q -d 'Quiet.   Print less information while running'
complete -c gfs2_convert -s n -d 'No to all questions'
complete -c gfs2_convert -s V -d 'Print program Version information only.   Print out the current version name'
complete -c gfs2_convert -s v -d 'Verbose operation.   Print more information while running'
complete -c gfs2_convert -s y -d 'Yes to all questions'

