# gh-auth-refresh
# Autogenerated from man page /usr/share/man/man1/gh-auth-refresh.1.gz
complete -c gh-auth-refresh -s h -l hostname -d 'The GitHub host to use for authentication'
complete -c gh-auth-refresh -l insecure-storage -d 'Save authentication credentials in plain text instead of credential store'
complete -c gh-auth-refresh -s s -l scopes -d 'Additional authentication scopes for gh to have EXAMPLE $ gh auth refresh --s…'

