# gh-alias-set
# Autogenerated from man page /usr/share/man/man1/gh-alias-set.1.gz
complete -c gh-alias-set -s s -l shell -d 'Declare an alias to be passed through a shell interpreter EXAMPLE # note: Com…'

