# gh-auth-status
# Autogenerated from man page /usr/share/man/man1/gh-auth-status.1.gz
complete -c gh-auth-status -s h -l hostname -d 'Check a specific hostname\'s auth status'
complete -c gh-auth-status -s t -l show-token -d 'Display the auth token SEE ALSO'

