# gh-auth-setup-git
# Autogenerated from man page /usr/share/man/man1/gh-auth-setup-git.1.gz
complete -c gh-auth-setup-git -s h -l hostname -d 'The hostname to configure git for EXAMPLE # Configure git to use GitHub CLI a…'

