# gh-alias-import
# Autogenerated from man page /usr/share/man/man1/gh-alias-import.1.gz
complete -c gh-alias-import -l clobber -d 'Overwrite existing aliases of the same name EXAMPLE # Import aliases from a f…'

