# gh-codespace-ports
# Autogenerated from man page /usr/share/man/man1/gh-codespace-ports.1.gz
complete -c gh-codespace-ports -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-ports -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-codespace-ports -l json -d 'Output JSON with the specified fields'
complete -c gh-codespace-ports -s R -l repo -d 'Filter codespace selection by repository name (user/repo)'
complete -c gh-codespace-ports -l repo-owner -d 'Filter codespace selection by repository owner (username or org)'
complete -c gh-codespace-ports -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" SEE ALSO'

