# gh-config-set
# Autogenerated from man page /usr/share/man/man1/gh-config-set.1.gz
complete -c gh-config-set -s h -l host -d 'Set per-host setting EXAMPLE $ gh config set editor vim $ gh config set edito…'

