# gh-codespace-ports-forward
# Autogenerated from man page /usr/share/man/man1/gh-codespace-ports-forward.1.gz
complete -c gh-codespace-ports-forward -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-ports-forward -s R -l repo -d 'Filter codespace selection by repository name (user/repo)'
complete -c gh-codespace-ports-forward -l repo-owner -d 'Filter codespace selection by repository owner (username or org) SEE ALSO'

