# gh-codespace-code
# Autogenerated from man page /usr/share/man/man1/gh-codespace-code.1.gz
complete -c gh-codespace-code -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-code -l insiders -d 'Use the insiders version of Visual Studio Code'
complete -c gh-codespace-code -s R -l repo -d 'Filter codespace selection by repository name (user/repo)'
complete -c gh-codespace-code -l repo-owner -d 'Filter codespace selection by repository owner (username or org)'
complete -c gh-codespace-code -s w -l web -d 'Use the web version of Visual Studio Code SEE ALSO'

