# gh-codespace-ssh
# Autogenerated from man page /usr/share/man/man1/gh-codespace-ssh.1.gz
complete -c gh-codespace-ssh -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-ssh -l config -d 'Write OpenSSH configuration to stdout'
complete -c gh-codespace-ssh -s d -l debug -d 'Log debug data to a file'
complete -c gh-codespace-ssh -l debug-file -d 'Path of the file log to'
complete -c gh-codespace-ssh -l profile -d 'Name of the SSH profile to use'
complete -c gh-codespace-ssh -s R -l repo -d 'Filter codespace selection by repository name (user/repo)'
complete -c gh-codespace-ssh -l repo-owner -d 'Filter codespace selection by repository owner (username or org)'
complete -c gh-codespace-ssh -l server-port -d 'SSH server port number (0 => pick unused) EXAMPLE $ gh codespace ssh'

