# gh-codespace-logs
# Autogenerated from man page /usr/share/man/man1/gh-codespace-logs.1.gz
complete -c gh-codespace-logs -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-logs -s f -l follow -d 'Tail and follow the logs'
complete -c gh-codespace-logs -s R -l repo -d 'Filter codespace selection by repository name (user/repo)'
complete -c gh-codespace-logs -l repo-owner -d 'Filter codespace selection by repository owner (username or org) SEE ALSO'

