# gh-codespace-stop
# Autogenerated from man page /usr/share/man/man1/gh-codespace-stop.1.gz
complete -c gh-codespace-stop -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-stop -s o -l org -d 'The login handle of the organization (admin-only)'
complete -c gh-codespace-stop -s R -l repo -d 'Filter codespace selection by repository name (user/repo)'
complete -c gh-codespace-stop -l repo-owner -d 'Filter codespace selection by repository owner (username or org)'
complete -c gh-codespace-stop -s u -l user -d 'The username to stop codespace for (used with --org) SEE ALSO'

