# gh-codespace-edit
# Autogenerated from man page /usr/share/man/man1/gh-codespace-edit.1.gz
complete -c gh-codespace-edit -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-edit -s d -l display-name -d 'Set the display name'
complete -c gh-codespace-edit -s m -l machine -d 'Set hardware specifications for the VM'
complete -c gh-codespace-edit -s R -l repo -d 'Filter codespace selection by repository name (user/repo)'
complete -c gh-codespace-edit -l repo-owner -d 'Filter codespace selection by repository owner (username or org) SEE ALSO'

