# gh-codespace-jupyter
# Autogenerated from man page /usr/share/man/man1/gh-codespace-jupyter.1.gz
complete -c gh-codespace-jupyter -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-jupyter -s R -l repo -d 'Filter codespace selection by repository name (user/repo)'
complete -c gh-codespace-jupyter -l repo-owner -d 'Filter codespace selection by repository owner (username or org) SEE ALSO'

