# gh-config-get
# Autogenerated from man page /usr/share/man/man1/gh-config-get.1.gz
complete -c gh-config-get -s h -l host -d 'Get per-host setting EXAMPLE $ gh config get git_protocol https SEE ALSO'

