# gh-extension-install
# Autogenerated from man page /usr/share/man/man1/gh-extension-install.1.gz
complete -c gh-extension-install -l force -d 'force upgrade extension, or ignore if latest already installed'
complete -c gh-extension-install -l pin -d 'pin extension to a release tag or commit ref EXAMPLE $ gh extension install o…'

