# gh-extension-upgrade
# Autogenerated from man page /usr/share/man/man1/gh-extension-upgrade.1.gz
complete -c gh-extension-upgrade -l all -d 'Upgrade all extensions'
complete -c gh-extension-upgrade -l dry-run -d 'Only display upgrades'
complete -c gh-extension-upgrade -l force -d 'Force upgrade extension SEE ALSO'

