# gh-gist-list
# Autogenerated from man page /usr/share/man/man1/gh-gist-list.1.gz
complete -c gh-gist-list -s L -l limit -d 'Maximum number of gists to fetch'
complete -c gh-gist-list -l public -d 'Show only public gists'
complete -c gh-gist-list -l secret -d 'Show only secret gists SEE ALSO'

