# gh-gist-edit
# Autogenerated from man page /usr/share/man/man1/gh-gist-edit.1.gz
complete -c gh-gist-edit -s a -l add -d 'Add a new file to the gist'
complete -c gh-gist-edit -s d -l desc -d 'New description for the gist'
complete -c gh-gist-edit -s f -l filename -d 'Select a file to edit SEE ALSO'

