# gh-issue-comment
# Autogenerated from man page /usr/share/man/man1/gh-issue-comment.1.gz
complete -c gh-issue-comment -s b -l body -d 'The comment body text'
complete -c gh-issue-comment -s F -l body-file -d 'Read body text from file (use "-" to read from standard input)'
complete -c gh-issue-comment -l edit-last -d 'Edit the last comment of the same author'
complete -c gh-issue-comment -s e -l editor -d 'Skip prompts and open the text editor to write the body in'
complete -c gh-issue-comment -s w -l web -d 'Open the web browser to write the comment OPTIONS INHERITED FROM PARENT COMMA…'
complete -c gh-issue-comment -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh iss…'

