# gh-issue-unlock
# Autogenerated from man page /usr/share/man/man1/gh-issue-unlock.1.gz
complete -c gh-issue-unlock -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

