# gh-issue-delete
# Autogenerated from man page /usr/share/man/man1/gh-issue-delete.1.gz
complete -c gh-issue-delete -l yes -d 'confirm deletion without prompting OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-issue-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

