# gh-issue-lock
# Autogenerated from man page /usr/share/man/man1/gh-issue-lock.1.gz
complete -c gh-issue-lock -s r -l reason -d 'Optional reason for locking conversation (off_topic, resolved, spam, too_heat…'
complete -c gh-issue-lock -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

