# gh-issue-pin
# Autogenerated from man page /usr/share/man/man1/gh-issue-pin.1.gz
complete -c gh-issue-pin -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # Pin an…'

