# gh-label-clone
# Autogenerated from man page /usr/share/man/man1/gh-label-clone.1.gz
complete -c gh-label-clone -s f -l force -d 'Overwrite labels in the destination repository OPTIONS INHERITED FROM PARENT …'
complete -c gh-label-clone -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # clone …'

