# gh-label-edit
# Autogenerated from man page /usr/share/man/man1/gh-label-edit.1.gz
complete -c gh-label-edit -s c -l color -d 'Color of the label'
complete -c gh-label-edit -s d -l description -d 'Description of the label'
complete -c gh-label-edit -s n -l name -d 'New name of the label OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-label-edit -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # update…'

