# gh-org-list
# Autogenerated from man page /usr/share/man/man1/gh-org-list.1.gz
complete -c gh-org-list -s L -l limit -d 'Maximum number of organizations to list EXAMPLE # List the first 30 organizat…'

