# gh-project-edit
# Autogenerated from man page /usr/share/man/man1/gh-project-edit.1.gz
complete -c gh-project-edit -s d -l description -d 'New description of the project'
complete -c gh-project-edit -l format -d 'Output format: {json}'
complete -c gh-project-edit -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-edit -l readme -d 'New readme for the project'
complete -c gh-project-edit -l title -d 'New title for the project'
complete -c gh-project-edit -l visibility -d 'Change project visibility: {PUBLIC|PRIVATE} EXAMPLE # edit the title of monal…'

