# gh-project-item-create
# Autogenerated from man page /usr/share/man/man1/gh-project-item-create.1.gz
complete -c gh-project-item-create -l body -d 'Body for the draft issue'
complete -c gh-project-item-create -l format -d 'Output format: {json}'
complete -c gh-project-item-create -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-item-create -l title -d 'Title for the draft issue EXAMPLE # create a draft issue in the current user\'…'

