# gh-project-create
# Autogenerated from man page /usr/share/man/man1/gh-project-create.1.gz
complete -c gh-project-create -l format -d 'Output format: {json}'
complete -c gh-project-create -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-create -l title -d 'Title for the project EXAMPLE # create a new project owned by login monalisa …'

