# gh-project-list
# Autogenerated from man page /usr/share/man/man1/gh-project-list.1.gz
complete -c gh-project-list -l closed -d 'Include closed projects'
complete -c gh-project-list -l format -d 'Output format: {json}'
complete -c gh-project-list -s L -l limit -d 'Maximum number of projects to fetch'
complete -c gh-project-list -l owner -d 'Login of the owner'
complete -c gh-project-list -s w -l web -d 'Open projects list in the browser EXAMPLE # list the current user\'s projects …'

