# gh-project-item-delete
# Autogenerated from man page /usr/share/man/man1/gh-project-item-delete.1.gz
complete -c gh-project-item-delete -l format -d 'Output format: {json}'
complete -c gh-project-item-delete -l id -d 'ID of the item to delete'
complete -c gh-project-item-delete -l owner -d 'Login of the owner.  Use "@me" for the current user'

