# gh-project-field-create
# Autogenerated from man page /usr/share/man/man1/gh-project-field-create.1.gz
complete -c gh-project-field-create -l data-type -d 'DataType of the new field. : {TEXT|SINGLE_SELECT|DATE|NUMBER}'
complete -c gh-project-field-create -l format -d 'Output format: {json}'
complete -c gh-project-field-create -l name -d 'Name of the new field'
complete -c gh-project-field-create -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-field-create -l single-select-options -d 'Options for SINGLE_SELECT data type EXAMPLE # create a field in the current u…'

