# gh-project-item-list
# Autogenerated from man page /usr/share/man/man1/gh-project-item-list.1.gz
complete -c gh-project-item-list -l format -d 'Output format: {json}'
complete -c gh-project-item-list -s L -l limit -d 'Maximum number of items to fetch'
complete -c gh-project-item-list -l owner -d 'Login of the owner.  Use "@me" for the current user'

