# gh-project-close
# Autogenerated from man page /usr/share/man/man1/gh-project-close.1.gz
complete -c gh-project-close -l format -d 'Output format, must be \'json\''
complete -c gh-project-close -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-close -l undo -d 'Reopen a closed project EXAMPLE # close project "1" owned by monalisa gh proj…'

