# gh-project-view
# Autogenerated from man page /usr/share/man/man1/gh-project-view.1.gz
complete -c gh-project-view -l format -d 'Output format: {json}'
complete -c gh-project-view -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-view -s w -l web -d 'Open a project in the browser EXAMPLE # view the current user\'s project "1" g…'

