# gh-project-item-archive
# Autogenerated from man page /usr/share/man/man1/gh-project-item-archive.1.gz
complete -c gh-project-item-archive -l format -d 'Output format: {json}'
complete -c gh-project-item-archive -l id -d 'ID of the item to archive'
complete -c gh-project-item-archive -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-item-archive -l undo -d 'Unarchive an item EXAMPLE # archive an item in the current user\'s project "1"…'

