# gh-project-item-add
# Autogenerated from man page /usr/share/man/man1/gh-project-item-add.1.gz
complete -c gh-project-item-add -l format -d 'Output format: {json}'
complete -c gh-project-item-add -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-item-add -l url -d 'URL of the issue or pull request to add to the project EXAMPLE # add an item …'

