# gh-release-list
# Autogenerated from man page /usr/share/man/man1/gh-release-list.1.gz
complete -c gh-release-list -l exclude-drafts -d 'Exclude draft releases'
complete -c gh-release-list -l exclude-pre-releases -d 'Exclude pre-releases'
complete -c gh-release-list -s L -l limit -d 'Maximum number of items to fetch OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-release-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

