# gh-run-rerun
# Autogenerated from man page /usr/share/man/man1/gh-run-rerun.1.gz
complete -c gh-run-rerun -s d -l debug -d 'Rerun with debug logging'
complete -c gh-run-rerun -l failed -d 'Rerun only failed jobs, including dependencies'
complete -c gh-run-rerun -s j -l job -d 'Rerun a specific job from a run, including dependencies OPTIONS INHERITED FRO…'
complete -c gh-run-rerun -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

