# gh-repo-set-default
# Autogenerated from man page /usr/share/man/man1/gh-repo-set-default.1.gz
complete -c gh-repo-set-default -s u -l unset -d 'unset the current default repository'
complete -c gh-repo-set-default -s v -l view -d 'view the current default repository EXAMPLE Interactively select a default re…'

