# gh-repo-deploy-key-list
# Autogenerated from man page /usr/share/man/man1/gh-repo-deploy-key-list.1.gz
complete -c gh-repo-deploy-key-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

