# gh-repo-deploy-key
# Autogenerated from man page /usr/share/man/man1/gh-repo-deploy-key.1.gz
complete -c gh-repo-deploy-key -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

