# gh-search-code
# Autogenerated from man page /usr/share/man/man1/gh-search-code.1.gz
complete -c gh-search-code -l extension -d 'Filter on file extension'
complete -c gh-search-code -l filename -d 'Filter on filename'
complete -c gh-search-code -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-search-code -l json -d 'Output JSON with the specified fields'
complete -c gh-search-code -l language -d 'Filter results by language'
complete -c gh-search-code -s L -l limit -d 'Maximum number of code results to fetch'
complete -c gh-search-code -l match -d 'Restrict search to file contents or file path: {file|path}'
complete -c gh-search-code -l owner -d 'Filter on owner'
complete -c gh-search-code -s R -l repo -d 'Filter on repository'
complete -c gh-search-code -l size -d 'Filter on size range, in kilobytes'
complete -c gh-search-code -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-search-code -s w -l web -d 'Open the search query in the web browser EXAMPLE # search code matching "reac…'

