# gh-status
# Autogenerated from man page /usr/share/man/man1/gh-status.1.gz
complete -c gh-status -s e -l exclude -d 'Comma separated list of repos to exclude in owner/name format'
complete -c gh-status -s o -l org -d 'Report status within an organization EXAMPLE $ gh status -e cli/cli -e cli/go…'

