# gh-variable-list
# Autogenerated from man page /usr/share/man/man1/gh-variable-list.1.gz
complete -c gh-variable-list -s e -l env -d 'List variables for an environment'
complete -c gh-variable-list -s o -l org -d 'List variables for an organization OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-variable-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

