# gh-variable-set
# Autogenerated from man page /usr/share/man/man1/gh-variable-set.1.gz
complete -c gh-variable-set -s b -l body -d 'The value for the variable (reads from standard input if not specified)'
complete -c gh-variable-set -s e -l env -d 'Set deployment environment variable'
complete -c gh-variable-set -s f -l env-file -d 'Load variable names and values from a dotenv-formatted file'
complete -c gh-variable-set -s o -l org -d 'Set organization variable'
complete -c gh-variable-set -s r -l repos -d 'List of repositories that can access an organization variable'
complete -c gh-variable-set -s v -l visibility -d 'Set visibility for an organization variable: {all|private|selected} OPTIONS I…'
complete -c gh-variable-set -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # Add va…'

