# gh-variable-delete
# Autogenerated from man page /usr/share/man/man1/gh-variable-delete.1.gz
complete -c gh-variable-delete -s e -l env -d 'Delete a variable for an environment'
complete -c gh-variable-delete -s o -l org -d 'Delete a variable for an organization OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-variable-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

