# gh-workflow-enable
# Autogenerated from man page /usr/share/man/man1/gh-workflow-enable.1.gz
complete -c gh-workflow-enable -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

