# gh-workflow-list
# Autogenerated from man page /usr/share/man/man1/gh-workflow-list.1.gz
complete -c gh-workflow-list -s a -l all -d 'Also show disabled workflows'
complete -c gh-workflow-list -s L -l limit -d 'Maximum number of workflows to fetch OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-workflow-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

