# gids-tool
# Autogenerated from man page /usr/share/man/man1/gids-tool.1.gz
complete -c gids-tool -s X -l initialize -d 'Initialize token'
complete -c gids-tool -l admin-key -d 'Define the administrator key'
complete -c gids-tool -l pin -d 'This option can be used to specify the PIN value on the command line'
complete -c gids-tool -l serial-number -d 'Define serial number'
complete -c gids-tool -s U -l unblock -d 'Unblock the user PIN after an administrator authentication'
complete -c gids-tool -s C -l change-admin-key -d 'Change the administrator key'
complete -c gids-tool -l new-admin-key -d 'Define the new administrator key'
complete -c gids-tool -l reader -s r -d 'Number of the reader to use'
complete -c gids-tool -s w -l wait -d 'Wait for a card to be inserted'
complete -c gids-tool -s v -l verbose -d 'Verbose operation.  Use several times to enable debug output'

