# glocktop
# Autogenerated from man page /usr/share/man/man8/glocktop.8.gz
complete -c glocktop -s d -d 'Specify a time delay (in seconds) between reports.  (Default is 30 seconds)'
complete -c glocktop -s h -d 'Print help information'
complete -c glocktop -s i -d 'Interactive mode.  In this mode, glocktop acts more like the top command'
complete -c glocktop -s D -d 'Omit DLM status'
complete -c glocktop -s n -d 'End the program after the specified number of iterations (reports)'
complete -c glocktop -s r -d 'Show resource group reservation information'
complete -c glocktop -s s -d 'Print glock summary information every <freq> reports'
complete -c glocktop -s t -d 'Trace directory path'
complete -c glocktop -s H -d 'Don\'t show Held glocks, unless there are also waiters for the lock'

