# glusterd
# Autogenerated from man page /usr/share/man/man8/glusterd.8.gz
complete -c glusterd -s l -l log-file -d 'File to use for logging'
complete -c glusterd -s L -l log-level -d 'Logging severity'
complete -c glusterd -l localtime-logging -d 'Enable localtime log timestamps'
complete -c glusterd -l debug -d 'Run the program in debug mode'
complete -c glusterd -s N -l no-daemon -d 'Run the program in the foreground. SS "Miscellaneous Options:"'
complete -c glusterd -s '?' -l help -d 'Display this help'
complete -c glusterd -l usage -d 'Display a short usage message'
complete -c glusterd -s V -l version -d 'Print the program version.  FILES /var/lib/glusterd/*'

