# gnome-photos
# Autogenerated from man page /usr/share/man/man1/gnome-photos.1.gz
complete -c gnome-photos -l help -s h -d 'Show a brief overview of all the options'
complete -c gnome-photos -l help-all -d 'Show all the options in detail'
complete -c gnome-photos -l help-gapplication -d 'Show all the GApplication options'
complete -c gnome-photos -l help-gtk -d 'Show all the GTK options'
complete -c gnome-photos -l empty-results -d 'Show the empty state'
complete -c gnome-photos -l version -d 'Show the application\\*(Aqs version'
complete -c gnome-photos -l gapplication-service -d 'Enter GApplication service mode.  To be used from D-Bus service files'
complete -c gnome-photos -l class -d 'Program class as used by the window manager'
complete -c gnome-photos -l display -d 'X display to use'
complete -c gnome-photos -l g-fatal-warnings -d 'Make all warnings fatal'
complete -c gnome-photos -l gdk-debug -d 'GDK debugging flags to set'
complete -c gnome-photos -l gdk-no-debug -d 'GDK debugging flags to unset'
complete -c gnome-photos -l gtk-debug -d 'GTK debugging flags to set'
complete -c gnome-photos -l gtk-no-debug -d 'GTK debugging flags to unset'
complete -c gnome-photos -l gtk-module -d 'Load additional GTK modules'
complete -c gnome-photos -l name -d 'Program name as used by the window manager'

