# gnome-contacts
# Autogenerated from man page /usr/share/man/man1/gnome-contacts.1.gz
complete -c gnome-contacts -s '?' -l help -d 'Prints a short help text and exits'
complete -c gnome-contacts -s e -l email -d 'Show contact with this email address'
complete -c gnome-contacts -s i -l individual -d 'Show contact with this individual id'
complete -c gnome-contacts -s v -l version -d 'Show the current version of Contacts'

