# gnroff
# Autogenerated from man page /usr/share/man/man1/gnroff.1.gz
complete -c gnroff -s T -d 'option are ascii , latin1 , utf8 , and cp1047 ; any others are ignored'
complete -c gnroff -o Tascii -d 'is implied.  Whitespace is not permitted between an option and its argument'
complete -c gnroff -s h -d and
complete -c gnroff -s c -d 'options are equivalent to grotty \'s options'
complete -c gnroff -s d
complete -c gnroff -s C
complete -c gnroff -s i
complete -c gnroff -s M
complete -c gnroff -s m
complete -c gnroff -s n
complete -c gnroff -s o
complete -c gnroff -s r
complete -c gnroff -s w -d and
complete -c gnroff -s W -d 'options have the effect described in troff (1)'
complete -c gnroff -s e
complete -c gnroff -s q -d and
complete -c gnroff -s s -d '(which are not implemented in troff )'
complete -c gnroff -s p -d '(pic),'
complete -c gnroff -s t -d '(tbl),'
complete -c gnroff -s S -d '(safer), and'
complete -c gnroff -s U -d '(unsafe) are passed to groff '
complete -c gnroff -s v -d and
complete -c gnroff -l version -d 'show version information, while'
complete -c gnroff -l help -d 'displays a usage message; all exit afterward'

