# goid-tool
# Autogenerated from man page /usr/share/man/man1/goid-tool.1.gz
complete -c goid-tool -l help -s h -d 'Print help message on screen'
complete -c goid-tool -l version -s V -d 'Print the OpenSC package release version'
complete -c goid-tool -l reader -s r -d 'Specify the number of the reader to use'
complete -c goid-tool -l verbose -s v -d 'Cause goid-tool to be more verbose'
complete -c goid-tool -l verify-pin -s p -d 'Verify PIN'
complete -c goid-tool -l verify-bio -s b -d 'Verify finger print'
complete -c goid-tool -l verify-pin-or-bio -d 'Verify PIN or finger print (user\\*(Aqs choice)'

