# grilo-test-ui-0.3
# Autogenerated from man page /usr/share/man/man1/grilo-test-ui-0.3.1.gz
complete -c 'grilo-test-ui-0.3' -s h -l help -d 'Show summary of grilo-test-ui options'
complete -c 'grilo-test-ui-0.3' -l help-grl -d 'Show summary of Grilo options'
complete -c 'grilo-test-ui-0.3' -l help-all -d 'Show summary of all options'

