# grl-launch-0.3
# Autogenerated from man page /usr/share/man/man1/grl-launch-0.3.1.gz
complete -c 'grl-launch-0.3' -s h -l help -d 'Show summary of grl-launch options'
complete -c 'grl-launch-0.3' -l help-grl -d 'Show summary of Grilo options'
complete -c 'grl-launch-0.3' -l help-all -d 'Show summary of all options'
complete -c 'grl-launch-0.3' -s C -l config -d 'Configuration file to send to sources'
complete -c 'grl-launch-0.3' -s c -l count -d 'Number of elements to return'
complete -c 'grl-launch-0.3' -s d -l delay -d 'Wait some seconds before performing the operation (default 1 second)'
complete -c 'grl-launch-0.3' -s f -l flags -d 'List of comma-separated flags to use'
complete -c 'grl-launch-0.3' -s F -l full -d 'Full serialize'
complete -c 'grl-launch-0.3' -s k -l keys -d 'List of comma-separated keys to retrieve'
complete -c 'grl-launch-0.3' -s S -l serialize -d Serialize
complete -c 'grl-launch-0.3' -s s -l skip -d 'Number of elements to skip'
complete -c 'grl-launch-0.3' -s T -l titles -d 'Print column titles (useful for CSV spreadsheets)'
complete -c 'grl-launch-0.3' -s V -l version -d 'Print version EXAMPLES Print the ID for all the items searched in the Tracker…'

