# grl-inspect-0.3
# Autogenerated from man page /usr/share/man/man1/grl-inspect-0.3.1.gz
complete -c 'grl-inspect-0.3' -s h -l help -d 'Show summary of grl-inspect options'
complete -c 'grl-inspect-0.3' -l help-grl -d 'Show summary of Grilo options'
complete -c 'grl-inspect-0.3' -l help-all -d 'Show summary of all options'
complete -c 'grl-inspect-0.3' -s k -d 'Show information about metadata keys'
complete -c 'grl-inspect-0.3' -s d -l delay -d 'Wait for some seconds before showing results'
complete -c 'grl-inspect-0.3' -s c -l config -d 'Configuration file to use with the plugins'

