# grub2-glue-efi
# Autogenerated from man page /usr/share/man/man1/grub2-glue-efi.1.gz
complete -c grub2-glue-efi -s 3 -l input32 -d 'set input filename for 32-bit part'
complete -c grub2-glue-efi -s 6 -l input64 -d 'set input filename for 64-bit part'
complete -c grub2-glue-efi -s o -l output -d 'set output filename.  Default is STDOUT'
complete -c grub2-glue-efi -s v -l verbose -d 'print verbose messages'
complete -c grub2-glue-efi -s '?' -l help -d 'give this help list'
complete -c grub2-glue-efi -l usage -d 'give a short usage message'
complete -c grub2-glue-efi -s V -l version -d 'print program version'

