# gsoelim
# Autogenerated from man page /usr/share/man/man1/gsoelim.1.gz
complete -c gsoelim -s C -d 'Recognize  . so even when followed by a character other than space or newline'
complete -c gsoelim -s I -d 'This option may be used to add a directory to the search path for files (both…'
complete -c gsoelim -s r -d 'Do not add  . lf requests (for general use, with non-groff files)'
complete -c gsoelim -s t -d 'Don\'t emit  '
complete -c gsoelim -s s -d 'option of groff '
complete -c gsoelim -s v -d 'Print the version number'

