# gsound-play
# Autogenerated from man page /usr/share/man/man1/gsound-play.1.gz
complete -c gsound-play -s h -l help -d 'Show help options'
complete -c gsound-play -s i -l id -d 'Event sound identifier'
complete -c gsound-play -s f -l file -d 'Play file'
complete -c gsound-play -s d -l description -d 'Event sound description'
complete -c gsound-play -s c -l cache-control -d 'Cache control (permanent, volatile, never)'
complete -c gsound-play -s l -l loop -d 'Loop many times (default: 1)'
complete -c gsound-play -s v -l volume -d 'A floating point dB value for the sample volume (ex: 0. 0)'
complete -c gsound-play -s b -l backend -d 'libcanberra backend to use'

