# gtsdelaunay
# Autogenerated from man page /usr/share/man/man1/gtsdelaunay.1.gz
complete -c gtsdelaunay -s b -l hull -d 'Do not keep convex hull'
complete -c gtsdelaunay -s e -l noconst -d 'Do not add constrained edges'
complete -c gtsdelaunay -s S -l split -d 'Split constraints (experimental)'
complete -c gtsdelaunay -s H -l holes -d 'Remove holes from the triangulation'
complete -c gtsdelaunay -s d -l duplicates -d 'Remove duplicate vertices'
complete -c gtsdelaunay -s r -l randomize -d 'Shuffle input vertex list'
complete -c gtsdelaunay -s c -l check -d 'Check Delaunay property'
complete -c gtsdelaunay -s f -l files -d 'Generate evolution files'
complete -c gtsdelaunay -s o -l conform -d 'Generate conforming triangulation'
complete -c gtsdelaunay -s s -l steiner -d 'Maximum number of Steiner points for conforming triangulation (default is no …'
complete -c gtsdelaunay -s q -l quality -d 'Set the minimum acceptable face quality'
complete -c gtsdelaunay -s a -l area -d 'Set the maximum acceptable face area'
complete -c gtsdelaunay -s v -l verbose -d 'Print statistics about the triangulation'
complete -c gtsdelaunay -s h -l help -d 'Display the help and exit'

