# gtstransform
# Autogenerated from man page /usr/share/man/man1/gtstransform.1.gz
complete -c gtstransform -s r -l rx -d 'Rotate around x-axis . RI ( ANGLE in degrees)'
complete -c gtstransform -s m -l ry -d 'Rotate around y-axis'
complete -c gtstransform -l rz -d 'Rotate around z-axis'
complete -c gtstransform -s s -l scale -d 'Scale by R FACTOR '
complete -c gtstransform -s R -l sx -d 'Scale x-axis by R FACTOR '
complete -c gtstransform -s M -l sy -d 'Scale y-axis by R FACTOR '
complete -c gtstransform -s N -l sz -d 'Scale z-axis by R FACTOR '
complete -c gtstransform -s t -l tx -d 'Translate of  V along x-axis'
complete -c gtstransform -s u -l ty -d 'Translate of  V along y-axis'
complete -c gtstransform -s w -l tz -d 'Translate of  V along z-axis'
complete -c gtstransform -s i -l revert -d 'Turn surface inside out'
complete -c gtstransform -s o -l normalize -d 'Fit the resulting surface in a cube of size 1 centered at the origin'
complete -c gtstransform -s v -l verbose -d 'Print statistics about the surface'
complete -c gtstransform -s h -l help -d 'Display the help and exit'

