# HEAD
# Autogenerated from man page /usr/share/man/man1/HEAD.1.gz
complete -c HEAD -s m
complete -c HEAD -s f
complete -c HEAD -s b
complete -c HEAD -s t
complete -c HEAD -s i
complete -c HEAD -s c
complete -c HEAD -s p
complete -c HEAD -s P
complete -c HEAD -s H
complete -c HEAD -s C
complete -c HEAD -s u
complete -c HEAD -s U
complete -c HEAD -s s
complete -c HEAD -s S
complete -c HEAD -s e
complete -c HEAD -s E
complete -c HEAD -s d
complete -c HEAD -s o
complete -c HEAD -s v
complete -c HEAD -s h
complete -c HEAD -s a

