# hspell
# Autogenerated from man page /usr/share/man/man1/hspell.1.gz
complete -c hspell -s v -d 'If the  -v option is given,  hspell prints emacs-oriented version information…'
complete -c hspell -o vv -d 'Repetition of the  -v option causes  hspell to also show some information on …'
complete -c hspell -s V -d 'With the  -V option,  hspell prints true and human-oriented version informati…'
complete -c hspell -s c -d 'If the  -c option is given,  hspell will suggest corrections for misspelled w…'
complete -c hspell -s n -d 'The  -n option will give some longer "notes" about certain spelling errors, e…'
complete -c hspell -s l -d 'The  -l (linguistic information) option will explain for each  correct word w…'
complete -c hspell -s s -d 'Normally, the words deemed spelling mistakes are shown in alphabetical order'
complete -c hspell -s a -d 'With the  -a option,  hspell tries to emulate (as little as possible of)  isp…'
complete -c hspell -s i -d 'This option only has any effect when used together with the  -a option'
complete -c hspell -s H -d 'By default, Hspell does not allow the He Ha-sh\'ela prefix'
complete -c hspell -s D -d 'Load the word lists from the given base pathname, rather than from the compil…'
complete -c hspell -o cn -d 'for maximal correction help from hspell '
complete -c hspell -s d -s B -s m -s T -s C -s S -s P -s p -s w -s W -d 'These options are passed to hspell by lyx or other applications, thinking the…'

