# htcacheclean
# Autogenerated from man page /usr/share/man/man8/htcacheclean.8.gz
complete -c htcacheclean -o dinterval -d 'Daemonize and repeat cache cleaning every interval minutes'
complete -c htcacheclean -s D -d 'Do a dry run and don\'t delete anything'
complete -c htcacheclean -s v -d 'Be verbose and print statistics'
complete -c htcacheclean -s r -d 'Clean thoroughly'
complete -c htcacheclean -s n -d 'Be nice.  This causes slower processing in favour of other processes'
complete -c htcacheclean -s t -d 'Delete all empty directories'
complete -c htcacheclean -o ppath -d 'Specify path as the root directory of the disk cache'
complete -c htcacheclean -o Ppidfile -d 'Specify pidfile as the name of the file to write the process ID to when daemo…'
complete -c htcacheclean -o Rround -d 'Specify round as the amount to round sizes up to, to compensate for disk bloc…'
complete -c htcacheclean -o llimit -d 'Specify limit as the total disk cache size limit'
complete -c htcacheclean -o Llimit -d 'Specify limit as the total disk cache inode limit'
complete -c htcacheclean -s i -d 'Be intelligent and run only when there was a modification of the disk cache'
complete -c htcacheclean -s a -d 'List the URLs currently stored in the cache'

