# htdbm
# Autogenerated from man page /usr/share/man/man1/htdbm.1.gz
complete -c htdbm -s b -d 'Use batch mode; i. e'
complete -c htdbm -s i -d 'Read the password from stdin without verification (for script usage)'
complete -c htdbm -s c -d 'Create the passwdfile'
complete -c htdbm -s n -d 'Display the results on standard output rather than updating a database'
complete -c htdbm -s m -d 'Use MD5 encryption for passwords'
complete -c htdbm -s B -d 'Use bcrypt encryption for passwords'
complete -c htdbm -s C -d 'This flag is only allowed in combination with -B (bcrypt encryption)'
complete -c htdbm -s d -d 'Use crypt() encryption for passwords'
complete -c htdbm -s s -d 'Use SHA encryption for passwords'
complete -c htdbm -s p -d 'Use plaintext passwords'
complete -c htdbm -s l -d 'Print each of the usernames and comments from the database on stdout'
complete -c htdbm -s v -d 'Verify the username and password'
complete -c htdbm -s x -d 'Delete user'
complete -c htdbm -s t -d 'Interpret the final parameter as a comment'

