# htpasswd
# Autogenerated from man page /usr/share/man/man1/htpasswd.1.gz
complete -c htpasswd -s b -d 'Use batch mode; i. e'
complete -c htpasswd -s i -d 'Read the password from stdin without verification (for script usage)'
complete -c htpasswd -s c -d 'Create the passwdfile'
complete -c htpasswd -s n -d 'Display the results on standard output rather than updating a file'
complete -c htpasswd -s m -d 'Use MD5 encryption for passwords.  This is the default (since version 2. 2'
complete -c htpasswd -s 2 -d 'Use SHA-256 crypt() based hashes for passwords'
complete -c htpasswd -s 5 -d 'Use SHA-512 crypt() based hashes for passwords'
complete -c htpasswd -s B -d 'Use bcrypt encryption for passwords'
complete -c htpasswd -s C -d 'This flag is only allowed in combination with -B (bcrypt encryption)'
complete -c htpasswd -s r -d 'This flag is only allowed in combination with -2 or -5'
complete -c htpasswd -s d -d 'Use crypt() encryption for passwords'
complete -c htpasswd -s s -d 'Use SHA-1 (160-bit) encryption for passwords'
complete -c htpasswd -s p -d 'Use plaintext passwords'
complete -c htpasswd -s D -d 'Delete user'
complete -c htpasswd -s v -d 'Verify password'

