# httpcfg
# Autogenerated from man page /usr/share/man/man1/httpcfg.1.gz
complete -c httpcfg -o add -d 'Adds a new certificate/private key combination for being used at a given port…'
complete -c httpcfg -o del -o delete -d 'Deletes the certificates associated for the port specified (must be specified…'
complete -c httpcfg -o list -d 'List all known certificates'
complete -c httpcfg -o port -d 'Specifies the port to add certificates to, or remove certificates from'
complete -c httpcfg -o pvk -d 'Specifies the Private Key file'
complete -c httpcfg -o cert -d 'Specifies the certificate file to use.  EXAMPLES'

