# httxt2dbm
# Autogenerated from man page /usr/share/man/man1/httxt2dbm.1.gz
complete -c httxt2dbm -s v -d 'More verbose output'
complete -c httxt2dbm -s f -d 'Specify the DBM type to be used for the output'
complete -c httxt2dbm -s i -d 'Input file from which the dbm is to be created'

