# iasecc-tool
# Autogenerated from man page /usr/share/man/man1/iasecc-tool.1.gz
complete -c iasecc-tool -l reader -d 'Number of the reader to use'
complete -c iasecc-tool -l list-applications -d 'Get list of the on-card applications'
complete -c iasecc-tool -l aid -d 'Select hex-aid before processing'
complete -c iasecc-tool -l list-sdos -d 'List SDOs of the given sdo-type, present in default or selected application'
complete -c iasecc-tool -l verbose -s v -d 'Causes cardos-tool to be more verbose'
complete -c iasecc-tool -l wait -s w -d 'Causes iasecc-tool to wait for the token to be inserted into reader'

