# ilasm
# Autogenerated from man page /usr/share/man/man1/ilasm.1.gz
complete -c ilasm -l about -d 'Display information about ilasm'
complete -c ilasm -l version -d 'Display ilasm version SEE ALSO mono(1), mcs(1) COPYRIGHT Copyright (C) 2004, …'

