# illinkanalyzer
# Autogenerated from man page /usr/share/man/man1/illinkanalyzer.1.gz
complete -c illinkanalyzer -l - -l ---------------------
complete -c illinkanalyzer -l ---------------
complete -c illinkanalyzer -l ---------------------- -d 'Dependency #1 	TypeDef:XA. App. MainActivity 	| Assembly:XA. App, Version=1'

