# innochecksum
# Autogenerated from man page /usr/share/man/man1/innochecksum.1.gz
complete -c innochecksum -s '?' -l help
complete -c innochecksum -s c -l count
complete -c innochecksum -s d -l debug
complete -c innochecksum -s e -l end-page
complete -c innochecksum -s i -l per-page-details
complete -c innochecksum -s I -l info
complete -c innochecksum -s l -l leaf
complete -c innochecksum -s m -l merge
complete -c innochecksum -s p -l page-num
complete -c innochecksum -s s -l start-page
complete -c innochecksum -s u -l skip-corrupt
complete -c innochecksum -s v -l verbose
complete -c innochecksum -s V -l version

