# ipsec_newhostkey
# Autogenerated from man page /usr/share/man/man8/ipsec_newhostkey.8.gz
complete -c ipsec_newhostkey -l quiet
complete -c ipsec_newhostkey -l nssdir
complete -c ipsec_newhostkey -l password
complete -c ipsec_newhostkey -l bits
complete -c ipsec_newhostkey -l curve
complete -c ipsec_newhostkey -l keytype
complete -c ipsec_newhostkey -l seeddev

