# ipsec_addconn
# Autogenerated from man page /usr/share/man/man8/ipsec_addconn.8.gz
complete -c ipsec_addconn -l addall -d 'is used, all connections defined in the config file will be operated on'
complete -c ipsec_addconn -l configsetup -d 'is specified, the configuration file is parsed for the config setup section a…'
complete -c ipsec_addconn -l noexport -d 'is specified'
complete -c ipsec_addconn -l checkconfig -d 'is specified, the configuration file is parsed and all sections are checked f…'
complete -c ipsec_addconn -l listroute -d or
complete -c ipsec_addconn -l liststart -d 'is specified, no connections are added or replaced, only shown'

