# ipsec_showhostkey
# Autogenerated from man page /usr/share/man/man8/ipsec_showhostkey.8.gz
complete -c ipsec_showhostkey -l version
complete -c ipsec_showhostkey -l verbose
complete -c ipsec_showhostkey -l nssdir
complete -c ipsec_showhostkey -l password
complete -c ipsec_showhostkey -l list
complete -c ipsec_showhostkey -l dump
complete -c ipsec_showhostkey -l ckaid
complete -c ipsec_showhostkey -l rsaid
complete -c ipsec_showhostkey -l pem
complete -c ipsec_showhostkey -l left -l right
complete -c ipsec_showhostkey -l ipseckey
complete -c ipsec_showhostkey -l gateway -d 'gethostname is used, with a .  appended'
complete -c ipsec_showhostkey -l precedence

