# ipsec_rsasigkey
# Autogenerated from man page /usr/share/man/man8/ipsec_rsasigkey.8.gz
complete -c ipsec_rsasigkey -l verbose -d 'option makes rsasigkey give a running commentary on standard error'
complete -c ipsec_rsasigkey -l seeddev -d 'option specifies a source for random bits used to seed the crypto librarys RNG'
complete -c ipsec_rsasigkey -l seedbits -d 'option specifies how many seed bits are pulled from the random device to seed…'
complete -c ipsec_rsasigkey -l nssdir -d 'option specifies the directory to use for the nss database'
complete -c ipsec_rsasigkey -l password -d 'option specifies the nss cryptographic module authentication password if the …'
complete -c ipsec_rsasigkey -l round -d and
complete -c ipsec_rsasigkey -l noopt -d 'options were obsoleted as these were only used with the old non-library crypt…'
complete -c ipsec_rsasigkey -l random -d 'device is only used for seeding the crypto library, not for direct random to …'

