# ipsec_pluto
# Autogenerated from man page /usr/share/man/man8/ipsec_pluto.8.gz
complete -c ipsec_pluto -l interface -d 'option can be used to limit the interfaces considered)'
complete -c ipsec_pluto -l listen -d 'can be used to limit listening on only 1 IP address of a certain interface'
complete -c ipsec_pluto -s a -d 'flag will show the name and status of each network interface'
complete -c ipsec_pluto -l use-netkey -d '(Linux),'
complete -c ipsec_pluto -l use-bsdkame -d '(BSD)'
complete -c ipsec_pluto -l config -d 'is given as argument to pluto.  If both'
complete -c ipsec_pluto -l use-XXX -d and
complete -c ipsec_pluto -l virtual-private -d 'option.  See ipsec. conf(5) for the syntax.  The option'
complete -c ipsec_pluto -l force-keepalive -d 'forces the sending of the keep-alive packets, which are send to prevent the N…'
complete -c ipsec_pluto -l keep-alive -d 'sets the delay (in seconds) of these keep-alive packets'
complete -c ipsec_pluto -l crlcheckinterval -d 'sets the time between checking for CRL expiration and issuing new fetch comma…'
complete -c ipsec_pluto -l crl-strict -d 'is given, the connection will be rejected until a valid CRL has been loaded'
complete -c ipsec_pluto -l nhelpers -d '(n-1) of them, where n is the number of CPUs you have (including hypherthread…'
complete -c ipsec_pluto -s 1 -d 'tells pluto to perform the above calculation'
complete -c ipsec_pluto -l seedbits -d 'option can be used to specify the number of bits that will be pulled from /de…'
complete -c ipsec_pluto -l stderrlog -d 'is used to steer logging to stderr'
complete -c ipsec_pluto -l logfile -d 'can be used to send all logging information to a specific file'
complete -c ipsec_pluto -l ipsecdir
complete -c ipsec_pluto -l nssdir
complete -c ipsec_pluto -l ctlsocket
complete -c ipsec_pluto -l rundir
complete -c ipsec_pluto -l label
complete -c ipsec_pluto -l help
complete -c ipsec_pluto -l version
complete -c ipsec_pluto -l name
complete -c ipsec_pluto -l to -d 'flag describe the left side and those afterwards describe the right side'
complete -c ipsec_pluto -l id
complete -c ipsec_pluto -l host
complete -c ipsec_pluto -l cert
complete -c ipsec_pluto -l ckaid
complete -c ipsec_pluto -l ca
complete -c ipsec_pluto -l groups
complete -c ipsec_pluto -l sendcert
complete -c ipsec_pluto -l sendca
complete -c ipsec_pluto -l certtype
complete -c ipsec_pluto -l ikeport
complete -c ipsec_pluto -l nexthop
complete -c ipsec_pluto -l client
complete -c ipsec_pluto -l clientprotoport
complete -c ipsec_pluto -l srcip
complete -c ipsec_pluto -l xauthserver
complete -c ipsec_pluto -l xauthclient
complete -c ipsec_pluto -l initiate -d 'also requires the client to specify'
complete -c ipsec_pluto -l xauthuser -d and
complete -c ipsec_pluto -l xauthpass
complete -c ipsec_pluto -l modecfgserver
complete -c ipsec_pluto -l modecfgclient
complete -c ipsec_pluto -l modecfgdns
complete -c ipsec_pluto -l modecfgdomains
complete -c ipsec_pluto -l dnskeyondemand
complete -c ipsec_pluto -l updown
complete -c ipsec_pluto -l psk
complete -c ipsec_pluto -l 'rsasig;'
complete -c ipsec_pluto -l rsasig
complete -c ipsec_pluto -l 'psk;'
complete -c ipsec_pluto -l encrypt
complete -c ipsec_pluto -l authenticate
complete -c ipsec_pluto -l compress
complete -c ipsec_pluto -l tunnel
complete -c ipsec_pluto -l ipv4
complete -c ipsec_pluto -l ipv6
complete -c ipsec_pluto -l tunnelipv4
complete -c ipsec_pluto -l tunnelipv6
complete -c ipsec_pluto -l pfs
complete -c ipsec_pluto -l pfsgroup
complete -c ipsec_pluto -l esp
complete -c ipsec_pluto -l aggrmode
complete -c ipsec_pluto -l modecfgpull
complete -c ipsec_pluto -l dpddelay
complete -c ipsec_pluto -l timeout
complete -c ipsec_pluto -l dpdaction
complete -c ipsec_pluto -l forceencaps
complete -c ipsec_pluto -l initiateontraffic
complete -c ipsec_pluto -l pass
complete -c ipsec_pluto -l drop
complete -c ipsec_pluto -l reject
complete -c ipsec_pluto -l failnone
complete -c ipsec_pluto -l failpass
complete -c ipsec_pluto -l faildrop
complete -c ipsec_pluto -l failreject
complete -c ipsec_pluto -l utc
complete -c ipsec_pluto -l listall
complete -c ipsec_pluto -l listpubkeys
complete -c ipsec_pluto -l listcerts
complete -c ipsec_pluto -l checkpubkeys
complete -c ipsec_pluto -l listcacerts
complete -c ipsec_pluto -l listcrls
complete -c ipsec_pluto -l rereadsecrets
complete -c ipsec_pluto -l rereadall
complete -c ipsec_pluto -l rereadcrls -d 'options reread this information from their respective sources, and purge all …'
complete -c ipsec_pluto -l listevents -d 'lists all pending events, and the'
complete -c ipsec_pluto -l ddns -d 'triggers the Dynamic DNS update event that is normally scheduled to run once …'
complete -c ipsec_pluto -l ikelifetime
complete -c ipsec_pluto -l ipseclifetime
complete -c ipsec_pluto -l rekeymargin
complete -c ipsec_pluto -l rekeyfuzz
complete -c ipsec_pluto -l keyingtries
complete -c ipsec_pluto -l dontrekey
complete -c ipsec_pluto -l delete
complete -c ipsec_pluto -l deletestate
complete -c ipsec_pluto -l route
complete -c ipsec_pluto -l unroute
complete -c ipsec_pluto -l asynchronous
complete -c ipsec_pluto -l oppohere -l oppothere -l opposport -l oppodport -l oppoproto
complete -c ipsec_pluto -l rekey-ipsec
complete -c ipsec_pluto -l rekey-ike
complete -c ipsec_pluto -l terminate
complete -c ipsec_pluto -l crash
complete -c ipsec_pluto -l global-redirect
complete -c ipsec_pluto -l global-redirect-to
complete -c ipsec_pluto -l redirect-to
complete -c ipsec_pluto -l keyid
complete -c ipsec_pluto -l addkey
complete -c ipsec_pluto -l pubkeyrsa
complete -c ipsec_pluto -l unlisten
complete -c ipsec_pluto -l ddos-busy
complete -c ipsec_pluto -l ddos-unlimited
complete -c ipsec_pluto -l ddos-auto
complete -c ipsec_pluto -l status -d 'The trafficstatus form will display the xauth username, add_time and the tota…'
complete -c ipsec_pluto -l trafficstatus -d 'The shutdown form is the proper way to shut down pluto'
complete -c ipsec_pluto -l leave-state -d 'option is given, it does not delete any connections, and leaves the kernel st…'
complete -c ipsec_pluto -l shutdown -d Examples
complete -c ipsec_pluto -l ctlbase
complete -c ipsec_pluto -l secretsfile
complete -c ipsec_pluto -l nofork
complete -c ipsec_pluto -l uniqueids
complete -c ipsec_pluto -l force-busy
complete -c ipsec_pluto -l debug
complete -c ipsec_pluto -l no-debug
complete -c ipsec_pluto -l impair
complete -c ipsec_pluto -l no-impair

