# ipsec_letsencrypt
# Autogenerated from man page /usr/share/man/man8/ipsec_letsencrypt.8.gz
complete -c ipsec_letsencrypt -l client -d 'operation is used for initial client setup'
complete -c ipsec_letsencrypt -l server -d 'operation is used for initial server setup'
complete -c ipsec_letsencrypt -l test -d 'operation is used for testing the configuration/connection'
complete -c ipsec_letsencrypt -l generate-certificate -d 'operation is used for generating the certificate for the hostname'
complete -c ipsec_letsencrypt -l renew -d 'operation is used for updating the generated certificate, it keeps the privat…'
complete -c ipsec_letsencrypt -l disable -d 'operation is used for disabling IPsec service'
complete -c ipsec_letsencrypt -l help -d 'operation is used for displaying all the available options.  SEE ALSO'

