# isodebug
# Autogenerated from man page /usr/share/man/man1/isodebug.1.gz
complete -c isodebug -o help -d 'Prints a short summary of the   isodebug options and exists'
complete -c isodebug -o version -d 'Prints the   isodebug version number string and exists'
complete -c isodebug -s i -d 'Filename to read ISO-9660 image from'

