# isql
# Autogenerated from man page /usr/share/man/man1/isql.1.gz
complete -c isql -s b -d 'Run \'isql\' in non-interactive batch mode'
complete -c isql -o dDELIMITER -d 'Delimit columns with the specified delimiter'
complete -c isql -o xHEX -d 'Delimit columns with the character represented in hexadecimal by HEX'
complete -c isql -s w -d 'Format the result as an HTML table'
complete -c isql -s c -d 'Output the names of the columns on the first row'
complete -c isql -o mNUM -d 'Limit the column display width to NUM characters'
complete -c isql -o lLOCALE -d 'Set the character locale to LOCALE'
complete -c isql -s q -d 'Wrap the character fields in double quotes'
complete -c isql -s 3 -d 'Use calls from ODBC version 3'
complete -c isql -s n -d 'Process multiple lines of SQL, terminated with the GO command'
complete -c isql -s e -d 'Use SQLExecDirect instead of Prepare'
complete -c isql -s k -d 'Use SQLDriverConnect'
complete -c isql -s v -d 'Enable verbose mode, fully describing all errors'
complete -c isql -l version -d 'Display the program version'
complete -c isql -o LNUM -d 'Set the maximum number of characters displayed from a character field to NUM'

