# kasumi
# Autogenerated from man page /usr/share/man/man1/kasumi.1.gz
complete -c kasumi -s h -l help -d 'Show summary of options'
complete -c kasumi -s v -l version -d 'Show Kasumi\'s version and copyright information'
complete -c kasumi -s m -l manage -d 'Run Kasumi in Manage mode.  You may abbreviate this option'
complete -c kasumi -s a -l add -d 'Run Kasumi in Add mode'
complete -c kasumi -s e -l exclusive -d 'Run Kasumi in Exclusive mode'
complete -c kasumi -l sound -d 'Set default sound entry (only in Add mode)'
complete -c kasumi -l spelling -d 'Set default spelling entry (only in Add mode)'
complete -c kasumi -l wordclass -d 'Set default word class entry (only in Add mode)'
complete -c kasumi -s i -l import -d 'Import selected text as a spelling'
complete -c kasumi -s I -l ignore -d 'Ignore selected text'

