# kdeinit5
# Autogenerated from man page /usr/share/man/man8/kdeinit5.8.gz
complete -c kdeinit5 -l help -d 'Show help about options'
complete -c kdeinit5 -l no-fork -d 'Do not fork, i. e.  do not exit until all the executed programs ends'
complete -c kdeinit5 -l no-kded -d 'Do not start kded'
complete -c kdeinit5 -l suicide -d 'Terminate when no KDE applications are left running'

