# kdesu
# Autogenerated from man page /usr/share/man/man1/kdesu.1.gz
complete -c kdesu -s c -d 'This specifies the command to run as root'
complete -c kdesu -s d -d 'Show debug information'
complete -c kdesu -s f -d 'This option allow efficient use of KDE su in . desktop files'
complete -c kdesu -s i -d 'Specify icon to use in the password dialog'
complete -c kdesu -s n -d 'Do not keep the password'
complete -c kdesu -s p -d 'Set priority value'
complete -c kdesu -s r -d 'Use realtime scheduling'
complete -c kdesu -s s -d 'Stop the kdesu daemon'
complete -c kdesu -s t -d 'Enable terminal output.  This disables password keeping'
complete -c kdesu -s u -d 'While the most common use for KDE su is to run a command as the superuser, yo…'
complete -c kdesu -l noignorebutton -d 'Do not display an ignore button'
complete -c kdesu -l attach -d 'Makes the dialog transient for an X app specified by winid'

