# kf5-config
# Autogenerated from man page /usr/share/man/man1/kf5-config.1.gz
complete -c kf5-config -l expandvars -d 'Expand ${prefix} and ${exec_prefix} in output'
complete -c kf5-config -l prefix -d 'Compiled in prefix for Frameworks libraries'
complete -c kf5-config -l exec-prefix -d 'Compiled in exec_prefix for Frameworks libraries'
complete -c kf5-config -l libsuffix -d 'Compiled in library path suffix'
complete -c kf5-config -l localprefix -d 'Prefix in $HOME used to write files'
complete -c kf5-config -l version -d 'Version of Qt(TM) and compiled in version string for Frameworks libraries and…'
complete -c kf5-config -l kde-version -d 'Compiled in version string for Frameworks libraries'
complete -c kf5-config -l types -d 'Print a list of all available KDE resource types'
complete -c kf5-config -l path -d 'Search path for the specified type'
complete -c kf5-config -l userpath -d 'User paths for the types: desktop|document'
complete -c kf5-config -l install -d 'Prefix to install resource files to'
complete -c kf5-config -l qt-prefix -d 'Installation prefix for Qt(TM)'
complete -c kf5-config -l qt-binaries -d 'Location of installed Qt(TM) binaries'
complete -c kf5-config -l qt-libraries -d 'Location of installed Qt(TM) libraries'
complete -c kf5-config -l qt-plugins -d 'Location of installed Qt(TM) plugins'

