# kf5kross
# Autogenerated from man page /usr/share/man/man1/kf5kross.1.gz
complete -c kf5kross -o h--help -d 'Show help about options'
complete -c kf5kross -o v--version -d 'Show version information'
complete -c kf5kross -l author -d 'Show author information'
complete -c kf5kross -l license -d 'Show license information'

