# lastcomm
# Autogenerated from man page /usr/share/man/man1/lastcomm.1.gz
complete -c lastcomm -l strict-match -d 'Print only entries that match *all* of the arguments on the command line'
complete -c lastcomm -l print-controls -d 'Print control characters'
complete -c lastcomm -l user -d 'List records for user with  name'
complete -c lastcomm -l command -d 'List records for command  name'
complete -c lastcomm -l tty -d 'List records for tty  name'
complete -c lastcomm -l forwards -d 'Read file forwards instead of backwards'
complete -c lastcomm -s f -l file -d 'Read from the file   filename  instead of  acct'
complete -c lastcomm -l ahz -d 'Use this flag to tell the program what  AHZ should be (in hertz)'
complete -c lastcomm -s p -l show-paging -d 'Print paging statistics'
complete -c lastcomm -l pid -d 'Add pid of the process and pid of the process parent to the output (pid is th…'
complete -c lastcomm -l debug -d 'Print verbose internal information'
complete -c lastcomm -s V -l version -d 'Print the version number of  lastcomm'
complete -c lastcomm -s h -l help -d 'Prints the usage string and default locations of system files to standard out…'

