# lc
# Autogenerated from man page /usr/share/man/man1/lc.1.gz
complete -c lc -l complist -s c -d 'This option is used to specify the input file, the licenses'
complete -c lc -l target -s t -d 'full assembly name with file extension for the target assembly'
complete -c lc -l load -s i -d 'Assembly reference to load before trying to compile a license'
complete -c lc -l verbose -s v -d 'Gives more verbose output about the license compiling process'
complete -c lc -l help -s h -d 'Displays usage instructions'
complete -c lc -l outdir -s o -d 'Target path file the licenses resource'
complete -c lc -l nologo -d 'Do not emit the "Mono License Compiler" logo  on stdout while compilng'

