# libvirtd
# Autogenerated from man page /usr/share/man/man8/libvirtd.8.gz
complete -c libvirtd -s h -l help
complete -c libvirtd -s d -l daemon
complete -c libvirtd -s f -l config
complete -c libvirtd -s l -l listen
complete -c libvirtd -s p -l pid-file
complete -c libvirtd -s t -l timeout
complete -c libvirtd -s v -l verbose
complete -c libvirtd -l version
complete -c libvirtd -o rw-r--r--

