# log2pcap
# Autogenerated from man page /usr/share/man/man1/log2pcap.1.gz
complete -c log2pcap -s h -d 'If this parameter is specified the output file will be a hex dump, in a forma…'
complete -c log2pcap -s q -d 'Be quiet.  No warning messages about missing or incomplete data will be given'
complete -c log2pcap -s '?' -l help -d 'Print a summary of command line options'

