# lp-cups
# Autogenerated from man page /usr/share/man/man1/lp-cups.1.gz
complete -c lp-cups -s E -d 'Forces encryption when connecting to the server'
complete -c lp-cups -s U -d 'Specifies the username to use when connecting to the server'
complete -c lp-cups -s c -d 'This option is provided for backwards-compatibility only'
complete -c lp-cups -s d -d 'Prints files to the named printer'
complete -c lp-cups -s h -d 'Chooses an alternate server.  Note: This option must occur before all others'
complete -c lp-cups -s i -d 'Specifies an existing job to modify'
complete -c lp-cups -s m -d 'Sends an email when the job is completed'
complete -c lp-cups -s n -d 'Sets the number of copies to print'
complete -c lp-cups -s o -d 'Sets one or more job options.  See "COMMON JOB OPTIONS" below'
complete -c lp-cups -s q -d 'Sets the job priority from 1 (lowest) to 100 (highest)'
complete -c lp-cups -s s -d 'Do not report the resulting job IDs (silent mode. )'
complete -c lp-cups -s t -d 'Sets the job name'
complete -c lp-cups -s H -d 'Specifies when the job should be printed'
complete -c lp-cups -s P -d 'Specifies which pages to print in the document'

