# lpq-cups
# Autogenerated from man page /usr/share/man/man1/lpq-cups.1.gz
complete -c lpq-cups -s E -d 'Forces encryption when connecting to the server'
complete -c lpq-cups -s P -d 'Specifies an alternate printer or class name'
complete -c lpq-cups -s U -d 'Specifies an alternate username'
complete -c lpq-cups -s a -d 'Reports jobs on all printers'
complete -c lpq-cups -s h -d 'Specifies an alternate server'
complete -c lpq-cups -s l -d 'Requests a more verbose (long) reporting format'

