# lpr-cups
# Autogenerated from man page /usr/share/man/man1/lpr-cups.1.gz
complete -c lpr-cups -s E -d 'Forces encryption when connecting to the server'
complete -c lpr-cups -s H -d 'Specifies an alternate server'
complete -c lpr-cups -s T -d 'Sets the job name/title'
complete -c lpr-cups -s P -d 'Prints files to the named printer'
complete -c lpr-cups -s U -d 'Specifies an alternate username'
complete -c lpr-cups -s '#' -d 'Sets the number of copies to print'
complete -c lpr-cups -s h -d 'Disables banner printing.  This option is equivalent to -o job-sheets=none'
complete -c lpr-cups -s l -d 'Specifies that the print file is already formatted for the destination and sh…'
complete -c lpr-cups -s m -d 'Send an email on job completion'
complete -c lpr-cups -s o -d 'Sets a job option.  See "COMMON JOB OPTIONS" below'
complete -c lpr-cups -s p -d 'Specifies that the print file should be formatted with a shaded header with t…'
complete -c lpr-cups -s q -d 'Hold job for printing'
complete -c lpr-cups -s r -d 'Specifies that the named print files should be deleted after submitting them'
complete -c lpr-cups -s C
complete -c lpr-cups -s J

