# lprm-cups
# Autogenerated from man page /usr/share/man/man1/lprm-cups.1.gz
complete -c lprm-cups -s E -d 'Forces encryption when connecting to the server'
complete -c lprm-cups -s P -d 'Specifies the destination printer or class'
complete -c lprm-cups -s U -d 'Specifies an alternate username'
complete -c lprm-cups -s h -d 'Specifies an alternate server'

