# lsar
# Autogenerated from man page /usr/share/man/man1/lsar.1.gz
complete -c lsar -s l -o long -d 'Print more information about each file in the archive'
complete -c lsar -s L -o verylong -d 'Print all available information about each file in the archive'
complete -c lsar -s t -o test -d 'Test the integrity of the files in the archive, if possible'
complete -c lsar -s p -o password -d 'The password to use for decrypting protected archives'
complete -c lsar -s e -o encoding -d 'The encoding to use for filenames in the archive, when it is not known'
complete -c lsar -s E -o password-encoding -d 'The encoding to use for the password for the archive, when it is not known'
complete -c lsar -o pe -o print-encoding -d 'Print the auto-detected encoding and the confidence factor after the file list'
complete -c lsar -s i -o indexes -d 'Instead of specifying the files to list as filenames or wildcard patterns, sp…'
complete -c lsar -s j -o json -d 'Print the listing in JSON format'
complete -c lsar -o ja -o json-ascii -d 'Print the listing in JSON format, encoded as pure ASCII text'
complete -c lsar -o nr -o no-recursion -d 'Do not attempt to list the contents of archives contained in other archives'
complete -c lsar -s h -o help -d 'Display help information'
complete -c lsar -s v -o version -d 'Print version and exit.  SEE ALSO unar (1)'

