# lsmdev
# Autogenerated from man page /usr/share/man/man8/lsmdev.8.gz
complete -c lsmdev -l addattr -d 'Add an attribute ATTRIBUTE.  Valid for the modify command'
complete -c lsmdev -s a -l auto -d 'Automatically start the device on parent availability'
complete -c lsmdev -s d -l defined -d 'List all defined devices, even if not active.  Valid for the list command'
complete -c lsmdev -l delattr -d 'Delete an attribute entry.  Valid for the modify command'
complete -c lsmdev -l dumpjson -d 'Dump the configuration for a device in JSON format when filtered to as single…'
complete -c lsmdev -s i -l index -d 'Act on the attribute INDEX.  Valid for the modify command'
complete -c lsmdev -l jsonfile -d 'Read the configuration for a device from a JSON file FILE'
complete -c lsmdev -s m -l manual -d 'Do not start a device automatically on parent availability'
complete -c lsmdev -s p -l parent -d 'Specify or identify the device by its parent device'
complete -c lsmdev -s t -l type -d 'Specify or identify the device by its type'
complete -c lsmdev -s u -l uuid -d 'Specify or identify the device by its UUID'
complete -c lsmdev -l value -d 'Set an attribute to VALUE, in the format accepted by the attribute'
complete -c lsmdev -s v -l verbose -d 'Increase output verbosity, currently only adds attribute output to the list c…'
complete -c lsmdev -s V -l version -d 'Print mdevctl version'
complete -c lsmdev -s s
complete -c lsmdev -s e -d 'Event type of call-out that is invoked'

