# lwp-dump
# Autogenerated from man page /usr/share/man/man1/lwp-dump.1.gz
complete -c lwp-dump -l agent
complete -c lwp-dump -l keep-client-headers
complete -c lwp-dump -l max-length
complete -c lwp-dump -l method
complete -c lwp-dump -l parse-head
complete -c lwp-dump -l request

