# lwp-request
# Autogenerated from man page /usr/share/man/man1/lwp-request.1.gz
complete -c lwp-request -s m
complete -c lwp-request -s f
complete -c lwp-request -s b
complete -c lwp-request -s t
complete -c lwp-request -s i
complete -c lwp-request -s c
complete -c lwp-request -s p
complete -c lwp-request -s P
complete -c lwp-request -s H
complete -c lwp-request -s C
complete -c lwp-request -s u
complete -c lwp-request -s U
complete -c lwp-request -s s
complete -c lwp-request -s S
complete -c lwp-request -s e
complete -c lwp-request -s E
complete -c lwp-request -s d
complete -c lwp-request -s o
complete -c lwp-request -s v
complete -c lwp-request -s h
complete -c lwp-request -s a

