# lzip
# Autogenerated from man page /usr/share/man/man1/lzip.1.gz
complete -c lzip -s h -l help -d 'display this help and exit'
complete -c lzip -s V -l version -d 'output version information and exit'
complete -c lzip -s a -l trailing-error -d 'exit with error status if trailing data'
complete -c lzip -s b -l member-size -d 'set member size limit in bytes'
complete -c lzip -s c -l stdout -d 'write to standard output, keep input files'
complete -c lzip -s d -l decompress -d decompress
complete -c lzip -s f -l force -d 'overwrite existing output files'
complete -c lzip -s F -l recompress -d 'force re-compression of compressed files'
complete -c lzip -s k -l keep -d 'keep (don\'t delete) input files'
complete -c lzip -s l -l list -d 'print (un)compressed file sizes'
complete -c lzip -s m -l match-length -d 'set match length limit in bytes [36]'
complete -c lzip -s o -l output -d 'write to <file>, keep input files'
complete -c lzip -s q -l quiet -d 'suppress all messages'
complete -c lzip -s s -l dictionary-size -d 'set dictionary size limit in bytes [8 MiB]'
complete -c lzip -s S -l volume-size -d 'set volume size limit in bytes'
complete -c lzip -s t -l test -d 'test compressed file integrity'
complete -c lzip -s v -l verbose -d 'be verbose (a 2nd -v gives more)'
complete -c lzip -s 0 -s 9 -d 'set compression level [default 6]'
complete -c lzip -l fast -d 'alias for -0'
complete -c lzip -l best -d 'alias for -9'
complete -c lzip -l loose-trailing -d 'allow trailing data seeming corrupt header'

