# macpack
# Autogenerated from man page /usr/share/man/man1/macpack.1.gz
complete -c macpack -o mode -d 'libraries is setup'
complete -c macpack -s a
complete -c macpack -s m -d or
complete -c macpack -o 'mode:[winforms'
complete -c macpack -s n -d or
complete -c macpack -o appname:NAME
complete -c macpack -s o -d or
complete -c macpack -o output:DIRECTORY
complete -c macpack -s r -d 'or '
complete -c macpack -o resource:RESOURCE

