# make-bcache
# Autogenerated from man page /usr/share/man/man8/make-bcache.8.gz
complete -c make-bcache -s C -d 'Create a cache'
complete -c make-bcache -s B -d 'Create a backing device (kernel functionality not yet implemented)'
complete -c make-bcache -o UUUID -d 'Create a cache device with the specified UUID'
complete -c make-bcache -s U -d 'Create a cache device with the specified UUID'
complete -c make-bcache -s b -d 'Specifies the bucket size'

