# mariadb-conv
# Autogenerated from man page /usr/share/man/man1/mariadb-conv.1.gz
complete -c mariadb-conv -l from
complete -c mariadb-conv -s f
complete -c mariadb-conv -l to
complete -c mariadb-conv -s t
complete -c mariadb-conv -l continue
complete -c mariadb-conv -s c
complete -c mariadb-conv -l delimiter

