# mcelog
# Autogenerated from man page /usr/share/man/man8/mcelog.8.gz
complete -c mcelog -l daemon -d option
complete -c mcelog -l ascii -d option
complete -c mcelog -l is-cpu-supported -d 'option mcelog exits with code 0 if the current CPU is supported, 1 otherwise'
complete -c mcelog -l syslog -d 'option is specified redirect output to system log.  The '
complete -c mcelog -l syslog-error -d 'option causes the normal machine checks to be logged as  LOG_ERR (implies'
complete -c mcelog -l logfile -d 'option is specified append log output to the specified file.  With the'
complete -c mcelog -l no-syslog -d 'option mcelog will never log anything to the syslog'
complete -c mcelog -l cpu -d 'option is specified set the to be decoded CPU to  cputype'
complete -c mcelog -l dmi -d 'option mcelog will look up the DIMMs reported in machine checks in the  SMBIO…'
complete -c mcelog -l ignorenodev -d 'is specified then mcelog will exit silently when the device cannot be opened'
complete -c mcelog -l filter -d 'is specified  mcelog will filter out known broken machine check events (defau…'
complete -c mcelog -l no-filter -d 'option is specified mcelog does not filter events'
complete -c mcelog -l raw -d 'is specified mcelog will not decode, but just dump the mcelog in a raw hex fo…'
complete -c mcelog -l file -d 'option is specified  mcelog --ascii will read the ASCII machine check record …'
complete -c mcelog -l config-file -d 'option mcelog reads the specified config file'
complete -c mcelog -l foreground -d 'will prevent mcelog from giving up the terminal in daemon mode'
complete -c mcelog -l client -d 'option mcelog will query a running daemon for accumulated errors'
complete -c mcelog -l cpumhz -d 'option assume the CPU has  mhz frequency for decoding the time of the event u…'
complete -c mcelog -l pidfile -d 'option writes the process id of the daemon into file  file'
complete -c mcelog -l no-imc-log -d option
complete -c mcelog -l version -d 'displays the version of mcelog and exits'

