# mconfig
# Autogenerated from man page /usr/share/man/man1/mconfig.1.gz
complete -c mconfig -s c -l config -d 'Read the specified config file after reading the other, preconfigured, config…'
complete -c mconfig -s t -l target -d 'Features and default configuration files defined in the mconfig config file(s…'
complete -c mconfig -s '?' -s h -l help -d 'Show a summary usage screen'
complete -c mconfig -s v -l version -d 'Show the mconfig version COMMANDS'

