# mdassembler
# Autogenerated from man page /usr/share/man/man1/mdassembler.1.gz
complete -c mdassembler -l ecma -d 'The documentation found within   DIRS is in the Mono ECMA documentation format'
complete -c mdassembler -l ecmaspec -d 'The documentation found within   DIRS is in the ECMA Specification documentat…'
complete -c mdassembler -l error -d 'The documentation found within  DIRS is in "error" format'
complete -c mdassembler -l help -d 'Show program argument information'
complete -c mdassembler -l man -d 'The documentation found within  DIRS is in man page format'
complete -c mdassembler -s o -l out -d 'Specify the output file prefix.   mdassembler creates the files  PREFIX'
complete -c mdassembler -l simple -d 'The documentation found within  DIRS is in "simple" format'
complete -c mdassembler -l xhtml -l hb -d 'The documentation found within DIRS is in XHTML format'

