# mdoc-assemble
# Autogenerated from man page /usr/share/man/man1/mdoc-assemble.1.gz
complete -c mdoc-assemble -s f -l format -d 'Specifies the documentation format used within PATHS'
complete -c mdoc-assemble -s o -l out -d 'Specify the output file prefix.   mdoc assemble creates the files PREFIX'
complete -c mdoc-assemble -s h -s '?' -l help -d 'Display a help message and exit'

