# mdoc-export-html
# Autogenerated from man page /usr/share/man/man1/mdoc-export-html.1.gz
complete -c mdoc-export-html -l default-template -d 'Writes the default XSLT used to stdout'
complete -c mdoc-export-html -l ext -d 'The file extension to use for created files. Sp This defaults to html'
complete -c mdoc-export-html -l force-update -d 'Always generate new files'
complete -c mdoc-export-html -s o -l out -d 'Write the created files within directory DIRECTORY'
complete -c mdoc-export-html -l template -d 'An XSLT file to use to generate the created files'
complete -c mdoc-export-html -l with-profile -d 'Only process types and members within the . NET profile PROFILE'
complete -c mdoc-export-html -l with-version -d 'Only process types and members within the assembly version VERSION'
complete -c mdoc-export-html -s h -s '?' -l help -d 'Display a help message and exit'

