# mdoc-validate
# Autogenerated from man page /usr/share/man/man1/mdoc-validate.1.gz
complete -c mdoc-validate -l format -d 'The documentation format to validate PATHS against'
complete -c mdoc-validate -s h -s '?' -l help -d 'Display a help message and exit'

