# mdoc-export-msxdoc
# Autogenerated from man page /usr/share/man/man1/mdoc-export-msxdoc.1.gz
complete -c mdoc-export-msxdoc -s o -l out -d 'The XML file to generate'
complete -c mdoc-export-msxdoc -s h -s '?' -l help -d 'Display a help message and exit.  MAILING LISTS'

