# mdoc-update
# Autogenerated from man page /usr/share/man/man1/mdoc-update.1.gz
complete -c mdoc-update -l delete -d 'Allow mdoc update to delete members from documentation files'
complete -c mdoc-update -l exceptions -d EXPERIMENTAL
complete -c mdoc-update -s f -d 'Specify a flag to alter behavior.   Valid flags include: . RS . ne 8'
complete -c mdoc-update -o fno-assembly-versions -d 'Do not generate /Type/AssemblyInfo/AssemblyVersion and /Type/Members/Member/A…'
complete -c mdoc-update -s i -l import -d 'Import documentation found within FILE'
complete -c mdoc-update -s L -l lib -d 'Add DIRECTORY to the assembly search path, so that dependencies of ASSEMBLIES…'
complete -c mdoc-update -s o -l out -d 'Place the generated stubs into DIRECTORY'
complete -c mdoc-update -s r -d 'ASSEMBLY is a dependency for one of ASSEMBLIES which should not be documented…'
complete -c mdoc-update -l since -d 'When updating documentation for an assembly, if a type or member is encounter…'
complete -c mdoc-update -l type -d 'Only update documentation for the type TYPE'
complete -c mdoc-update -s h -s '?' -l help -d 'Display a help message and exit'

