# meinproc5
# Autogenerated from man page /usr/share/man/man1/meinproc5.1.gz
complete -c meinproc5 -o h--help
complete -c meinproc5 -o v--version
complete -c meinproc5 -l cache
complete -c meinproc5 -l check
complete -c meinproc5 -s o -l output
complete -c meinproc5 -l stdout
complete -c meinproc5 -l stylesheet
complete -c meinproc5 -l srcdir
complete -c meinproc5 -l param

