# mii-diag
# Autogenerated from man page /usr/share/man/man8/mii-diag.8.gz
complete -c mii-diag -s A -l advertise -d '-F, --fixed-speed <speed|setting>  Speed is one of: 100baseT4, 100baseTx, 100…'
complete -c mii-diag -s a -l all-interfaces -d 'Show the status of all interfaces'
complete -c mii-diag -s s -l status -d 'Return exit status 2 if there is no link beat'
complete -c mii-diag -s D -d 'Increase the debugging level'
complete -c mii-diag -s g -l read-parameters -d 'Show driver-specific parameters'
complete -c mii-diag -s G -l set-parameters -d 'Set driver-specific parameters.  Set a adapter-specific parameters'
complete -c mii-diag -s v -d 'Increase the verbosity level'
complete -c mii-diag -s V -d 'Show the program version information'
complete -c mii-diag -s w -l watch -d 'Continuously monitor the transceiver and report changes'
complete -c mii-diag -s F -l fixed-speed
complete -c mii-diag -s '?' -d 'Emit usage information'

