# mkfs.hfsplus
# Autogenerated from man page /usr/share/man/man8/mkfs.hfsplus.8.gz
complete -c 'mkfs.hfsplus' -s N -d 'Causes the file system parameters to be printed out without really creating t…'
complete -c 'mkfs.hfsplus' -s U -d 'Set the owner of the file system\'s root directory to uid'
complete -c 'mkfs.hfsplus' -s G -d 'Set the group of the file system\'s root directory to gid'
complete -c 'mkfs.hfsplus' -s M -d 'Specify the octal access permissions mask for the file system\'s root directory'
complete -c 'mkfs.hfsplus' -s P -d 'Set kHFSContentProtectionBit in the volume\'s attributes, which will cause the…'
complete -c 'mkfs.hfsplus' -s s -d 'Creates a case-sensitive HFS Plus filesystem'
complete -c 'mkfs.hfsplus' -s b -d 'The allocation block size of the file system.  The default value is 4096'
complete -c 'mkfs.hfsplus' -s c -d 'This specifies the clump and/or initial sizes, in allocation blocks, for the …'
complete -c 'mkfs.hfsplus' -s i -d 'This specifies the initial catalog node ID for user files and directories'
complete -c 'mkfs.hfsplus' -s J -d 'Creates a journaled HFS+ volume'
complete -c 'mkfs.hfsplus' -s n -d 'This specifies the b-tree node sizes, in bytes, for the various b-tree files'
complete -c 'mkfs.hfsplus' -s v -d 'Volume name (file system name) in ascii or UTF-8 format'

