# mkfs.gfs2
# Autogenerated from man page /usr/share/man/man8/mkfs.gfs2.8.gz
complete -c 'mkfs.gfs2' -s b -d 'Set the filesystem block size to bytes which must be a power of two'
complete -c 'mkfs.gfs2' -s c -d 'Initial size of each journal\'s quota change file.  The default is 1MB'
complete -c 'mkfs.gfs2' -s D -d 'Enable debugging output'
complete -c 'mkfs.gfs2' -s h -d 'Print out a help message describing the available options, then exit'
complete -c 'mkfs.gfs2' -s J -d 'The size of each journal'
complete -c 'mkfs.gfs2' -s j -d 'The number of journals for mkfs. gfs2 to create'
complete -c 'mkfs.gfs2' -s K -d 'Do not attempt to discard the block device contents'
complete -c 'mkfs.gfs2' -s O -d 'Override.  This option prevents mkfs'
complete -c 'mkfs.gfs2' -s o -d 'Specify extended options.  Multiple options can be separated by commas'
complete -c 'mkfs.gfs2' -s p -d 'Specify the locking protocol to use when no locking protocol is specified at …'
complete -c 'mkfs.gfs2' -s q -d 'Quiet mode.  Do not print anything'
complete -c 'mkfs.gfs2' -s r -d 'mkfs. gfs2 will try to make resource groups approximately this large'
complete -c 'mkfs.gfs2' -s t -d 'The "lock table" pair used to uniquely identify this filesystem in a cluster'
complete -c 'mkfs.gfs2' -s V -d 'Print program version information, then exit'

