# mono-shlib-cop
# Autogenerated from man page /usr/share/man/man1/mono-shlib-cop.1.gz
complete -c mono-shlib-cop -s p -l prefixes -d 'Mono installation prefixes.   This is to find $prefix/etc/mono/config'
complete -c mono-shlib-cop -o devel -d 'packages which provide the  unversioned library'

