# monop
# Autogenerated from man page /usr/share/man/man1/monop.1.gz
complete -c monop -o r:assembly -d 'Specifies the assembly to use for looking up the type'
complete -c monop -s a -d 'Renders all of the types in the specified assembly'
complete -c monop -l search -s s -s k -d 'Searches through all known assemblies for types containing `class\''
complete -c monop -l refs -d 'Prints a list of the referenced assemblies for an assembly'
complete -c monop -l filter-obsolete -s f -d 'Do not show obsolete types and members'
complete -c monop -l declared-only -s d -d 'Only show members declared in the type'
complete -c monop -l private -s p -d 'Show private members'
complete -c monop -l runtime-version -d 'Print runtime version'
complete -c monop -o xa -d 'Sets the lookup path to the Xamarin. Android directory'
complete -c monop -o xi -d 'Sets the lookup path to the Xamarin. iOS directory'

