# mono-api-info
# Autogenerated from man page /usr/share/man/man1/mono-api-info.1.gz
complete -c mono-api-info -l abi -d 'Show the ABI instead of the API, that is, non-static fields (even the non-pub…'

