# monodocs2html
# Autogenerated from man page /usr/share/man/man1/monodocs2html.1.gz
complete -c monodocs2html -o dest:DEST_DIR -d 'Write the HTML files into the directory  DEST_DIR '
complete -c monodocs2html -o dumptemplate -d 'Dump the default page template to standard output so that you can use it as a…'
complete -c monodocs2html -o ext:FILE_EXTENSION -d 'FILE_EXTENSION is the file extension for generated files'
complete -c monodocs2html -s '?' -o help -d 'Show program argument information'
complete -c monodocs2html -o onlytype:TYPE -d 'Only generate HTML for the type  TYPE '
complete -c monodocs2html -o source:SOURCE_DIR -d 'SOURCE_DIR is the base directory containing the Monodoc XML documentation'
complete -c monodocs2html -o template:TEMPLATE -d 'Generate HTML using the page template  TEMPLATE '
complete -c monodocs2html -o template -d option
complete -c monodocs2html -s V -o version -d 'Display version and licensing information'

