# monodocer
# Autogenerated from man page /usr/share/man/man1/monodocer.1.gz
complete -c monodocer -o assembly:ASSEMBLY -d 'ASSEMBLY is a . NET assembly to generate documentation stubs for'
complete -c monodocer -o delete -d 'Allow monodocer to delete members from documentation files'
complete -c monodocer -s '?' -o help -d 'Show program argument information'
complete -c monodocer -o ignoremembers -d 'Do not update members'
complete -c monodocer -o importslashdoc:FILE -d 'FILE is an XML file generated with the   /doc:FILE C# compiler flag (e. g'
complete -c monodocer -o name:NAME -d 'NAME is the name of the project this documentation is for'
complete -c monodocer -o namespace:NAMESPACE -d 'Only update the types within the namespace  NAMESPACE '
complete -c monodocer -o overrides -d 'Include overridden methods in documentation'
complete -c monodocer -o path:OUTPUT_DIR -d 'OUTPUT_DIR is the directory which will contain the new/updated documentation …'
complete -c monodocer -o pretty -d 'Indent the XML files nicely'
complete -c monodocer -o since:SINCE -d 'Create a <since/> element for added types and members with the value   SINCE '
complete -c monodocer -o type:TYPE -d 'Only create/update documentation for the type  TYPE '
complete -c monodocer -o updateto:PATH -d 'When updating documentation, write the updated documentation files into the d…'
complete -c monodocer -o path -d ' This is used by some programs for title information (e. g.  monodocs2html )'
complete -c monodocer -o since -d 'an element will be inserted into the  Docs element for all added types and ty…'
complete -c monodocer -s V -o version -d 'Display version and licensing information'

