# mono-xmltool
# Autogenerated from man page /usr/share/man/man1/mono-xmltool.1.gz
complete -c mono-xmltool -l validate-xxx
complete -c mono-xmltool -l validate-rng
complete -c mono-xmltool -l validate-rnc -d 'Commons. Xml. Relaxng. RncParser as the schema, and Commons. Xml. Relaxng'
complete -c mono-xmltool -l validate-nvdl
complete -c mono-xmltool -l validate-xsd -d 'System. Xml. Schema. XmlSchema as the schema and uses System. Xml'

