# monolinker
# Autogenerated from man page /usr/share/man/man1/monolinker.1.gz
complete -c monolinker -s d -d 'Specify a directory to the linker where to look for assemblies'
complete -c monolinker -s o -d 'Specify the output directory, default is \'output\''
complete -c monolinker -s b -d 'Specify whether to generate debug symbols or not, default is false'
complete -c monolinker -s g -d 'Specify whether to generate a new guid for each linked module or reuse the ex…'
complete -c monolinker -s l -d 'Specify what to do with the region specific assemblies '
complete -c monolinker -s c -d 'Specify the action to apply to the core assemblies'
complete -c monolinker -s p -d 'Specify per assembly which action to apply'
complete -c monolinker -s x -d 'Use an XML descriptor as a source for the linker'
complete -c monolinker -s a -d 'use an assembly as a source for the linker'
complete -c monolinker -s i -d 'use a . info xml file as a source for the linker'
complete -c monolinker -s s -d 'Sp You can ask the linker to execute custom steps by using the -s command'
complete -c monolinker -s m -d 'Specify a parameter for a custom step'

