# mono-service
# Autogenerated from man page /usr/share/man/man1/mono-service.1.gz
complete -c mono-service -o d:DIRECTORY -d 'Use this option to specify the working directory for the service'
complete -c mono-service -o l:LOCKFILE -d 'Specifies the file to use for locking, the default is a filename constructed …'
complete -c mono-service -o m:MESSAGE -d 'Name to show in the syslog'
complete -c mono-service -o n:NAME -d 'Use this to specify the service to be launched (if the program contains more …'
complete -c mono-service -l debug -d 'Use this option to prevent mono-service from redirecting stdin and stdout and…'
complete -c mono-service -l no-daemon -d 'Use this option to prevent mono-service from redirecting stdin and stdout and…'

