# mozroots
# Autogenerated from man page /usr/share/man/man1/mozroots.1.gz
complete -c mozroots -l import -d 'Import the certificates into the trust store'
complete -c mozroots -l sync -d 'Synchronize (add/remove) the trust store with the certificates'
complete -c mozroots -l ask -d 'Always confirm before adding or removing trusted certificates'
complete -c mozroots -l ask-add -d 'Always confirm before adding a new trusted certificate'
complete -c mozroots -l ask-remove -d 'Always confirm before removing an existing trusted certificate'
complete -c mozroots -l url -d 'Specify an alternative URL for downloading the trusted certificates (LXR sour…'
complete -c mozroots -l file -d 'Do not download from LXR but use the specified file'
complete -c mozroots -l pkcs7 -d 'Export the certificates into a PKCS#7 file'
complete -c mozroots -l machine -d 'Import the certificate in the machine trust store'
complete -c mozroots -l quiet -d 'Limit console output to errors and confirmations messages'

