# mprof-report
# Autogenerated from man page /usr/share/man/man1/mprof-report.1.gz
complete -c mprof-report -l help -d 'Displays usage instructions'
complete -c mprof-report -l out -d 'Write the report output to file instead of standard output'
complete -c mprof-report -l traces -d 'Show backtraces in reports when available'
complete -c mprof-report -l maxframes -d 'Limit backtraces to num frames'
complete -c mprof-report -l reports -d 'Generate only the specified reports'
complete -c mprof-report -l method-sort -d 'Sort methods according to mode, which can be one of: . RS'
complete -c mprof-report -l alloc-sort -d 'Sort allocations according to mode, which can be one of: . RS'
complete -c mprof-report -l counters-sort -d 'Sort counters according to mode'
complete -c mprof-report -l track -d 'Track what happens to the specified objects'
complete -c mprof-report -l find -d 'Find and track what happens to objects matching spec, which can have one of t…'
complete -c mprof-report -l thread -d 'Consider only events from the thread with ID tid'
complete -c mprof-report -l time -d 'Consider only events occurring in the specified time span'
complete -c mprof-report -l verbose -d 'Print verbose output'
complete -c mprof-report -l debug -d 'Print extremely detailed debug output.  Most users should not use this option'

