# mvxattr
# Autogenerated from man page /usr/share/man/man1/mvxattr.1.gz
complete -c mvxattr -s s -l from -d 'Source xattr name'
complete -c mvxattr -s d -l to -d 'Destination xattr name'
complete -c mvxattr -s l -l follow-symlinks -d 'Follow symlinks, the default is to ignore them'
complete -c mvxattr -s p -l print -d 'Print files where the xattr got renamed'
complete -c mvxattr -s v -l verbose -d 'Print files as they are checked'
complete -c mvxattr -s f -l force -d 'Force overwriting of destination xattr'

