# my_print_defaults
# Autogenerated from man page /usr/share/man/man1/my_print_defaults.1.gz
complete -c my_print_defaults -l user
complete -c my_print_defaults -l password
complete -c my_print_defaults -l host -d 'The output consists of options, one per line, in the form that they would be …'
complete -c my_print_defaults -l help
complete -c my_print_defaults -s '?'
complete -c my_print_defaults -l defaults-file
complete -c my_print_defaults -s c
complete -c my_print_defaults -l debug
complete -c my_print_defaults -s '#'
complete -c my_print_defaults -l defaults-extra-file
complete -c my_print_defaults -s e
complete -c my_print_defaults -l defaults-group-suffix
complete -c my_print_defaults -s g
complete -c my_print_defaults -l mysqld
complete -c my_print_defaults -l no-defaults
complete -c my_print_defaults -s n
complete -c my_print_defaults -l verbose
complete -c my_print_defaults -s v
complete -c my_print_defaults -l version
complete -c my_print_defaults -s V

