# myisamchk
# Autogenerated from man page /usr/share/man/man1/myisamchk.1.gz
complete -c myisamchk -l help
complete -c myisamchk -s '?'
complete -c myisamchk -l HELP
complete -c myisamchk -s H
complete -c myisamchk -l debug
complete -c myisamchk -s '#'
complete -c myisamchk -l silent
complete -c myisamchk -s s
complete -c myisamchk -l verbose
complete -c myisamchk -s v
complete -c myisamchk -s d -d and
complete -c myisamchk -s e
complete -c myisamchk -o vvv -d 'oc o 2. 3'
complete -c myisamchk -l version
complete -c myisamchk -s V
complete -c myisamchk -l wait
complete -c myisamchk -s w
complete -c myisamchk -l print-defaults
complete -c myisamchk -l no-defaults
complete -c myisamchk -l defaults-file
complete -c myisamchk -l defaults-extra-file
complete -c myisamchk -l var_name -d 'syntax: T{ Variable T}:T{ Default Value T} T{ decode_bits T}:T{ 9 T} T{ ft_ma…'
complete -c myisamchk -l recover
complete -c myisamchk -l extend-check -d 'or when the keys are repaired by inserting keys row by row into the table (li…'
complete -c myisamchk -l safe-recover -d 'oc o 2. 3'
complete -c myisamchk -l sort-recover -d option
complete -c myisamchk -l analyze -d 'option is given.  It acts like the myisam_stats_method system variable'
complete -c myisamchk -l check
complete -c myisamchk -s c
complete -c myisamchk -l check-only-changed
complete -c myisamchk -s C
complete -c myisamchk -l fast
complete -c myisamchk -s F
complete -c myisamchk -l force
complete -c myisamchk -s f
complete -c myisamchk -s r -d 'option.  States will be updated as with '
complete -c myisamchk -l update-state -d 'oc o 2. 3'
complete -c myisamchk -l information
complete -c myisamchk -s i
complete -c myisamchk -l medium-check
complete -c myisamchk -s m
complete -c myisamchk -l read-only
complete -c myisamchk -s T
complete -c myisamchk -s U
complete -c myisamchk -l backup
complete -c myisamchk -s B
complete -c myisamchk -l character-sets-dir
complete -c myisamchk -l correct-checksum
complete -c myisamchk -l create-missing-keys
complete -c myisamchk -l quick -d 'oc o 2. 3'
complete -c myisamchk -l data-file-length
complete -c myisamchk -s D
complete -c myisamchk -l keys-used
complete -c myisamchk -s k
complete -c myisamchk -l max-record-length
complete -c myisamchk -l parallel-recover
complete -c myisamchk -s p
complete -c myisamchk -s n -d 'This is beta-quality code.  Use at your own risk! oc o 2. 3'
complete -c myisamchk -s q
complete -c myisamchk -s o
complete -c myisamchk -l set-collation
complete -c myisamchk -l tmpdir
complete -c myisamchk -s t
complete -c myisamchk -l unpack
complete -c myisamchk -s u
complete -c myisamchk -s a
complete -c myisamchk -l block-search
complete -c myisamchk -s b
complete -c myisamchk -l description
complete -c myisamchk -l set-auto-increment
complete -c myisamchk -s A
complete -c myisamchk -l sort-index
complete -c myisamchk -s S
complete -c myisamchk -l sort-records
complete -c myisamchk -s R
complete -c myisamchk -l stats-method
complete -c myisamchk -o eis -d 'The tbl_name argument can be either the name of a MyISAM table or the name of…'
complete -c myisamchk -o rw-rw----
complete -c myisamchk -l sort_buffer_size -d 'should probably be enough for most cases'
complete -c myisamchk -l 'quick;' -d 'This space must be available on the same file system as the original data fil…'

