# myisampack
# Autogenerated from man page /usr/share/man/man1/myisampack.1.gz
complete -c myisampack -l help
complete -c myisampack -s '?'
complete -c myisampack -l backup
complete -c myisampack -s b
complete -c myisampack -l character-sets-dir
complete -c myisampack -l debug
complete -c myisampack -s '#'
complete -c myisampack -l force
complete -c myisampack -s f
complete -c myisampack -l join
complete -c myisampack -s j
complete -c myisampack -l silent
complete -c myisampack -s s
complete -c myisampack -l test
complete -c myisampack -s t
complete -c myisampack -l tmpdir
complete -c myisampack -s T
complete -c myisampack -l verbose
complete -c myisampack -s v
complete -c myisampack -l version
complete -c myisampack -s V
complete -c myisampack -l wait
complete -c myisampack -s w
complete -c myisampack -o rw-rw-r--
complete -c myisampack -o 128 -d 'to 127.  oc o 2. 3'
complete -c myisampack -l unpack -d 'option to myisamchk'

