# mysqlslap
# Autogenerated from man page /usr/share/man/man1/mysqlslap.1.gz
complete -c mysqlslap -l create -d or
complete -c mysqlslap -l query -d 'enable you to specify a string containing an SQL statement or a file containi…'
complete -c mysqlslap -l delimiter -d 'option to specify a different delimiter, which enables you to specify stateme…'
complete -c mysqlslap -l help
complete -c mysqlslap -s '?'
complete -c mysqlslap -l auto-generate-sql
complete -c mysqlslap -s a
complete -c mysqlslap -l auto-generate-sql-add-autoincrement
complete -c mysqlslap -l auto-generate-sql-execute-number
complete -c mysqlslap -l auto-generate-sql-guid-primary
complete -c mysqlslap -l auto-generate-sql-load-type
complete -c mysqlslap -l auto-generate-sql-secondary-indexes
complete -c mysqlslap -l auto-generate-sql-unique-query-number
complete -c mysqlslap -l auto-generate-sql-unique-write-number
complete -c mysqlslap -l auto-generate-sql-write-number -d 'oc o 2. 3'
complete -c mysqlslap -l commit
complete -c mysqlslap -l compress
complete -c mysqlslap -s C
complete -c mysqlslap -l concurrency
complete -c mysqlslap -s c
complete -c mysqlslap -l create-schema
complete -c mysqlslap -l csv
complete -c mysqlslap -l debug
complete -c mysqlslap -s '#'
complete -c mysqlslap -l debug-check
complete -c mysqlslap -l debug-info
complete -c mysqlslap -s T
complete -c mysqlslap -l default-auth
complete -c mysqlslap -l defaults-extra-file
complete -c mysqlslap -l defaults-file
complete -c mysqlslap -s F
complete -c mysqlslap -l detach
complete -c mysqlslap -l engine
complete -c mysqlslap -s e
complete -c mysqlslap -l host
complete -c mysqlslap -s h
complete -c mysqlslap -l init-command
complete -c mysqlslap -l iterations
complete -c mysqlslap -s i
complete -c mysqlslap -l no-defaults
complete -c mysqlslap -l no-drop
complete -c mysqlslap -l number-char-cols
complete -c mysqlslap -s x
complete -c mysqlslap -l number-int-cols
complete -c mysqlslap -s y
complete -c mysqlslap -l number-of-queries
complete -c mysqlslap -l only-print
complete -c mysqlslap -l password
complete -c mysqlslap -s p
complete -c mysqlslap -l pipe
complete -c mysqlslap -s W
complete -c mysqlslap -l plugin-dir
complete -c mysqlslap -l port
complete -c mysqlslap -s P
complete -c mysqlslap -l post-query
complete -c mysqlslap -l post-system
complete -c mysqlslap -l pre-query
complete -c mysqlslap -l pre-system
complete -c mysqlslap -l print-defaults
complete -c mysqlslap -l protocol
complete -c mysqlslap -s q
complete -c mysqlslap -l shared-memory-base-name
complete -c mysqlslap -l silent
complete -c mysqlslap -s s
complete -c mysqlslap -l socket
complete -c mysqlslap -s S
complete -c mysqlslap -l ssl
complete -c mysqlslap -l skip-ssl -d 'oc o 2. 3'
complete -c mysqlslap -l ssl-ca
complete -c mysqlslap -l ssl-capath
complete -c mysqlslap -l ssl-cert
complete -c mysqlslap -l ssl-cipher
complete -c mysqlslap -l ssl-key
complete -c mysqlslap -l ssl-crl
complete -c mysqlslap -l ssl-crlpath
complete -c mysqlslap -l ssl-verify-server-cert
complete -c mysqlslap -l user
complete -c mysqlslap -s u
complete -c mysqlslap -l verbose
complete -c mysqlslap -s v
complete -c mysqlslap -l version
complete -c mysqlslap -s V

