# mysql_install_db
# Autogenerated from man page /usr/share/man/man1/mysql_install_db.1.gz
complete -c mysql_install_db -l user -d 'option to indicate the user name that mysqld will run as'
complete -c mysql_install_db -l basedir -d or
complete -c mysql_install_db -l datadir -d 'if mysql_install_db does not use the correct locations for the installation d…'
complete -c mysql_install_db -l bootstrap -d and
complete -c mysql_install_db -l skip-grant-tables -d 'options (see Section 2. 3. 2, “Typical configure Options”)'
complete -c mysql_install_db -l disable-grant-options -d 'option,'
complete -c mysql_install_db -l builddir
complete -c mysql_install_db -l cross-bootstrap
complete -c mysql_install_db -l ldata
complete -c mysql_install_db -l defaults-extra-file
complete -c mysql_install_db -l defaults-file
complete -c mysql_install_db -l defaults-group-suffix
complete -c mysql_install_db -l force
complete -c mysql_install_db -l help
complete -c mysql_install_db -l no-defaults
complete -c mysql_install_db -l print-defaults
complete -c mysql_install_db -l rpm
complete -c mysql_install_db -l skip-name-resolve
complete -c mysql_install_db -l srcdir
complete -c mysql_install_db -l verbose
complete -c mysql_install_db -l windows

