# mysqldumpslow
# Autogenerated from man page /usr/share/man/man1/mysqldumpslow.1.gz
complete -c mysqldumpslow -s a -d and
complete -c mysqldumpslow -s n -d 'options can be used to modify value abstracting behavior'
complete -c mysqldumpslow -l help
complete -c mysqldumpslow -l debug
complete -c mysqldumpslow -s d
complete -c mysqldumpslow -s g
complete -c mysqldumpslow -s h
complete -c mysqldumpslow -s i
complete -c mysqldumpslow -s l
complete -c mysqldumpslow -s r
complete -c mysqldumpslow -s s
complete -c mysqldumpslow -s t
complete -c mysqldumpslow -l verbose
complete -c mysqldumpslow -s v

