# mysqlbinlog
# Autogenerated from man page /usr/share/man/man1/mysqlbinlog.1.gz
complete -c mysqlbinlog -l read-from-remote-server -d option
complete -c mysqlbinlog -l host
complete -c mysqlbinlog -l password
complete -c mysqlbinlog -l port
complete -c mysqlbinlog -l protocol
complete -c mysqlbinlog -l socket
complete -c mysqlbinlog -l 'user;'
complete -c mysqlbinlog -l help
complete -c mysqlbinlog -s '?'
complete -c mysqlbinlog -l base64-output
complete -c mysqlbinlog -l verbose -d option
complete -c mysqlbinlog -l skip-base64-output -d '(with the sense of AUTO or NEVER)'
complete -c mysqlbinlog -l binlog-row-event-max-size
complete -c mysqlbinlog -l character-sets-dir
complete -c mysqlbinlog -l database
complete -c mysqlbinlog -s d
complete -c mysqlbinlog -l binlog-do-db -d 'option for mysqld, but can be used to specify only one database.  If'
complete -c mysqlbinlog -l debug
complete -c mysqlbinlog -s '#'
complete -c mysqlbinlog -l debug-check
complete -c mysqlbinlog -l debug-info
complete -c mysqlbinlog -l defaults-extra-file
complete -c mysqlbinlog -l defaults-file
complete -c mysqlbinlog -l default-auth
complete -c mysqlbinlog -l disable-log-bin
complete -c mysqlbinlog -s D
complete -c mysqlbinlog -l to-last-log -d 'option and are sending the output to the same MariaDB server'
complete -c mysqlbinlog -l force-if-open
complete -c mysqlbinlog -l force-read
complete -c mysqlbinlog -s f
complete -c mysqlbinlog -l hexdump
complete -c mysqlbinlog -s H
complete -c mysqlbinlog -s h
complete -c mysqlbinlog -l local-load
complete -c mysqlbinlog -s l
complete -c mysqlbinlog -l no-defaults
complete -c mysqlbinlog -l offset
complete -c mysqlbinlog -s o
complete -c mysqlbinlog -l open-files-limit
complete -c mysqlbinlog -s p
complete -c mysqlbinlog -l plugin-dir
complete -c mysqlbinlog -l print-defaults
complete -c mysqlbinlog -s P
complete -c mysqlbinlog -l raw
complete -c mysqlbinlog -s R
complete -c mysqlbinlog -l user
complete -c mysqlbinlog -l result-file
complete -c mysqlbinlog -s r
complete -c mysqlbinlog -l rewrite-db
complete -c mysqlbinlog -l server-id
complete -c mysqlbinlog -l set-charset
complete -c mysqlbinlog -l short-form
complete -c mysqlbinlog -s s
complete -c mysqlbinlog -s S
complete -c mysqlbinlog -l start-datetime
complete -c mysqlbinlog -l start-position
complete -c mysqlbinlog -s j
complete -c mysqlbinlog -l stop-datetime
complete -c mysqlbinlog -l stop-never
complete -c mysqlbinlog -l stop-never-slave-server-id
complete -c mysqlbinlog -l stop-position
complete -c mysqlbinlog -l table
complete -c mysqlbinlog -s T
complete -c mysqlbinlog -s t
complete -c mysqlbinlog -s u
complete -c mysqlbinlog -s v
complete -c mysqlbinlog -l version
complete -c mysqlbinlog -s V
complete -c mysqlbinlog -l var_name -d 'syntax: oc o 2. 3 open_files_limit'

