# mysqld_safe
# Autogenerated from man page /usr/share/man/man1/mysqld_safe.1.gz
complete -c mysqld_safe -l mysqld -d or
complete -c mysqld_safe -l mysqld-version -d 'option to mysqld_safe.  You can also use'
complete -c mysqld_safe -l ledir -d 'to indicate the directory where mysqld_safe should look for the server'
complete -c mysqld_safe -l log-error -d 'option: [mysqld] log-error=error'
complete -c mysqld_safe -l help
complete -c mysqld_safe -l basedir
complete -c mysqld_safe -l core-file-size
complete -c mysqld_safe -l crash-script
complete -c mysqld_safe -l datadir
complete -c mysqld_safe -l defaults-extra-file
complete -c mysqld_safe -l defaults-file
complete -c mysqld_safe -l flush-caches
complete -c mysqld_safe -l malloc-lib
complete -c mysqld_safe -l nice
complete -c mysqld_safe -l no-auto-restart
complete -c mysqld_safe -l nowatch
complete -c mysqld_safe -l no-watch
complete -c mysqld_safe -l no-defaults
complete -c mysqld_safe -l numa-interleave
complete -c mysqld_safe -l open-files-limit
complete -c mysqld_safe -l pid-file
complete -c mysqld_safe -l plugin-dir
complete -c mysqld_safe -l port
complete -c mysqld_safe -l skip-kill-mysqld
complete -c mysqld_safe -l socket
complete -c mysqld_safe -l syslog
complete -c mysqld_safe -l skip-syslog
complete -c mysqld_safe -l syslog-tag
complete -c mysqld_safe -l timezone
complete -c mysqld_safe -l user

