# mysql_setpermission
# Autogenerated from man page /usr/share/man/man1/mysql_setpermission.1.gz
complete -c mysql_setpermission -l help -d 'to display the help message, or options that indicate how to connect to the M…'
complete -c mysql_setpermission -l host
complete -c mysql_setpermission -l password
complete -c mysql_setpermission -l port
complete -c mysql_setpermission -l socket
complete -c mysql_setpermission -l user

