# mysql_waitpid
# Autogenerated from man page /usr/share/man/man1/mysql_waitpid.1.gz
complete -c mysql_waitpid -l help
complete -c mysql_waitpid -s '?'
complete -c mysql_waitpid -s I
complete -c mysql_waitpid -l verbose
complete -c mysql_waitpid -s v
complete -c mysql_waitpid -l version
complete -c mysql_waitpid -s V

