# mysql_convert_table_format
# Autogenerated from man page /usr/share/man/man1/mysql_convert_table_format.1.gz
complete -c mysql_convert_table_format -l help
complete -c mysql_convert_table_format -l force
complete -c mysql_convert_table_format -l host
complete -c mysql_convert_table_format -l password
complete -c mysql_convert_table_format -l port
complete -c mysql_convert_table_format -l socket
complete -c mysql_convert_table_format -l type
complete -c mysql_convert_table_format -l user
complete -c mysql_convert_table_format -l verbose
complete -c mysql_convert_table_format -l version

