# mysql_secure_installation
# Autogenerated from man page /usr/share/man/man1/mysql_secure_installation.1.gz
complete -c mysql_secure_installation -l basedir
complete -c mysql_secure_installation -l defaults-extra-file
complete -c mysql_secure_installation -l defaults-file
complete -c mysql_secure_installation -l no-defaults

