# mysqlcheck
# Autogenerated from man page /usr/share/man/man1/mysqlcheck.1.gz
complete -c mysqlcheck -l databases -d or
complete -c mysqlcheck -l all-databases -d 'option to process all tables in one or more databases, an invocation of mysql…'
complete -c mysqlcheck -l help
complete -c mysqlcheck -s '?'
complete -c mysqlcheck -s A
complete -c mysqlcheck -l all-in-1
complete -c mysqlcheck -s 1
complete -c mysqlcheck -l analyze
complete -c mysqlcheck -s a
complete -c mysqlcheck -l auto-repair
complete -c mysqlcheck -l character-sets-dir
complete -c mysqlcheck -l check
complete -c mysqlcheck -s c
complete -c mysqlcheck -l check-only-changed
complete -c mysqlcheck -s C
complete -c mysqlcheck -l check-upgrade
complete -c mysqlcheck -s g
complete -c mysqlcheck -l fix-db-names -d and
complete -c mysqlcheck -l fix-table-names -d 'options.  oc o 2. 3'
complete -c mysqlcheck -l compress
complete -c mysqlcheck -s B
complete -c mysqlcheck -l debug
complete -c mysqlcheck -s '#'
complete -c mysqlcheck -l debug-check
complete -c mysqlcheck -l debug-info
complete -c mysqlcheck -l default-auth
complete -c mysqlcheck -l default-character-set
complete -c mysqlcheck -l defaults-extra-file
complete -c mysqlcheck -l defaults-file
complete -c mysqlcheck -l extended
complete -c mysqlcheck -s e
complete -c mysqlcheck -l fast
complete -c mysqlcheck -s F
complete -c mysqlcheck -l flush
complete -c mysqlcheck -l force
complete -c mysqlcheck -s f
complete -c mysqlcheck -l host
complete -c mysqlcheck -s h
complete -c mysqlcheck -l medium-check
complete -c mysqlcheck -s m
complete -c mysqlcheck -l no-defaults
complete -c mysqlcheck -l optimize
complete -c mysqlcheck -s o
complete -c mysqlcheck -l password
complete -c mysqlcheck -s p
complete -c mysqlcheck -l persistent
complete -c mysqlcheck -s Z
complete -c mysqlcheck -l pipe
complete -c mysqlcheck -s W
complete -c mysqlcheck -l plugin-dir
complete -c mysqlcheck -l port
complete -c mysqlcheck -s P
complete -c mysqlcheck -l print-defaults
complete -c mysqlcheck -l process-tables
complete -c mysqlcheck -l process-views
complete -c mysqlcheck -l protocol
complete -c mysqlcheck -l quick
complete -c mysqlcheck -s q
complete -c mysqlcheck -l repair
complete -c mysqlcheck -s r
complete -c mysqlcheck -l silent
complete -c mysqlcheck -s s
complete -c mysqlcheck -l skip-database
complete -c mysqlcheck -l socket
complete -c mysqlcheck -s S
complete -c mysqlcheck -l ssl
complete -c mysqlcheck -l skip-ssl -d 'oc o 2. 3'
complete -c mysqlcheck -l ssl-ca
complete -c mysqlcheck -l ssl-capath
complete -c mysqlcheck -l ssl-cert
complete -c mysqlcheck -l ssl-cipher
complete -c mysqlcheck -l ssl-key
complete -c mysqlcheck -l ssl-crl
complete -c mysqlcheck -l ssl-crlpath
complete -c mysqlcheck -l ssl-verify-server-cert
complete -c mysqlcheck -l tables
complete -c mysqlcheck -l use-frm
complete -c mysqlcheck -l user
complete -c mysqlcheck -s u
complete -c mysqlcheck -l verbose
complete -c mysqlcheck -s v
complete -c mysqlcheck -l version
complete -c mysqlcheck -s V
complete -c mysqlcheck -l write-binlog
complete -c mysqlcheck -l skip-write-binlog -d 'to cause NO_WRITE_TO_BINLOG to be added to the statements so that they are no…'

