# mysqld_multi
# Autogenerated from man page /usr/share/man/man1/mysqld_multi.1.gz
complete -c mysqld_multi -l config-file -d 'option).  N can be any positive integer'
complete -c mysqld_multi -l no-defaults -d 'oc o 2. 3 With'
complete -c mysqld_multi -l defaults-file -d 'oc o 2'
complete -c mysqld_multi -l defaults-extra-file -d 'option, if one is given'
complete -c mysqld_multi -l help
complete -c mysqld_multi -l example
complete -c mysqld_multi -l log
complete -c mysqld_multi -l mysqladmin
complete -c mysqld_multi -l mysqld
complete -c mysqld_multi -l no-log
complete -c mysqld_multi -l password
complete -c mysqld_multi -l silent
complete -c mysqld_multi -l tcp-ip
complete -c mysqld_multi -l user
complete -c mysqld_multi -l verbose
complete -c mysqld_multi -l version
complete -c mysqld_multi -l wsrep-new-cluster
complete -c mysqld_multi -l bind-address -d 'to cause different servers to listen to different interfaces. ) oc o 2. 3'
complete -c mysqld_multi -l pid-file -d 'option is very important if you are using mysqld_safe to start mysqld (for ex…'
complete -c mysqld_multi -l -------------------------------------------------------------- -d 'MY_PWD=`pwd` # Check if we are starting this relative (for the binary release…'

