# mysql_plugin
# Autogenerated from man page /usr/share/man/man1/mysql_plugin.1.gz
complete -c mysql_plugin -l plugin-load -d 'option at server startup or using the INSTALL PLUGIN and UNINSTALL PLUGIN sta…'
complete -c mysql_plugin -l plugin_name -d 'options named for specific plugins'
complete -c mysql_plugin -l basedir
complete -c mysql_plugin -l datadir
complete -c mysql_plugin -l plugin-dir -d 'options and ignores others'
complete -c mysql_plugin -l help
complete -c mysql_plugin -s '?'
complete -c mysql_plugin -s b
complete -c mysql_plugin -s d
complete -c mysql_plugin -l my-print-defaults
complete -c mysql_plugin -l mysqld
complete -c mysql_plugin -l no-defaults
complete -c mysql_plugin -s p
complete -c mysql_plugin -l plugin-ini
complete -c mysql_plugin -s i
complete -c mysql_plugin -l print-defaults
complete -c mysql_plugin -s P
complete -c mysql_plugin -l verbose
complete -c mysql_plugin -s v
complete -c mysql_plugin -l version
complete -c mysql_plugin -s V

