# mysql_find_rows
# Autogenerated from man page /usr/share/man/man1/mysql_find_rows.1.gz
complete -c mysql_find_rows -l help
complete -c mysql_find_rows -l Information
complete -c mysql_find_rows -l regexp
complete -c mysql_find_rows -l rows
complete -c mysql_find_rows -l skip-use-db
complete -c mysql_find_rows -l start_row

