# mysql
# Autogenerated from man page /usr/share/man/man1/mysql.1.gz
complete -c mysql -l quick -d option
complete -c mysql -l help
complete -c mysql -s '?'
complete -c mysql -s I
complete -c mysql -l abort-source-on-error
complete -c mysql -l auto-rehash
complete -c mysql -l disable-auto-rehash -l no-auto-rehash -l skip-auto-rehash -d 'to disable rehashing'
complete -c mysql -l auto-vertical-output
complete -c mysql -l batch
complete -c mysql -s B
complete -c mysql -l raw -d 'option.  oc o 2. 3'
complete -c mysql -l binary-mode
complete -c mysql -l character-sets-dir
complete -c mysql -l column-names
complete -c mysql -l column-type-info
complete -c mysql -s m
complete -c mysql -l comments
complete -c mysql -s c
complete -c mysql -l compress
complete -c mysql -s C
complete -c mysql -l connect-timeout
complete -c mysql -l database
complete -c mysql -s D
complete -c mysql -l debug
complete -c mysql -s '#'
complete -c mysql -l debug-check
complete -c mysql -l debug-info
complete -c mysql -s T
complete -c mysql -l default-auth
complete -c mysql -l default-character-set
complete -c mysql -l defaults-extra-file
complete -c mysql -l defaults-file
complete -c mysql -l defaults-group-suffix
complete -c mysql -l delimiter
complete -c mysql -l disable-named-commands
complete -c mysql -l enable-cleartext-plugin
complete -c mysql -l execute
complete -c mysql -s e
complete -c mysql -l force
complete -c mysql -s f
complete -c mysql -l host
complete -c mysql -s h
complete -c mysql -l html
complete -c mysql -s H
complete -c mysql -l ignore-spaces
complete -c mysql -s i
complete -c mysql -l init-command
complete -c mysql -l line-numbers
complete -c mysql -l skip-line-numbers -d 'oc o 2. 3'
complete -c mysql -l local-infile
complete -c mysql -l max-allowed-packet
complete -c mysql -l max-join-size
complete -c mysql -l safe-updates -d 'oc o 2. 3'
complete -c mysql -l named-commands
complete -c mysql -s G
complete -c mysql -l skip-named-commands -d 'to disable named commands.  See the section called “MYSQL COMMANDS”'
complete -c mysql -l net-buffer-length
complete -c mysql -s A
complete -c mysql -l no-beep
complete -c mysql -s b
complete -c mysql -l no-defaults
complete -c mysql -l one-database
complete -c mysql -s o
complete -c mysql -l pager
complete -c mysql -l skip-pager -d 'the section called “MYSQL COMMANDS”, discusses output paging further.  oc o 2'
complete -c mysql -l password
complete -c mysql -s p
complete -c mysql -l pipe
complete -c mysql -s W
complete -c mysql -l plugin-dir
complete -c mysql -l port
complete -c mysql -s P
complete -c mysql -l print-defaults
complete -c mysql -l progress-reports
complete -c mysql -l prompt
complete -c mysql -l protocol
complete -c mysql -s q
complete -c mysql -s r
complete -c mysql -l silent -d 'option is given), special characters are escaped in the output so they can be…'
complete -c mysql -l reconnect
complete -c mysql -l skip-reconnect -l disable-reconnect -d 'oc o 2. 3'
complete -c mysql -l i-am-a-dummy
complete -c mysql -s U
complete -c mysql -l secure-auth
complete -c mysql -l select-limit
complete -c mysql -l server-arg
complete -c mysql -l show-warnings
complete -c mysql -l sigint-ignore
complete -c mysql -s s
complete -c mysql -l skip-column-names
complete -c mysql -s N
complete -c mysql -s L
complete -c mysql -l socket
complete -c mysql -s S
complete -c mysql -l ssl
complete -c mysql -l skip-ssl -d 'oc o 2. 3'
complete -c mysql -l ssl-ca
complete -c mysql -l ssl-capath
complete -c mysql -l ssl-cert
complete -c mysql -l ssl-cipher
complete -c mysql -l ssl-key
complete -c mysql -l ssl-crl
complete -c mysql -l ssl-crlpath
complete -c mysql -l ssl-verify-server-cert
complete -c mysql -l table
complete -c mysql -s t
complete -c mysql -l tee
complete -c mysql -l unbuffered
complete -c mysql -s n
complete -c mysql -l user
complete -c mysql -s u
complete -c mysql -l verbose
complete -c mysql -s v
complete -c mysql -l version
complete -c mysql -s V
complete -c mysql -l vertical
complete -c mysql -s E
complete -c mysql -l wait
complete -c mysql -s w
complete -c mysql -l xml
complete -c mysql -s X
complete -c mysql -l var_name -d 'oc o 2. 3 connect_timeout'
complete -c mysql -s F -d and

