# mysql.server
# Autogenerated from man page /usr/share/man/man1/mysql.server.1.gz
complete -c 'mysql.server' -l basedir
complete -c 'mysql.server' -l datadir
complete -c 'mysql.server' -l pid-file
complete -c 'mysql.server' -l service-startup-timeout
complete -c 'mysql.server' -l use-mysqld_safe
complete -c 'mysql.server' -l use-manager
complete -c 'mysql.server' -l user

