# nc
# Autogenerated from man page /usr/share/man/man1/nc.1.gz
complete -c nc -s 4
complete -c nc -s 6
complete -c nc -s U -l unixsock
complete -c nc -l udp -d 'for datagram sockets.  A description of'
complete -c nc -s u
complete -c nc -l sctp
complete -c nc -l vsock
complete -c nc -s g
complete -c nc -s G
complete -c nc -s p -l source-port
complete -c nc -s s -l source
complete -c nc -s l -l listen
complete -c nc -s m -l max-conns
complete -c nc -s k -l keep-open
complete -c nc -l broker
complete -c nc -l chat
complete -c nc -l ssl
complete -c nc -l ssl-verify
complete -c nc -l ssl-trustfile -d 'to give a custom list.  Use'
complete -c nc -s v -d 'one or more times to get details about verification failures'
complete -c nc -l ssl-cert
complete -c nc -l ssl-key
complete -c nc -l ssl-ciphers
complete -c nc -l ssl-servername
complete -c nc -l ssl-alpn
complete -c nc -l proxy
complete -c nc -l proxy-type
complete -c nc -l proxy-auth
complete -c nc -l proxy-dns
complete -c nc -s e -l exec
complete -c nc -s c -l sh-exec
complete -c nc -l lua-exec
complete -c nc -l allow
complete -c nc -l deny
complete -c nc -l allowfile
complete -c nc -l denyfile
complete -c nc -s d -l delay
complete -c nc -s i -l idle-timeout
complete -c nc -s w -l wait
complete -c nc -s o -l output
complete -c nc -s x -l hex-dump
complete -c nc -l append-output
complete -c nc -l append-ouput -d 'along with'
complete -c nc -l verbose
complete -c nc -o vvv
complete -c nc -s C -l crlf
complete -c nc -s h -l help
complete -c nc -l recv-only
complete -c nc -l send-only
complete -c nc -l no-shutdown
complete -c nc -s n -l nodns
complete -c nc -s t -l telnet
complete -c nc -l version

