# ncat
# Autogenerated from man page /usr/share/man/man1/ncat.1.gz
complete -c ncat -s 4
complete -c ncat -s 6
complete -c ncat -s U -l unixsock
complete -c ncat -l udp -d 'for datagram sockets.  A description of'
complete -c ncat -s u
complete -c ncat -l sctp
complete -c ncat -l vsock
complete -c ncat -s g
complete -c ncat -s G
complete -c ncat -s p -l source-port
complete -c ncat -s s -l source
complete -c ncat -s l -l listen
complete -c ncat -s m -l max-conns
complete -c ncat -s k -l keep-open
complete -c ncat -l broker
complete -c ncat -l chat
complete -c ncat -l ssl
complete -c ncat -l ssl-verify
complete -c ncat -l ssl-trustfile -d 'to give a custom list.  Use'
complete -c ncat -s v -d 'one or more times to get details about verification failures'
complete -c ncat -l ssl-cert
complete -c ncat -l ssl-key
complete -c ncat -l ssl-ciphers
complete -c ncat -l ssl-servername
complete -c ncat -l ssl-alpn
complete -c ncat -l proxy
complete -c ncat -l proxy-type
complete -c ncat -l proxy-auth
complete -c ncat -l proxy-dns
complete -c ncat -s e -l exec
complete -c ncat -s c -l sh-exec
complete -c ncat -l lua-exec
complete -c ncat -l allow
complete -c ncat -l deny
complete -c ncat -l allowfile
complete -c ncat -l denyfile
complete -c ncat -s d -l delay
complete -c ncat -s i -l idle-timeout
complete -c ncat -s w -l wait
complete -c ncat -s o -l output
complete -c ncat -s x -l hex-dump
complete -c ncat -l append-output
complete -c ncat -l append-ouput -d 'along with'
complete -c ncat -l verbose
complete -c ncat -o vvv
complete -c ncat -s C -l crlf
complete -c ncat -s h -l help
complete -c ncat -l recv-only
complete -c ncat -l send-only
complete -c ncat -l no-shutdown
complete -c ncat -s n -l nodns
complete -c ncat -s t -l telnet
complete -c ncat -l version

