# ndctl-enable-dimm
# Autogenerated from man page /usr/share/man/man1/ndctl-enable-dimm.1.gz
complete -c ndctl-enable-dimm -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'

