# ndctl-check-namespace
# Autogenerated from man page /usr/share/man/man1/ndctl-check-namespace.1.gz
complete -c ndctl-check-namespace -s R -l repair -d 'Perform metadata repairs if possible'
complete -c ndctl-check-namespace -s L -l rewrite-log -d 'Regenerate the BTT log and write it to media'
complete -c ndctl-check-namespace -s f -l force -d 'Unless this option is specified, a check-namespace operation will fail if the…'
complete -c ndctl-check-namespace -s v -l verbose -d 'Emit debug messages for the namespace check process'
complete -c ndctl-check-namespace -s r -l region -d 'A regionX device name, or a region id number'
complete -c ndctl-check-namespace -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'

