# ndctl-inject-error
# Autogenerated from man page /usr/share/man/man1/ndctl-inject-error.1.gz
complete -c ndctl-inject-error -s B -l block -d 'Namespace block offset in 512 byte sized blocks where the error is to be inje…'
complete -c ndctl-inject-error -s n -l count -d 'Number of blocks to inject as errors'
complete -c ndctl-inject-error -s d -l uninject -d 'This option will ask the platform to remove any injected errors for the speci…'
complete -c ndctl-inject-error -s t -l status -d 'This option will retrieve the status of injected errors'
complete -c ndctl-inject-error -s N -l no-notify -d 'This option is only valid when injecting errors'
complete -c ndctl-inject-error -s S -l saturate -d 'This option forces error injection or un-injection to cover the entire addres…'
complete -c ndctl-inject-error -s v -l verbose -d 'Emit debug messages for the error injection process'
complete -c ndctl-inject-error -s u -l human -d 'Format numbers representing storage sizes, or offsets as human readable strin…'
complete -c ndctl-inject-error -s r -l region -d 'A regionX device name, or a region id number'
complete -c ndctl-inject-error -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'

