# ndctl-load-keys
# Autogenerated from man page /usr/share/man/man1/ndctl-load-keys.1.gz
complete -c ndctl-load-keys -s p -l key-path -d 'Path to where key related files reside'
complete -c ndctl-load-keys -s t -l tpm-handle -d 'Provide a TPM handle (should be a string such as 0x81000001)'

