# ndctl-setup-passphrase
# Autogenerated from man page /usr/share/man/man1/ndctl-setup-passphrase.1.gz
complete -c ndctl-setup-passphrase -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'
complete -c ndctl-setup-passphrase -s k -l key_handle -d 'Handle for the master kek (key-encryption-key) that will be used for sealing …'
complete -c ndctl-setup-passphrase -s m -l master-passphrase -d 'Indicates that we are managing the master passphrase instead of the user pass…'
complete -c ndctl-setup-passphrase -s v -l verbose -d 'Emit debug messages'

