# ndctl-read-labels
# Autogenerated from man page /usr/share/man/man1/ndctl-read-labels.1.gz
complete -c ndctl-read-labels -s s -l size -d 'Limit the operation to the given number of bytes'
complete -c ndctl-read-labels -s O -l offset -d 'Begin the operation at the given offset into the label area'
complete -c ndctl-read-labels -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'
complete -c ndctl-read-labels -s v -d 'Turn on verbose debug messages in the library (if ndctl was built with loggin…'
complete -c ndctl-read-labels -s I -l index -d 'Limit the span of the label operation to just the index-block area'
complete -c ndctl-read-labels -s o -l output -d 'output file'
complete -c ndctl-read-labels -s j -l json -d 'parse the label data into json assuming the NVDIMM Namespace Specification fo…'
complete -c ndctl-read-labels -s u -l human -d 'enable json output and convert number formats to human readable strings, for …'

