# ndctl-clear-errors
# Autogenerated from man page /usr/share/man/man1/ndctl-clear-errors.1.gz
complete -c ndctl-clear-errors -s s -l scrub -d 'Perform a scrub on the bus prior to clearing errors'
complete -c ndctl-clear-errors -s v -l verbose -d 'Emit debug messages'
complete -c ndctl-clear-errors -s r -l region -d 'A regionX device name, or a region id number'
complete -c ndctl-clear-errors -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'

