# ndctl-list
# Autogenerated from man page /usr/share/man/man1/ndctl-list.1.gz
complete -c ndctl-list -s r -l region -d 'A regionX device name, or a region id number'
complete -c ndctl-list -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'
complete -c ndctl-list -s d -l dimm -d 'An nmemX device name, or dimm id number'
complete -c ndctl-list -s n -l namespace -d 'An namespaceX. Y device name, or namespace region plus id tuple X. Y'
complete -c ndctl-list -s m -l mode -d 'Filter listing by the mode (raw, fsdax, sector or devdax) of the namespace(s)'
complete -c ndctl-list -s U -l numa-node -d 'Filter listing by numa node'
complete -c ndctl-list -s B -l buses -d 'Include bus info in the listing'
complete -c ndctl-list -s D -l dimms -d 'Include dimm info in the listing'
complete -c ndctl-list -s H -l health -d 'Include dimm health info in the listing.  For example:'
complete -c ndctl-list -s F -l firmware -d 'Include firmware info in the listing, including the state and capability of r…'
complete -c ndctl-list -s X -l device-dax -d 'Include device-dax ("daxregion") details when a namespace is in "devdax" mode'
complete -c ndctl-list -s R -l regions -d 'Include region info in the listing'
complete -c ndctl-list -s N -l namespaces -d 'Include namespace info in the listing'
complete -c ndctl-list -s i -l idle -d 'Include idle (not enabled) devices in the listing'
complete -c ndctl-list -s c -l configured -d 'Include configured devices (non-zero sized namespaces) regardless of whether …'
complete -c ndctl-list -s C -l capabilities -d 'Include region capabilities in the listing, i. e'
complete -c ndctl-list -s M -l media-errors -d 'Include media errors (badblocks) in the listing'
complete -c ndctl-list -s v -l verbose -d 'Increase verbosity of the output'
complete -c ndctl-list -s u -l human -d 'Format numbers representing storage sizes, or offsets as human readable strin…'
complete -c ndctl-list -o vv -d Everything
complete -c ndctl-list -o vvv -d Everything

