# ndctl-freeze-security
# Autogenerated from man page /usr/share/man/man1/ndctl-freeze-security.1.gz
complete -c ndctl-freeze-security -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'
complete -c ndctl-freeze-security -s v -l verbose -d 'Emit debug messages'

