# ndctl-write-infoblock
# Autogenerated from man page /usr/share/man/man1/ndctl-write-infoblock.1.gz
complete -c ndctl-write-infoblock -s c -l stdout -d 'Write the infoblock to stdout'
complete -c ndctl-write-infoblock -s o -l output -d 'Write the infoblock to the given file (mutually exclusive with --stdout)'
complete -c ndctl-write-infoblock -s m -l mode -d 'Select the infoblock mode between fsdax and devdax'
complete -c ndctl-write-infoblock -s s -l size -d 'Override the default size determined from the size of the file specified to -…'
complete -c ndctl-write-infoblock -s a -l align -d 'Specify the "align" value in the infoblock'
complete -c ndctl-write-infoblock -s u -l uuid -d 'Override the default autogenerated UUID with the given value'
complete -c ndctl-write-infoblock -s M -l map -d 'Select whether the page map array is allocated from the device or from "Syste…'
complete -c ndctl-write-infoblock -s p -l parent-uuid -d 'When the infoblock is stored on a labelled namespace the UUID of the namespac…'
complete -c ndctl-write-infoblock -s O -l offset -d 'By default the assumption is that the infoblock is being written to a namespa…'
complete -c ndctl-write-infoblock -s r -l region -d 'A regionX device name, or a region id number'

