# ndctl-read-infoblock
# Autogenerated from man page /usr/share/man/man1/ndctl-read-infoblock.1.gz
complete -c ndctl-read-infoblock -s V -l verify -d 'Attempt to validate that the info-block is self consistent by validating the …'
complete -c ndctl-read-infoblock -s o -l output -d 'Output file'
complete -c ndctl-read-infoblock -s j -l json -d 'Parse the info-block data into json'
complete -c ndctl-read-infoblock -s u -l human -d 'Enable json output and convert number formats to human readable strings, for …'
complete -c ndctl-read-infoblock -s r -l region -d 'A regionX device name, or a region id number'

