# ndctl-disable-region
# Autogenerated from man page /usr/share/man/man1/ndctl-disable-region.1.gz
complete -c ndctl-disable-region -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'

