# ndctl-disable-namespace
# Autogenerated from man page /usr/share/man/man1/ndctl-disable-namespace.1.gz
complete -c ndctl-disable-namespace -s r -l region -d 'A regionX device name, or a region id number'
complete -c ndctl-disable-namespace -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'
complete -c ndctl-disable-namespace -s v -l verbose -d 'Emit debug messages for the namespace operation'

