# ndctl-enable-region
# Autogenerated from man page /usr/share/man/man1/ndctl-enable-region.1.gz
complete -c ndctl-enable-region -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'

