# ndctl-destroy-namespace
# Autogenerated from man page /usr/share/man/man1/ndctl-destroy-namespace.1.gz
complete -c ndctl-destroy-namespace -s r -l region -d 'A regionX device name, or a region id number'
complete -c ndctl-destroy-namespace -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'
complete -c ndctl-destroy-namespace -s v -l verbose -d 'Emit debug messages for the namespace operation'
complete -c ndctl-destroy-namespace -s f -l force -d 'Unless this option is specified the destroy namespace operation will fail if …'

