# ndctl-wait-overwrite
# Autogenerated from man page /usr/share/man/man1/ndctl-wait-overwrite.1.gz
complete -c ndctl-wait-overwrite -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'
complete -c ndctl-wait-overwrite -s v -l verbose -d 'Emit debug messages'

