# ndctl-zero-labels
# Autogenerated from man page /usr/share/man/man1/ndctl-zero-labels.1.gz
complete -c ndctl-zero-labels -s s -l size -d 'Limit the operation to the given number of bytes'
complete -c ndctl-zero-labels -s O -l offset -d 'Begin the operation at the given offset into the label area'
complete -c ndctl-zero-labels -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'
complete -c ndctl-zero-labels -s v -d 'Turn on verbose debug messages in the library (if ndctl was built with loggin…'

