# ndctl-init-labels
# Autogenerated from man page /usr/share/man/man1/ndctl-init-labels.1.gz
complete -c ndctl-init-labels -s s -l size -d 'Limit the operation to the given number of bytes'
complete -c ndctl-init-labels -s O -l offset -d 'Begin the operation at the given offset into the label area'
complete -c ndctl-init-labels -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'
complete -c ndctl-init-labels -s v -d 'Turn on verbose debug messages in the library (if ndctl was built with loggin…'
complete -c ndctl-init-labels -s f -l force -d 'Force initialization of the label space even if there appears to be an existi…'
complete -c ndctl-init-labels -s V -l label-version -d 'Initialize with a specific version of labels from the namespace label specifi…'

