# ndctl-create-namespace
# Autogenerated from man page /usr/share/man/man1/ndctl-create-namespace.1.gz
complete -c ndctl-create-namespace -s m -l mode -d sp
complete -c ndctl-create-namespace -s s -l size -d 'For NVDIMM devices that support namespace labels, set the namespace size in b…'
complete -c ndctl-create-namespace -s a -l align -d 'Applications that want to establish dax memory mappings with page table entri…'
complete -c ndctl-create-namespace -s e -l reconfig -d 'Reconfigure an existing namespace'
complete -c ndctl-create-namespace -s u -l uuid -d 'This option is not recommended as a new uuid should be generated every time a…'
complete -c ndctl-create-namespace -s n -l name -d 'For NVDIMM devices that support namespace labels, specify a human friendly na…'
complete -c ndctl-create-namespace -s l -l sector-size -d 'Specify the logical sector size (LBA size) of the Linux block device associat…'
complete -c ndctl-create-namespace -s M -l map -d 'A pmem namespace in "fsdax" or "devdax" mode requires allocation of per-page …'
complete -c ndctl-create-namespace -s c -l continue -d 'Do not stop after creating one namespace'
complete -c ndctl-create-namespace -s f -l force -d 'Unless this option is specified the reconfigure namespace operation will fail…'
complete -c ndctl-create-namespace -s L -l autolabel -l no-autolabel -d 'Legacy NVDIMM devices do not support namespace labels'
complete -c ndctl-create-namespace -s R -l autorecover -l no-autorecover -d 'By default, if a namespace creation attempt fails, ndctl will cleanup the par…'
complete -c ndctl-create-namespace -s v -l verbose -d 'Emit debug messages for the namespace creation process'
complete -c ndctl-create-namespace -s r -l region -d 'A regionX device name, or a region id number'
complete -c ndctl-create-namespace -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'

