# ndctl-remove-passphrase
# Autogenerated from man page /usr/share/man/man1/ndctl-remove-passphrase.1.gz
complete -c ndctl-remove-passphrase -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'
complete -c ndctl-remove-passphrase -s v -l verbose -d 'Emit debug messages'
complete -c ndctl-remove-passphrase -s m -l master-passphrase -d 'Indicates that we are managing the master passphrase instead of the user pass…'

