# ndctl-activate-firmware
# Autogenerated from man page /usr/share/man/man1/ndctl-activate-firmware.1.gz
complete -c ndctl-activate-firmware -s n -l dry-run -d 'Perform all actions related to activation including honoring --idle and --for…'
complete -c ndctl-activate-firmware -s I -l idle -d 'Implied by default, this option controls whether the platform will attempt to…'
complete -c ndctl-activate-firmware -s f -l force -d 'The activation method defaults to the reported "bus. firmware'
complete -c ndctl-activate-firmware -s v -l verbose -d 'Emit debug messages for the firmware activation procedure'

