# ndctl-update-firmware
# Autogenerated from man page /usr/share/man/man1/ndctl-update-firmware.1.gz
complete -c ndctl-update-firmware -s b -l bus -d 'A bus id number, or a provider string (e. g.  "ACPI. NFIT")'
complete -c ndctl-update-firmware -s f -l firmware -d 'firmware file used to perform the update'
complete -c ndctl-update-firmware -s i -l force -d 'Ignore in-progress Address Range Scrub and try to submit the firmware update,…'
complete -c ndctl-update-firmware -s A -l arm -d 'Arm a device for firmware activation'
complete -c ndctl-update-firmware -s D -l disarm -d 'Disarm devices after uploading the firmware file, or manually disarm devices …'
complete -c ndctl-update-firmware -s v -l verbose -d 'Emit debug messages for the namespace check process'

