# netkey-tool
# Autogenerated from man page /usr/share/man/man1/netkey-tool.1.gz
complete -c netkey-tool -l help -s h -d 'Displays a short help message'
complete -c netkey-tool -l pin -s p -d 'Specifies the current value of the global PIN'
complete -c netkey-tool -l puk -s u -d 'Specifies the current value of the global PUK'
complete -c netkey-tool -l pin0 -s 0 -d 'Specifies the current value of the local PIN0 (aka local PIN)'
complete -c netkey-tool -l pin1 -s 1 -d 'Specifies the current value of the local PIN1 (aka local PUK)'
complete -c netkey-tool -l reader -s r -d 'Number of the reader to use'
complete -c netkey-tool -s v -d 'Causes netkey-tool to be more verbose'

