# nfsref
# Autogenerated from man page /usr/share/man/man8/nfsref.8.gz
complete -c nfsref -s d -l debug -d 'Enables debugging messages during operation'
complete -c nfsref -s t -l type -d 'Specifies the junction type for the operation'

