# nomarch
# Autogenerated from man page /usr/share/man/man1/nomarch.1.gz
complete -c nomarch -s h -d 'give terse usage help'
complete -c nomarch -s l -d 'list files in archive'
complete -c nomarch -s p -d 'extract to standard output, rather than to separate files'
complete -c nomarch -s t -d 'test files in archive (more precisely, check file CRCs)'
complete -c nomarch -s U -d 'use uppercase filenames; more precisely, preserve original case from archive'
complete -c nomarch -s v -d 'give verbose output (when used with . RI ` -l \')'

