# nvme-fdp-events
# Autogenerated from man page /usr/share/man/man1/nvme-fdp-events.1.gz
complete -c nvme-fdp-events -s e -l endgrp-id -d 'The endurance group identifier to use when requesting the log page'
complete -c nvme-fdp-events -s E -l host-events -d 'Request the controller to report host events'
complete -c nvme-fdp-events -s b -l raw-binary -d 'Print the raw buffer to the standard output stream'
complete -c nvme-fdp-events -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

