# nvme-seagate-clear-pcie-correctable-errors
# Autogenerated from man page /usr/share/man/man1/nvme-seagate-clear-pcie-correctable-errors.1.gz
complete -c nvme-seagate-clear-pcie-correctable-errors -s s -l save -d 'Specifies that the controller shall save the attribute'

