# nvme-seagate-vs-fw-activate-history
# Autogenerated from man page /usr/share/man/man1/nvme-seagate-vs-fw-activate-history.1.gz
complete -c nvme-seagate-vs-fw-activate-history -s n -l namespace-id -d 'Desired namespace'
complete -c nvme-seagate-vs-fw-activate-history -s f -l dump-file -d 'Dump file'

