# nvme-seagate-clear-fw-activate-history
# Autogenerated from man page /usr/share/man/man1/nvme-seagate-clear-fw-activate-history.1.gz
complete -c nvme-seagate-clear-fw-activate-history -s s -l save -d EXAMPLES

