# nvme-seagate-vs-log-page-sup
# Autogenerated from man page /usr/share/man/man1/nvme-seagate-vs-log-page-sup.1.gz
complete -c nvme-seagate-vs-log-page-sup -s o -l output-format -d 'Output in binary format'

