# nvme-show-topology
# Autogenerated from man page /usr/share/man/man1/nvme-show-topology.1.gz
complete -c nvme-show-topology -s o -l output-format -d 'Set the reporting format to normal or json'
complete -c nvme-show-topology -s v -l verbose -d 'Increase the information in the output, showing nvme subsystems, controllers …'
complete -c nvme-show-topology -s r -l ranking -d 'Set the ranking orer to namespace (default) or ctrl'

