# nvme-wdc-vs-hw-rev-log
# Autogenerated from man page /usr/share/man/man1/nvme-wdc-vs-hw-rev-log.1.gz
complete -c nvme-wdc-vs-hw-rev-log -s o -l output-format -d 'Set the reporting format to normal, or json'
complete -c nvme-wdc-vs-hw-rev-log -s n -l namespace-id -d 'Sets the command\'s nsid value to the given nsid'

