# nvme-seagate-vs-internal-log
# Autogenerated from man page /usr/share/man/man1/nvme-seagate-vs-internal-log.1.gz
complete -c nvme-seagate-vs-internal-log -s n -l namespace-id -d 'Desired namespace'
complete -c nvme-seagate-vs-internal-log -s f -l dump-file -d 'Dump file'

