# nvme-fdp-configs
# Autogenerated from man page /usr/share/man/man1/nvme-fdp-configs.1.gz
complete -c nvme-fdp-configs -s e -l endgrp-id -d 'The endurance group identifier to use when requesting the log page'
complete -c nvme-fdp-configs -s H -l human-readable -d 'Parse, print and describe individual parts of bitfields'
complete -c nvme-fdp-configs -s b -l raw-binary -d 'Print the raw buffer to the standard output stream'
complete -c nvme-fdp-configs -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

