# nvme-fdp-set-events
# Autogenerated from man page /usr/share/man/man1/nvme-fdp-set-events.1.gz
complete -c nvme-fdp-set-events -s n -l namespace-id -d 'Namespace identifier'
complete -c nvme-fdp-set-events -s b -l raw-binary -d 'Print the raw buffer to the standard output stream'
complete -c nvme-fdp-set-events -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

