# nvme-ocp-clear-fw-activate-history
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-clear-fw-activate-history.1.gz
complete -c nvme-ocp-clear-fw-activate-history -s n -l no-uuid -d 'Do not try to automatically detect UUID index for this command (required for …'

