# nvme-ana-log
# Autogenerated from man page /usr/share/man/man1/nvme-ana-log.1.gz
complete -c nvme-ana-log -s g -l groups -d 'Return the list of ANA groups without the namespace listing'
complete -c nvme-ana-log -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

