# nvme-seagate-vs-smart-add-log
# Autogenerated from man page /usr/share/man/man1/nvme-seagate-vs-smart-add-log.1.gz
complete -c nvme-seagate-vs-smart-add-log -s l -l log -d 'Log number, page 0xC4 (Extended SMART log page) and page 0xCF (DRAM Supercap …'
complete -c nvme-seagate-vs-smart-add-log -s n -l namespace-id -d 'Namespace number'
complete -c nvme-seagate-vs-smart-add-log -s o -l output-file -d 'Output in binary format.  Defaults to text-formatted dump to stdout'

