# nvme-create-ns
# Autogenerated from man page /usr/share/man/man1/nvme-create-ns.1.gz
complete -c nvme-create-ns -s s -l nsze -d 'The namespace size'
complete -c nvme-create-ns -s c -l ncap -d 'The namespace capacity'
complete -c nvme-create-ns -s f -l flbas -d 'The namespace formatted logical block size setting'
complete -c nvme-create-ns -s d -l dps -d 'The data protection settings'
complete -c nvme-create-ns -s m -l nmic -d 'Namespace multipath and sharing capabilities'
complete -c nvme-create-ns -s a -l anagrp-id -d 'ANA Group Identifier'
complete -c nvme-create-ns -s i -l nvmset-id -d 'This field specifies the identifier of the NVM Set'
complete -c nvme-create-ns -s y -l csi -d 'This field specifies the identifier of command set'
complete -c nvme-create-ns -s l -l lbstm -d 'Logical Block Storage Tag Mask for end-to-end protection'
complete -c nvme-create-ns -s b -l block-size -d 'Target block size the new namespace should be formatted as'
complete -c nvme-create-ns -s S -l nsze-si -d 'The namespace size (NSZE) in standard SI units'
complete -c nvme-create-ns -s C -l ncap-si -d 'The namespace capacity (NCAP) in standard SI units'

