# nvme-fdp-update
# Autogenerated from man page /usr/share/man/man1/nvme-fdp-update.1.gz
complete -c nvme-fdp-update -s n -l namespace-id -d 'Namespace identifier'
complete -c nvme-fdp-update -s p -l pids -d 'Comma-separated list of placement identifiers to update'

