# nvme-seagate-get-ctrl-tele
# Autogenerated from man page /usr/share/man/man1/nvme-seagate-get-ctrl-tele.1.gz
complete -c nvme-seagate-get-ctrl-tele -s n -l namespace-id -d 'Desired namespace'
complete -c nvme-seagate-get-ctrl-tele -s b -l raw-binary -d 'Output in raw format'

