# nvme-device-self-test
# Autogenerated from man page /usr/share/man/man1/nvme-device-self-test.1.gz
complete -c nvme-device-self-test -s n -l namespace-id -d 'Indicate the namespace in which the device self-test has to be carried out'
complete -c nvme-device-self-test -s s -l self-test-code -d 'This field specifies the action taken by the device self-test command : 0h: S…'
complete -c nvme-device-self-test -s w -l wait -d 'Wait for the device self test to complete before exiting The device self-test…'

