# nvme-seagate-vs-pcie-stats
# Autogenerated from man page /usr/share/man/man1/nvme-seagate-vs-pcie-stats.1.gz
complete -c nvme-seagate-vs-pcie-stats -s o -l output-format -d 'Output in binary format'

