# nvme-seagate-get-host-tele
# Autogenerated from man page /usr/share/man/man1/nvme-seagate-get-host-tele.1.gz
complete -c nvme-seagate-get-host-tele -s n -l namespace-id -d 'desired namespace'
complete -c nvme-seagate-get-host-tele -s i -l log_specific -d '1 - controller shall capture Data representing the internal state of the cont…'
complete -c nvme-seagate-get-host-tele -s b -l raw-binary -d 'output in raw format'

