# nvme-fdp-status
# Autogenerated from man page /usr/share/man/man1/nvme-fdp-status.1.gz
complete -c nvme-fdp-status -s n -l namespace-id -d 'Namespace identifier'
complete -c nvme-fdp-status -s b -l raw-binary -d 'Print the raw buffer to the standard output stream'
complete -c nvme-fdp-status -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

