# nvme-fdp-stats
# Autogenerated from man page /usr/share/man/man1/nvme-fdp-stats.1.gz
complete -c nvme-fdp-stats -s e -l endgrp-id -d 'The endurance group identifier to use when requesting the log page'
complete -c nvme-fdp-stats -s b -l raw-binary -d 'Print the raw buffer to the standard output stream'
complete -c nvme-fdp-stats -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

