# o2cb_ctl
# Autogenerated from man page /usr/share/man/man8/o2cb_ctl.8.gz
complete -c o2cb_ctl -s C -d 'Create an object in the OCFS2 Cluster Configuration'
complete -c o2cb_ctl -s D -d 'Delete an object from the existing OCFS2 Cluster Configuration'
complete -c o2cb_ctl -s I -d 'Print information about the OCFS2 Cluster Configuration'
complete -c o2cb_ctl -s H -d 'Change an object or objects in the existing OCFS2 Cluster Configuration'
complete -c o2cb_ctl -s h -d 'Displays help and exit'

