# o2cb
# Autogenerated from man page /usr/share/man/man8/o2cb.8.gz
complete -c o2cb -l config-file -d 'Specify a path to the configuration file'
complete -c o2cb -s v -l verbose -d 'Verbose mode'
complete -c o2cb -s h -l help -d Help

