# o2cluster
# Autogenerated from man page /usr/share/man/man8/o2cluster.8.gz
complete -c o2cluster -s o -l show-ondisk -d 'Shows the cluster stack stamped on-disk'
complete -c o2cluster -s r -l show-running -d 'Shows the active cluster stack'
complete -c o2cluster -s u -l update -d 'Updates the on-disk cluster stack with the one provided'
complete -c o2cluster -s v -l verbose -d 'Verbose mode'
complete -c o2cluster -s V -l version -d 'Show version and exit'
complete -c o2cluster -s y -l yes -d 'Always answer Yes in interactive command line'

