# o2hbmonitor
# Autogenerated from man page /usr/share/man/man8/o2hbmonitor.8.gz
complete -c o2hbmonitor -s w -d 'Warn threshold percent.  It is the percentage of the idle threshold'
complete -c o2hbmonitor -s i -d 'Interactive mode.  It works as a daemon by default'
complete -c o2hbmonitor -s v -d 'Verbose mode.  It logs messages only to the system logger by default'

