# o2image
# Autogenerated from man page /usr/share/man/man8/o2image.8.gz
complete -c o2image -s r -d 'Copies the meta-data to the image-file in the raw format'
complete -c o2image -s I -d 'Restores meta-data from the image-file onto the device'

