# o2info
# Autogenerated from man page /usr/share/man/man1/o2info.1.gz
complete -c o2info -s C -l cluster-coherent -d 'Force cluster coherency when querying a mounted file systems'
complete -c o2info -l fs-features -d 'Show all the file system features (compat, incompat, ro compat) enabled on th…'
complete -c o2info -l volinfo -d 'Show file system information such as label, uuid, block and cluster sizes, no…'
complete -c o2info -l mkfs -d 'Show file system information in mkfs. ocfs2(8) format'
complete -c o2info -l freeinode -d 'Show the inode (allocated/free) count for all slots in the file system'
complete -c o2info -l freefrag -d 'Show the free space fragmentation of the file system'
complete -c o2info -l space-usage -d 'Show the disk space used by a file in block sized units'
complete -c o2info -l filestat -d 'Show the extended stat(1) information that includes the number of clusters co…'
complete -c o2info -s V -l version -d 'Show version and exit'

