# ocfs2_hb_ctl
# Autogenerated from man page /usr/share/man/man8/ocfs2_hb_ctl.8.gz
complete -c ocfs2_hb_ctl -s S -d 'Starts the heartbeat'
complete -c ocfs2_hb_ctl -s K -d 'Stops the heartbeat'
complete -c ocfs2_hb_ctl -s I -d 'Prints the heartbeat reference counts for that heartbeat region'
complete -c ocfs2_hb_ctl -s d -d 'Specify region by device name'
complete -c ocfs2_hb_ctl -s u -d 'Specify region by device uuid'
complete -c ocfs2_hb_ctl -s n -d 'Adjust IO priority for the heartbeat thread'

