# odbc_config
# Autogenerated from man page /usr/share/man/man1/odbc_config.1.gz
complete -c odbc_config -l prefix -d 'Prefix for architecture-independent files'
complete -c odbc_config -l exec-prefix -d 'Prefix for architecture-dependent files'
complete -c odbc_config -l include-prefix -d 'Directory containing C header files for unixODBC'
complete -c odbc_config -l lib-prefix -d 'Directory containing unixODBC shared libraries'
complete -c odbc_config -l bin-prefix -d 'Directory containing unixODBC utilities'
complete -c odbc_config -l version -d 'Current version of unixODBC'
complete -c odbc_config -l libs -d 'Compiler flags for linking dynamic libraries'
complete -c odbc_config -l static-libs -d 'Absolute file name of the unixODBC static library (libodbc. a)'
complete -c odbc_config -l libtool-libs -d 'Absolute file name of the unixODBC libtool library (libodbc. la)'
complete -c odbc_config -l cflags -d 'Outputs compiler flags to find header files, as well as critical compiler fla…'
complete -c odbc_config -l odbcversion -d 'Version of the ODBC specification used by unixODBC'
complete -c odbc_config -l odbcini -d 'Absolute file name of the system-wide DSN configuration file odbc. ini'
complete -c odbc_config -l odbcinstini -d 'Absolute file name of the unixODBC driver configuration file odbcinst. ini'
complete -c odbc_config -l header -d 'Definitions of C preprocessor constants used by unixODBC'
complete -c odbc_config -l ulen -d 'Compiler flag that defines SIZEOF_SQLULEN'

