# odbcinst
# Autogenerated from man page /usr/share/man/man1/odbcinst.1.gz
complete -c odbcinst -s i -d 'Install a new OBJECT (by adding a section to a configuration file)'
complete -c odbcinst -s u -d 'Uninstall an existing OBJECT (by removing a section from a configuration file)'
complete -c odbcinst -s q -d 'Query ODBC configuration files and print available options for the specified …'
complete -c odbcinst -s j -d 'Print the current configuration of unixODBC, including paths to configuration…'
complete -c odbcinst -s c -d 'Call SQLCreateDataSource'
complete -c odbcinst -s m -d 'Call SQLManageDataSources'
complete -c odbcinst -l version -d 'Display the program version. SS OBJECTS'
complete -c odbcinst -s d -d 'The specified ACTION affects a driver (and thus the odbcinst'
complete -c odbcinst -s s -d 'The specified ACTION affects a data source (and thus the user or system odbc'
complete -c odbcinst -s f -d 'FILE is a template describing the configuration of the installed OBJECT (only…'
complete -c odbcinst -s r -d 'Act in the same way as for the -f OPTION, but take standard input as the temp…'
complete -c odbcinst -s n -d 'Specifies the NAME of the OBJECT'
complete -c odbcinst -s v -d 'Disable all information, warning and error messages'
complete -c odbcinst -s l -d 'The specified data source is system-wide'
complete -c odbcinst -s h -d 'The specified data source is user-specific'

