# okular
# Autogenerated from man page /usr/share/man/man1/okular.1.gz
complete -c okular -s p -l page
complete -c okular -l presentation
complete -c okular -l print
complete -c okular -l print-and-exit
complete -c okular -l unique
complete -c okular -l noraise
complete -c okular -l find
complete -c okular -l editor-cmd

