# oLschema2ldif
# Autogenerated from man page /usr/share/man/man1/oLschema2ldif.1.gz
complete -c oLschema2ldif -s I -d 'OpenLDAP schema to read'
complete -c oLschema2ldif -s O -d 'File to write ldif version of schema to'

