# openssl-prime.1ossl
# Autogenerated from man page /usr/share/man/man1/openssl-prime.1ossl.gz
complete -c 'openssl-prime.1ossl' -o help -d 'X Item "-help" Display an option summary'
complete -c 'openssl-prime.1ossl' -o hex -d 'X Item "-hex" Generate hex output'
complete -c 'openssl-prime.1ossl' -o generate -d 'X Item "-generate" Generate a prime number'
complete -c 'openssl-prime.1ossl' -o bits -d 'X Item "-bits num" Generate a prime with num bits'
complete -c 'openssl-prime.1ossl' -o safe -d 'X Item "-safe" When used with -generate, generates a "safe" prime'
complete -c 'openssl-prime.1ossl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-prime.1ossl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-prime.1ossl' -o propquery -d 'X Item "-propquery propq" '
complete -c 'openssl-prime.1ossl' -o checks

