# openssl-engine.1ossl
# Autogenerated from man page /usr/share/man/man1/openssl-engine.1ossl.gz
complete -c 'openssl-engine.1ossl' -o help -d 'X Item "-help" Display an option summary'
complete -c 'openssl-engine.1ossl' -s v -o vv -o vvv -o vvvv -d 'X Item "-v -vv -vvv -vvvv" Provides information about each specified engine'
complete -c 'openssl-engine.1ossl' -s c -d 'X Item "-c" Lists the capabilities of each engine'
complete -c 'openssl-engine.1ossl' -s t -d 'X Item "-t" Tests if each specified engine is available, and displays the ans…'
complete -c 'openssl-engine.1ossl' -o tt -d 'X Item "-tt" Displays an error trace for any unavailable engine'
complete -c 'openssl-engine.1ossl' -o pre -d 'X Item "-pre command"'
complete -c 'openssl-engine.1ossl' -o post -d 'Command-line configuration of engines'

