# openssl-genrsa.1ossl
# Autogenerated from man page /usr/share/man/man1/openssl-genrsa.1ossl.gz
complete -c 'openssl-genrsa.1ossl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-genrsa.1ossl' -o out -d 'X Item "-out filename" Output the key to the specified file'
complete -c 'openssl-genrsa.1ossl' -o passout -d 'X Item "-passout arg" The output file password source'
complete -c 'openssl-genrsa.1ossl' -o aes128 -o aes192 -o aes256 -o aria128 -o aria192 -o aria256 -o camellia128 -o camellia192 -o camellia256 -o des -o des3 -o idea -d 'X Item "-aes128, -aes192, -aes256, -aria128, -aria192, -aria256, -camellia128…'
complete -c 'openssl-genrsa.1ossl' -o F4 -o f4 -s 3 -d 'X Item "-F4, -f4, -3" The public exponent to use, either 65537 or 3'
complete -c 'openssl-genrsa.1ossl' -o primes -d 'X Item "-primes num" Specify the number of primes to use while generating the…'
complete -c 'openssl-genrsa.1ossl' -o verbose -d 'X Item "-verbose" Print extra details about the operations being performed'
complete -c 'openssl-genrsa.1ossl' -o traditional -d 'X Item "-traditional" Write the key using the traditional PKCS#1 format inste…'
complete -c 'openssl-genrsa.1ossl' -o rand -o writerand -d 'X Item "-rand files, -writerand file" See "Random State Options" in openssl\\|…'
complete -c 'openssl-genrsa.1ossl' -o engine -d 'X Item "-engine id" See "Engine Options" in openssl\\|(1)'
complete -c 'openssl-genrsa.1ossl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-genrsa.1ossl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-genrsa.1ossl' -o propquery -d 'X Item "-propquery propq" '

