# openssl-gendsa.1ossl
# Autogenerated from man page /usr/share/man/man1/openssl-gendsa.1ossl.gz
complete -c 'openssl-gendsa.1ossl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-gendsa.1ossl' -o out -d 'X Item "-out filename" Output the key to the specified file'
complete -c 'openssl-gendsa.1ossl' -o passout -d 'X Item "-passout arg" The passphrase used for the output file'
complete -c 'openssl-gendsa.1ossl' -o aes128 -o aes192 -o aes256 -o aria128 -o aria192 -o aria256 -o camellia128 -o camellia192 -o camellia256 -o des -o des3 -o idea -d 'X Item "-aes128, -aes192, -aes256, -aria128, -aria192, -aria256, -camellia128…'
complete -c 'openssl-gendsa.1ossl' -o verbose -d 'X Item "-verbose" Print extra details about the operations being performed'
complete -c 'openssl-gendsa.1ossl' -o rand -o writerand -d 'X Item "-rand files, -writerand file" See "Random State Options" in openssl\\|…'
complete -c 'openssl-gendsa.1ossl' -o engine -d 'X Item "-engine id" See "Engine Options" in openssl\\|(1)'
complete -c 'openssl-gendsa.1ossl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-gendsa.1ossl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-gendsa.1ossl' -o propquery -d 'See "Provider Options" in openssl(1), provider(7), and property(7).  NOTES'

