# openssl.1ossl
# Autogenerated from man page /usr/share/man/man1/openssl.1ossl.gz
complete -c 'openssl.1ossl' -o help -d 'X Item "-help" Provides a terse summary of all options'
complete -c 'openssl.1ossl' -o rand -d 'X Item "-rand files" A file or files containing random data used to seed the …'
complete -c 'openssl.1ossl' -o writerand -d 'X Item "-writerand file" Writes the seed data to the specified file upon exit'
complete -c 'openssl.1ossl' -o ssl3 -o tls1 -o tls1_1 -o tls1_2 -o tls1_3 -o no_ssl3 -o no_tls1 -o no_tls1_1 -o no_tls1_2 -o no_tls1_3 -d 'X Item "-ssl3, -tls1, -tls1_1, -tls1_2, -tls1_3, -no_ssl3, -no_tls1, -no_tls1…'
complete -c 'openssl.1ossl' -o dtls -o dtls1 -o dtls1_2 -d 'X Item "-dtls, -dtls1, -dtls1_2" These options specify to use DTLS instead of…'
complete -c 'openssl.1ossl' -o engine -d 'X Item "-engine id" Load the engine identified by id and use all the methods …'
complete -c 'openssl.1ossl' -o provider -d 'X Item "-provider name" Load and initialize the provider identified by name'
complete -c 'openssl.1ossl' -o provider-path -d 'X Item "-provider-path path" Specifies the search path that is to be used for…'
complete -c 'openssl.1ossl' -o propquery

