# opensc-asn1
# Autogenerated from man page /usr/share/man/man1/opensc-asn1.1.gz
complete -c opensc-asn1 -l help -s h -d 'Print help and exit'
complete -c opensc-asn1 -l version -s V -d 'Print version and exit'

