# openssl-asn1parse.1ossl
# Autogenerated from man page /usr/share/man/man1/openssl-asn1parse.1ossl.gz
complete -c 'openssl-asn1parse.1ossl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-asn1parse.1ossl' -o inform -d 'X Item "-inform DER|PEM" The input format; the default is PEM'
complete -c 'openssl-asn1parse.1ossl' -o in -d 'X Item "-in filename" The input file, default is standard input'
complete -c 'openssl-asn1parse.1ossl' -o out -d 'X Item "-out filename" Output file to place the DER encoded data into'
complete -c 'openssl-asn1parse.1ossl' -o noout -d 'X Item "-noout" Don\'t output the parsed version of the input file'
complete -c 'openssl-asn1parse.1ossl' -o offset -d 'X Item "-offset number" Starting offset to begin parsing, default is start of…'
complete -c 'openssl-asn1parse.1ossl' -o length -d 'X Item "-length number" Number of bytes to parse, default is until end of file'
complete -c 'openssl-asn1parse.1ossl' -s i -d 'X Item "-i" Indents the output according to the "depth" of the structures'
complete -c 'openssl-asn1parse.1ossl' -o oid -d 'X Item "-oid filename" A file containing additional OBJECT IDENTIFIERs (OIDs)'
complete -c 'openssl-asn1parse.1ossl' -o dump -d 'X Item "-dump" Dump unknown data in hex format'
complete -c 'openssl-asn1parse.1ossl' -o dlimit -d 'X Item "-dlimit num" Like -dump, but only the first num bytes are output'
complete -c 'openssl-asn1parse.1ossl' -o strparse -d 'X Item "-strparse offset" Parse the contents octets of the ASN'
complete -c 'openssl-asn1parse.1ossl' -o genstr -o genconf -d 'X Item "-genstr string, -genconf file" Generate encoded data based on string,…'
complete -c 'openssl-asn1parse.1ossl' -o strictpem -d 'X Item "-strictpem" If this option is used then -inform will be ignored'
complete -c 'openssl-asn1parse.1ossl' -o item

