# opensc-explorer
# Autogenerated from man page /usr/share/man/man1/opensc-explorer.1.gz
complete -c opensc-explorer -l card-driver -s c -d 'Use the given card driver'
complete -c opensc-explorer -l mf -s m -d 'Select the file referenced by the given path on startup'
complete -c opensc-explorer -l reader -s r -d 'Number of the reader to use'
complete -c opensc-explorer -l verbose -s v -d 'Cause opensc-explorer to be more verbose'
complete -c opensc-explorer -l wait -s w -d 'Wait for a card to be inserted'

