# pam_console_apply
# Autogenerated from man page /usr/share/man/man8/pam_console_apply.8.gz
complete -c pam_console_apply -s c -d 'Load other console. perms file than the default one'
complete -c pam_console_apply -s f -d 'Load other fstab file than the default one (/etc/fstab)'
complete -c pam_console_apply -s r -d 'Signals pam_console_apply to reset permissions'
complete -c pam_console_apply -s t -d 'Use <tty> to match console class in console. perms file.  The default is tty0'
complete -c pam_console_apply -s s -d 'Write error messages to the system log instead of stderr'
complete -c pam_console_apply -s d -d 'Log/display messages useful for debugging'

