# patool
# Autogenerated from man page /usr/share/man/man1/patool.1.gz
complete -c patool -s v -l verbose -d 'Display more info about what patool does, and display the output of helper ap…'
complete -c patool -l non-interactive -d 'Try to prevent any interactive user input (ie'
complete -c patool -l outdir -d 'Extract to the given output directory'

