# permview
# Autogenerated from man page /usr/share/man/man1/permview.1.gz
complete -c permview -o output -d 'Output all declarative security attributes related informations into the spec…'
complete -c permview -o xml -l xml -d 'Output all declarative security attributes in an XML format'
complete -c permview -o decl -l decl -d 'Show declarative security attributes on classes and methods'
complete -c permview -s '?' -s h -d 'Display help informations about the permview tool'

