# perror
# Autogenerated from man page /usr/share/man/man1/perror.1.gz
complete -c perror -l help
complete -c perror -l info
complete -c perror -s I
complete -c perror -s '?'
complete -c perror -l silent
complete -c perror -s s
complete -c perror -l verbose
complete -c perror -s v
complete -c perror -l version
complete -c perror -s V

