# pinfo
# Autogenerated from man page /usr/share/man/man1/pinfo.1.gz
complete -c pinfo -s h
complete -c pinfo -l help
complete -c pinfo -s v
complete -c pinfo -l version
complete -c pinfo -s m
complete -c pinfo -l manual
complete -c pinfo -s r
complete -c pinfo -l raw-filename
complete -c pinfo -s f
complete -c pinfo -l file -d 'synonym for -r'
complete -c pinfo -s a
complete -c pinfo -l apropos
complete -c pinfo -s p
complete -c pinfo -l plain-apropos
complete -c pinfo -s c
complete -c pinfo -l cut-man-headers
complete -c pinfo -s s
complete -c pinfo -l squeeze-lines -d 'cut empty lines from manual pages'
complete -c pinfo -s d
complete -c pinfo -l dont-handle-without-tag-table
complete -c pinfo -s t
complete -c pinfo -l force-manual-tag-table -d 'forces manual detection of tag table'
complete -c pinfo -l node
complete -c pinfo -l rcfile
complete -c pinfo -l long-manual-links
complete -c pinfo -s l -d 'Use long link names in manuals'
complete -c pinfo -l clear-at-exit
complete -c pinfo -s x -d 'Clear screen at exit'

