# piv-tool
# Autogenerated from man page /usr/share/man/man1/piv-tool.1.gz
complete -c piv-tool -l serial -d 'Print the card serial number derived from the CHUID object, if any'
complete -c piv-tool -l name -s n -d 'Print the name of the inserted card (driver)'
complete -c piv-tool -l admin -s A -d 'Authenticate to the card using a 2DES, 3DES or AES key'
complete -c piv-tool -l genkey -s G -d 'Generate a key pair on the card and output the public key'
complete -c piv-tool -l object -s O -d 'Load an object onto the card'
complete -c piv-tool -l cert -s C -d 'Load a certificate onto the card.  ref is 9A, 9C, 9D or 9E'
complete -c piv-tool -l compresscert -s Z -d 'Load a certificate that has been gzipped onto the card'
complete -c piv-tool -l out -s o -d 'Output file for any operation that produces output'
complete -c piv-tool -l in -s i -d 'Input file for any operation that requires an input file'
complete -c piv-tool -l key-slots-discovery -d 'Print properties of the key slots.  Needs \\*(Aqadmin\\*(Aq authentication'
complete -c piv-tool -l send-apdu -s s -d 'Sends an arbitrary APDU to the card in the format AA:BB:CC:DD:EE:FF'
complete -c piv-tool -l reader -s r -d 'Number of the reader to use'
complete -c piv-tool -l wait -s w -d 'Wait for a card to be inserted'
complete -c piv-tool -l verbose -s v -d 'Causes piv-tool to be more verbose'

