# plasmapkg2
# Autogenerated from man page /usr/share/man/man1/plasmapkg2.1.gz
complete -c plasmapkg2 -l hash -d 'Generate a SHA1 hash for the package at \\(lqpath\\(rq'
complete -c plasmapkg2 -s g -l global -d 'For install or remove, operates on packages installed for all users'
complete -c plasmapkg2 -s t -l type -d 'The type of package, e. g'
complete -c plasmapkg2 -s i -l install -d 'Install the package at \\(lqpath\\(rq'
complete -c plasmapkg2 -s s -l show -d 'Show information of package \\(lqname\\(rq'
complete -c plasmapkg2 -s u -l upgrade -d 'Upgrade the package at \\(lqpath\\(rq'
complete -c plasmapkg2 -s l -l list -d 'List installed packages'
complete -c plasmapkg2 -l list-types -d 'Lists all known Package types that can be installed'
complete -c plasmapkg2 -s r -l remove -d 'Remove the package named \\(lqname\\(rq'
complete -c plasmapkg2 -s p -l packageroot -d 'Absolute path to the package root'

