# plocate-build
# Autogenerated from man page /usr/share/man/man8/plocate-build.8.gz
complete -c plocate-build -s b -l block-size -d 'Create blocks containing  SIZE filenames each, compress them together, and tr…'
complete -c plocate-build -s p -l plaintext -d 'Treat the input as plain text, with entries delimited by newlines, instead of…'
complete -c plocate-build -l help -d 'Print out usage information, then exit successfully'
complete -c plocate-build -l version -d 'Print out version information, then exit successfully'

