# POST
# Autogenerated from man page /usr/share/man/man1/POST.1.gz
complete -c POST -s m
complete -c POST -s f
complete -c POST -s b
complete -c POST -s t
complete -c POST -s i
complete -c POST -s c
complete -c POST -s p
complete -c POST -s P
complete -c POST -s H
complete -c POST -s C
complete -c POST -s u
complete -c POST -s U
complete -c POST -s s
complete -c POST -s S
complete -c POST -s e
complete -c POST -s E
complete -c POST -s d
complete -c POST -s o
complete -c POST -s v
complete -c POST -s h
complete -c POST -s a

