# pzstd
# Autogenerated from man page /usr/share/man/man1/pzstd.1.gz
complete -c pzstd -s z -l compress -d Compress
complete -c pzstd -s d -l decompress -l uncompress -d Decompress
complete -c pzstd -s t -l test -d 'Test the integrity of compressed files'
complete -c pzstd -o 'b#' -d 'Benchmark file(s) using compression level #'
complete -c pzstd -l train -d 'Use FILES as a training set to create a dictionary'

