# qemu-ga
# Autogenerated from man page /usr/share/man/man8/qemu-ga.8.gz
complete -c qemu-ga -s m -l method -d 'Transport method: one of unix-listen, virtio-serial, or isa-serial, or vsock-…'
complete -c qemu-ga -s p -l path -d 'Device/socket path (the default for virtio-serial is /dev/virtio-ports/org'
complete -c qemu-ga -s l -l logfile -d 'Set log file path (default is stderr)'
complete -c qemu-ga -s f -l pidfile -d 'Specify pid file (default is /var/run/qemu-ga. pid)'
complete -c qemu-ga -s F -l fsfreeze-hook -d 'Enable fsfreeze hook'
complete -c qemu-ga -s t -l statedir -d 'Specify the directory to store state information (absolute paths only, defaul…'
complete -c qemu-ga -s v -l verbose -d 'Log extra debugging information'
complete -c qemu-ga -s V -l version -d 'Print version information and exit'
complete -c qemu-ga -s d -l daemon -d 'Daemonize after startup (detach from terminal)'
complete -c qemu-ga -s b -l block-rpcs -d 'Comma-separated list of RPCs to disable (no spaces, use help to list availabl…'
complete -c qemu-ga -s D -l dump-conf -d 'Dump the configuration in a format compatible with qemu-ga. conf and exit'
complete -c qemu-ga -s h -l help -d 'Display this help and exit'
complete -c qemu-ga -o 'F/var/run/fsfreezehook.sh'

