# quotaon
# Autogenerated from man page /usr/share/man/man8/quotaon.8.gz
complete -c quotaon -s F -l format -d 'Report quota for specified format (ie.  don\'t perform format autodetection)'
complete -c quotaon -s a -l all -d 'All automatically mounted (no  noauto option) non-NFS filesystems in  /etc/fs…'
complete -c quotaon -s v -l verbose -d 'Display a message for each filesystem where quotas are turned on'
complete -c quotaon -s u -l user -d 'Manipulate user quotas.  This is the default'
complete -c quotaon -s g -l group -d 'Manipulate group quotas'
complete -c quotaon -s P -l project -d 'Manipulate project quotas'
complete -c quotaon -s p -l print-state -d 'Instead of turning quotas on just print state of quotas (ie.  whether'
complete -c quotaon -s x -l xfs-command -d 'Switch on limit enforcement for XFS filesystems'
complete -c quotaon -s f -l off -d 'Make  quotaon behave like being called as  quotaoff . SS quotaoff'

