# quotasync
# Autogenerated from man page /usr/share/man/man1/quotasync.1.gz
complete -c quotasync -s u -l user -d 'Synchronize user usage and limits'
complete -c quotasync -s g -l group -d 'Synchronize group usage and limits'
complete -c quotasync -s P -l project -d 'Synchronize project usage and limits'
complete -c quotasync -s a -l all -d 'Synchronize usage and limits on all file systems'
complete -c quotasync -s V -l version -d 'Show program version information and exit'
complete -c quotasync -s h -l help -d 'Show program usage and exit'

