# realm
# Autogenerated from man page /usr/share/man/man8/realm.8.gz
complete -c realm -s i -l install
complete -c realm -l unattended
complete -c realm -s v -l verbose
complete -c realm -s a -l all
complete -c realm -l client-software
complete -c realm -s n -l name
complete -c realm -l server-software
complete -c realm -l membership-software
complete -c realm -l use-ldaps
complete -c realm -l user -d 'is explicitly specified, an automatic join is attempted first'
complete -c realm -l no-password
complete -c realm -l one-time-password -d 'options are mutually exclusive.  At most one of them can be specified'
complete -c realm -l automatic-id-mapping
complete -c realm -l computer-ou
complete -c realm -l computer-name
complete -c realm -l os-name
complete -c realm -l os-version
complete -c realm -s U
complete -c realm -l user-principal
complete -c realm -l do-not-touch-config
complete -c realm -l remove
complete -c realm -l name-only
complete -c realm -l groups -s g
complete -c realm -l realm -s R
complete -c realm -l withdraw -s x

