# regdiff
# Autogenerated from man page /usr/share/man/man1/regdiff.1.gz
complete -c regdiff -l help -d 'Show list of available options'
complete -c regdiff -l backend -d 'Name of backend to load.  Possible values are: creg, regf, dir and rpc'
complete -c regdiff -l credentials -d 'Credentials to use, if any'

