# regedit
# Autogenerated from man page /usr/share/man/man1/regedit.1.gz
complete -c regedit -o Dregpath -d 'Deletes the specified registry key'
complete -c regedit -s S -d 'Run regedit silently (ignored, CLI mode is always silent)'
complete -c regedit -s V -d 'Run regedit in advanced mode (ignored)'
complete -c regedit -o Llocation -d 'Specifies the location of the system. dat registry file (ignored)'
complete -c regedit -o Rlocation -d 'Specifies the location of the user. dat registry file (ignored)'
complete -c regedit -s '?' -d 'Prints a help message.  Any other options are ignored'

