# regpatch
# Autogenerated from man page /usr/share/man/man1/regpatch.1.gz
complete -c regpatch -l help -d 'Show list of available options'
complete -c regpatch -l backend -d 'Name of backend to load.  Possible values are: creg, regf, dir and rpc'
complete -c regpatch -l credentials -d 'Credentials to use, if any'

