# regshell
# Autogenerated from man page /usr/share/man/man1/regshell.1.gz
complete -c regshell -l help -d 'Show list of available options'
complete -c regshell -l backend -d 'Name of backend to load.  Possible values are: creg, regf, dir and rpc'
complete -c regshell -l credentials -d 'Credentials to use, if any'

