# regtree
# Autogenerated from man page /usr/share/man/man1/regtree.1.gz
complete -c regtree -l help -d 'Show list of available options'
complete -c regtree -l backend -d 'Name of backend to load.  Possible values are: creg, regf, dir and rpc'
complete -c regtree -l credentials -d 'Credentials to use, if any'
complete -c regtree -l fullpath -d 'Print the full path to each key instead of only its name'
complete -c regtree -l no-values -d 'Don\\*(Aqt print values, just keys'

