# report-cli
# Autogenerated from man page /usr/share/man/man1/report-cli.1.gz
complete -c report-cli -s L -d 'List possible events [which start with PREFIX]'
complete -c report-cli -s e -d 'Run EVENT on PROBLEM_DIR'
complete -c report-cli -s a -l analyze -d 'Run analyze event(s) on PROBLEM_DIR'
complete -c report-cli -s c -l collect -d 'Run collect event(s) on PROBLEM_DIR'
complete -c report-cli -s r -l report -d 'Analyze, collect and report problem data in PROBLEM_DIR'
complete -c report-cli -s d -l delete -d 'Remove PROBLEM_DIR after reporting'
complete -c report-cli -s y -l always -d 'Noninteractive: don\'t ask questions, assume positive answer to all of them'
complete -c report-cli -s o -l report-only -d 'With -r: do not run analyzers, run only reporters'
complete -c report-cli -s v -l verbose -d 'Be verbose'
complete -c report-cli -s s -d 'Log to syslog'
complete -c report-cli -s p -d 'Add program names to log'
complete -c report-cli -s V -l version -d 'Display version and exit'

