# report-gtk
# Autogenerated from man page /usr/share/man/man1/report-gtk.1.gz
complete -c report-gtk -s d -l delete -d 'Remove PROBLEM_DIR after reporting'
complete -c report-gtk -s e -d 'Run only theset EVENTs on PROBLEM_DIR'
complete -c report-gtk -s g -d 'Alternate GUI file'
complete -c report-gtk -s p -d 'Add program names to log'
complete -c report-gtk -s v -l verbose -d 'Be verbose'
complete -c report-gtk -s V -l version -d 'Display version and exit'
complete -c report-gtk -s x -l expert -d 'Enabled advanced features'

