# reporter-upload
# Autogenerated from man page /usr/share/man/man1/reporter-upload.1.gz
complete -c reporter-upload -s d -d 'Path to problem directory'
complete -c reporter-upload -s c -d 'Path to configuration file'
complete -c reporter-upload -s u -d 'The URL where tarball should be uploaded'
complete -c reporter-upload -s b -l pubkey -d 'Set SSH public key file'
complete -c reporter-upload -s r -l key -d 'Set SSH private key file'

