# reporter-systemd-journal
# Autogenerated from man page /usr/share/man/man1/reporter-systemd-journal.1.gz
complete -c reporter-systemd-journal -s d -d 'Path to problem directory'
complete -c reporter-systemd-journal -s m -l message-id -d 'Catalog message id'
complete -c reporter-systemd-journal -s F -d 'Formatting file for systemd journal catalog message'
complete -c reporter-systemd-journal -s p -l dump -d 'Defines how much detailed the report will be'
complete -c reporter-systemd-journal -s s -l syslog-id -d 'Define SYSLOD_IDENTIFIER systemd journal field'
complete -c reporter-systemd-journal -s v -d 'Be more verbose.  Can be given multiple times'

