# reporter-kerneloops
# Autogenerated from man page /usr/share/man/man1/reporter-kerneloops.1.gz
complete -c reporter-kerneloops -s v -d 'Be more verbose.  Can be given multiple times'
complete -c reporter-kerneloops -s d -d 'Path to problem directory'
complete -c reporter-kerneloops -s c -d 'Path to configuration file'

