# reporter-print
# Autogenerated from man page /usr/share/man/man1/reporter-print.1.gz
complete -c reporter-print -s d -d 'Path to problem directory'
complete -c reporter-print -s v -d 'Be more verbose.  Can be given multiple times'
complete -c reporter-print -s o -d 'Output file'
complete -c reporter-print -s a -d 'If -o FILE is specified, controls whether FILE is appended to, or overwritten'
complete -c reporter-print -s r -d 'Add a record to reported_to in DIR which specifies that this problem was repo…'

