# resolve_stack_dump
# Autogenerated from man page /usr/share/man/man1/resolve_stack_dump.1.gz
complete -c resolve_stack_dump -l help
complete -c resolve_stack_dump -s h
complete -c resolve_stack_dump -l numeric-dump-file
complete -c resolve_stack_dump -s n
complete -c resolve_stack_dump -l symbols-file
complete -c resolve_stack_dump -s s
complete -c resolve_stack_dump -l version
complete -c resolve_stack_dump -s V

