# resolveip
# Autogenerated from man page /usr/share/man/man1/resolveip.1.gz
complete -c resolveip -l help
complete -c resolveip -l info
complete -c resolveip -s '?'
complete -c resolveip -s I
complete -c resolveip -l silent
complete -c resolveip -s s
complete -c resolveip -l version
complete -c resolveip -s V

