# rmiregistry-java-17-openjdk-17.0.7.0.7-5.fc38.x86_64
# Autogenerated from man page /usr/share/man/man1/rmiregistry-java-17-openjdk-17.0.7.0.7-5.fc38.x86_64.1.gz
complete -c 'rmiregistry-java-17-openjdk-17.0.7.0.7-5.fc38.x86_64' -o Joption -d 'Used with any Java option to pass the option following the'
complete -c 'rmiregistry-java-17-openjdk-17.0.7.0.7-5.fc38.x86_64' -s J -s J -d 'Java interpreter'

