# rpmargs
# Autogenerated from man page /usr/share/man/man1/rpmargs.1.gz
complete -c rpmargs -s a -d 'X Item "-a" Process all Sisyphus packages'
complete -c rpmargs -s p -d 'X Item "-p" When processing a directory, list package names, not file names; …'
complete -c rpmargs -s h

