# rpmdev-packager
# Autogenerated from man page /usr/share/man/man1/rpmdev-packager.1.gz
complete -c rpmdev-packager -s h -l help -d 'Show help message and exit'
complete -c rpmdev-packager -s v -l version -d 'Print version information and exit'

