# rpmdev-newspec
# Autogenerated from man page /usr/share/man/man1/rpmdev-newspec.1.gz
complete -c rpmdev-newspec -s m -l macros -d 'Emit templates using macros instead of shell style variables'
complete -c rpmdev-newspec -s h -l help -d 'Show this usage message and exit'
complete -c rpmdev-newspec -s o -l output -d 'Output the specfile to FILE.  "-" means stdout'
complete -c rpmdev-newspec -s t -l type -d 'Force use of the TYPE spec template'
complete -c rpmdev-newspec -s D -l legacy-datestamp -d 'Use use legacy datestamp for changelog entries'
complete -c rpmdev-newspec -s r -l rpm-version -d 'Filter out some spec file constructs not needed by the specified rpm(build) v…'
complete -c rpmdev-newspec -s v -l version -d 'Print version information and exit'

