# rpmdeps
# Autogenerated from man page /usr/share/man/man8/rpmdeps.8.gz
complete -c rpmdeps -l 'provides\\f' -d 'Print the provides'
complete -c rpmdeps -l 'requires\\f' -d 'Print the requires'
complete -c rpmdeps -s P -l provides -d 'Print the provides'
complete -c rpmdeps -s R -l requires -d 'Print the requires'
complete -c rpmdeps -l recommends -d 'Print the recommends'
complete -c rpmdeps -l suggests -d 'Print the suggests'
complete -c rpmdeps -l supplements -d 'Print the supplements'
complete -c rpmdeps -l enhances -d 'Print the enhances'
complete -c rpmdeps -l conflicts -d 'Print the conflicts'
complete -c rpmdeps -l obsoletes -d 'Print the obsoletes'
complete -c rpmdeps -l alldeps -d 'Print all the dependencies SEE ALSO'

