# rpmdev-rmdevelrpms
# Autogenerated from man page /usr/share/man/man8/rpmdev-rmdevelrpms.8.gz
complete -c rpmdev-rmdevelrpms -s h -l help -d 'show this help message and exit'
complete -c rpmdev-rmdevelrpms -s l -l list-only -d 'Output condensed list of packages, do not remove'
complete -c rpmdev-rmdevelrpms -l qf -l queryformat -d 'Query format to use for output'
complete -c rpmdev-rmdevelrpms -s y -l yes -d 'Root only: remove without prompting; ignored with -l'
complete -c rpmdev-rmdevelrpms -s v -l version -d 'Print program version and exit'

