# rpmdev-bumpspec
# Autogenerated from man page /usr/share/man/man1/rpmdev-bumpspec.1.gz
complete -c rpmdev-bumpspec -s h -l help -d 'show this help message and exit'
complete -c rpmdev-bumpspec -s c -l comment -d 'changelog comment (default: "- rebuilt")'
complete -c rpmdev-bumpspec -s f -l file -d 'take changelog comment from the given file'
complete -c rpmdev-bumpspec -s u -l userstring -d 'user name+email string (default: output from rpmdev-packager(1))'
complete -c rpmdev-bumpspec -s r -l rightmost -d 'bump trailing . <DIGIT> component if found, append '
complete -c rpmdev-bumpspec -s s -l string -d 'bump trailing . STRING<DIGIT> component if found, append '
complete -c rpmdev-bumpspec -s n -l new -d 'set new version and reset/set release (simple spec files only)'
complete -c rpmdev-bumpspec -s D -l legacy-datestamp -d 'use legacy datestamp for changelog entries'
complete -c rpmdev-bumpspec -s d -l datestamp -d 'changelog date string (default: today)'
complete -c rpmdev-bumpspec -s V -l verbose -d 'more output'
complete -c rpmdev-bumpspec -s v -l version -d 'output version number and exit COPYRIGHT Copyright © 2005-2014 Fedora Project…'

