# rpmdev-diff
# Autogenerated from man page /usr/share/man/man1/rpmdev-diff.1.gz
complete -c rpmdev-diff -s c -l contents -d 'Diff contents of files in archives.   This is the default'
complete -c rpmdev-diff -s l -l list -d 'Diff lists of files in archives'
complete -c rpmdev-diff -s L -l long-list -d 'Diff long lists (akin to \'find -ls\') of files in archives'
complete -c rpmdev-diff -s m -l metadata -d 'Diff archive metadata (only implemented for rpms for now)'
complete -c rpmdev-diff -s h -l help -d 'Print help message and exit'
complete -c rpmdev-diff -s v -l version -d 'Print version information and exit'

