# rpmdev-extract
# Autogenerated from man page /usr/share/man/man1/rpmdev-extract.1.gz
complete -c rpmdev-extract -s q -d 'Suppress output'
complete -c rpmdev-extract -s f -d 'Force overwriting existing files'
complete -c rpmdev-extract -s C -d 'Change to directory DIR before extracting'
complete -c rpmdev-extract -s h -d 'Print help message and exit'
complete -c rpmdev-extract -s v -d 'Print version information and exit'

