# rpmdev-newinit
# Autogenerated from man page /usr/share/man/man1/rpmdev-newinit.1.gz
complete -c rpmdev-newinit -s o -d 'Output the init script to FILE.   "-" means stdout'
complete -c rpmdev-newinit -s h -d 'Show this usage message and exit'
complete -c rpmdev-newinit -s v -d 'Print version information and exit'

