# rpmelfsym
# Autogenerated from man page /usr/share/man/man1/rpmelfsym.1.gz
complete -c rpmelfsym -s a -d 'X Item "-a" Process all Sisyphus packages'
complete -c rpmelfsym -s p -d 'X Item "-p" When processing a directory, list package names, not file names; …'
complete -c rpmelfsym -s h

