# rpmfile
# Autogenerated from man page /usr/share/man/man1/rpmfile.1.gz
complete -c rpmfile -s a -d 'X Item "-a" Process all Sisyphus packages'
complete -c rpmfile -s p -d 'X Item "-p" When processing a directory, list package names, not file names; …'
complete -c rpmfile -s h

