# rpmlua
# Autogenerated from man page /usr/share/man/man8/rpmlua.8.gz
complete -c rpmlua -l 'interactive\\f' -d 'Run an interactive session after executing optional script or statement'
complete -c rpmlua -s i -l interactive -d 'Run an interactive session after executing optional script or statement'
complete -c rpmlua -s e -l execute -d 'Execute a Lua statement before executing optional script.  EXAMPLES'

