# rpmspec
# Autogenerated from man page /usr/share/man/man8/rpmspec.8.gz
complete -c rpmspec -l qf -l queryformat
complete -c rpmspec -l rpms -d 'from spec'
complete -c rpmspec -l builtrpms -d 'packages which would be built from spec'
complete -c rpmspec -l srpm -d 'spec.  EXAMPLES'

