# rzip
# Autogenerated from man page /usr/share/man/man1/rzip.1.gz
complete -c rzip -s h -d 'Print an options summary page'
complete -c rzip -s V -d 'Print the rzip version number'
complete -c rzip -o '0..9' -d 'Set the compression level from 0 to 9'
complete -c rzip -s d -d Decompress
complete -c rzip -s o -d 'Set the output file name'
complete -c rzip -s S -d 'Set the compression suffix.  The default is \'. rz\''
complete -c rzip -s f -d 'If this option is not specified then rzip will not overwrite any existing fil…'
complete -c rzip -s k -d 'If this option is not specified then rzip will delete the source file after s…'
complete -c rzip -s P -d 'If this option is specified then rzip will show the percentage progress while…'

