# saslauthd
# Autogenerated from man page /usr/share/man/man8/saslauthd.8.gz
complete -c saslauthd -s a -d 'Use authmech as the authentication mechanism'
complete -c saslauthd -s O -d 'A mechanism specific option (e. g.  rimap hostname or config file path)'
complete -c saslauthd -s H -d 'The remote host to be contacted by the rimap authentication mechanism'
complete -c saslauthd -s m -d 'Use path as the pathname to the named socket to listen on for connection requ…'
complete -c saslauthd -s n -d 'Use threads processes for responding to authentication queries'
complete -c saslauthd -s s -d 'Use size as the table size of the hash table (in kilobytes)'
complete -c saslauthd -s t -d 'Use timeout as the expiration time of the authentication cache (in seconds)'
complete -c saslauthd -s T -d 'Honour time-of-day login restrictions'
complete -c saslauthd -s h -d 'Show usage information'
complete -c saslauthd -s c -d 'Enable caching of authentication credentials'
complete -c saslauthd -s l -d 'Disable the use of a lock file for controlling access to accept()'
complete -c saslauthd -s r -d 'Combine the realm with the login (with an \'@\' sign in between).   e. g'
complete -c saslauthd -s v -d 'Print the version number and available authentication mechanisms on standard …'
complete -c saslauthd -s d -d 'Debugging mode'

