# secutil
# Autogenerated from man page /usr/share/man/man1/secutil.1.gz
complete -c secutil -s s -o strongname -d 'Display strongname informations about the assembly'
complete -c secutil -s x -o x509certificate -d 'Display the X509 Authenticode certificate for the assembly'
complete -c secutil -s a -o array -d 'Display data in a decimal array (default)'
complete -c secutil -s v -o vbmode -d 'Display data in a VisualBasic friendly format'
complete -c secutil -s c -o cmode -d 'Display data in a C/C++/C# friendly format (default)'
complete -c secutil -o help -s h -s '?' -d 'Display help about this tool'

