# semanage-fcontext
# Autogenerated from man page /usr/share/man/man8/semanage-fcontext.8.gz
complete -c semanage-fcontext -s h -l help -d 'show this help message and exit'
complete -c semanage-fcontext -s n -l noheading -d 'Do not print heading when listing the specified object type'
complete -c semanage-fcontext -s N -l noreload -d 'Do not reload policy after commit'
complete -c semanage-fcontext -s C -l locallist -d 'List local customizations'
complete -c semanage-fcontext -s S -l store -d 'Select an alternate SELinux Policy Store to manage'
complete -c semanage-fcontext -s a -l add -d 'Add a record of the specified object type'
complete -c semanage-fcontext -s d -l delete -d 'Delete a record of the specified object type'
complete -c semanage-fcontext -s m -l modify -d 'Modify a record of the specified object type'
complete -c semanage-fcontext -s l -l list -d 'List records of the specified object type'
complete -c semanage-fcontext -s E -l extract -d 'Extract customizable commands, for use within a transaction'
complete -c semanage-fcontext -s D -l deleteall -d 'Remove all local customizations'
complete -c semanage-fcontext -s e -l equal -d 'Substitute target path with sourcepath when generating default label'
complete -c semanage-fcontext -s f -l ftype -d 'File Type.  This is used with fcontext'
complete -c semanage-fcontext -s s -l seuser -d 'SELinux user name'
complete -c semanage-fcontext -s t -l type -d 'SELinux Type for the object'

