# semanage-export
# Autogenerated from man page /usr/share/man/man8/semanage-export.8.gz
complete -c semanage-export -s h -l help -d 'show this help message and exit'
complete -c semanage-export -s S -l store -d 'Select an alternate SELinux Policy Store to manage'

