# semanage-boolean
# Autogenerated from man page /usr/share/man/man8/semanage-boolean.8.gz
complete -c semanage-boolean -s h -l help -d 'show this help message and exit'
complete -c semanage-boolean -s n -l noheading -d 'Do not print heading when listing the specified object type'
complete -c semanage-boolean -s N -l noreload -d 'Do not reload policy after commit'
complete -c semanage-boolean -s S -l store -d 'Select an alternate SELinux Policy Store to manage'
complete -c semanage-boolean -s C -l locallist -d 'List local customizations'
complete -c semanage-boolean -s m -l modify -d 'Modify a record of the specified object type'
complete -c semanage-boolean -s l -l list -d 'List records of the specified object type'
complete -c semanage-boolean -s E -l extract -d 'Extract customizable commands, for use within a transaction'
complete -c semanage-boolean -s D -l deleteall -d 'Remove all local customizations'
complete -c semanage-boolean -s 1 -l on -d 'Enable the boolean'

