# semanage-node
# Autogenerated from man page /usr/share/man/man8/semanage-node.8.gz
complete -c semanage-node -s h -l help -d 'show this help message and exit'
complete -c semanage-node -s n -l noheading -d 'Do not print heading when listing the specified object type'
complete -c semanage-node -s N -l noreload -d 'Do not reload policy after commit'
complete -c semanage-node -s S -l store -d 'Select an alternate SELinux Policy Store to manage'
complete -c semanage-node -s C -l locallist -d 'List local customizations'
complete -c semanage-node -s a -l add -d 'Add a record of the specified object type'
complete -c semanage-node -s d -l delete -d 'Delete a record of the specified object type'
complete -c semanage-node -s m -l modify -d 'Modify a record of the specified object type'
complete -c semanage-node -s l -l list -d 'List records of the specified object type'
complete -c semanage-node -s E -l extract -d 'Extract customizable commands, for use within a transaction'
complete -c semanage-node -s D -l deleteall -d 'Remove all local customizations'
complete -c semanage-node -s M -l netmask -d 'Network Mask, either in CIDR (/16) or address mask notation (255. 255. 0'
complete -c semanage-node -s t -l type -d 'SELinux type for the object'
complete -c semanage-node -s r -l range -d 'MLS/MCS Security Range (MLS/MCS Systems only) SELinux Range for SELinux login…'

