# semanage-port
# Autogenerated from man page /usr/share/man/man8/semanage-port.8.gz
complete -c semanage-port -s h -l help -d 'show this help message and exit'
complete -c semanage-port -s n -l noheading -d 'Do not print heading when listing the specified object type'
complete -c semanage-port -s N -l noreload -d 'Do not reload policy after commit'
complete -c semanage-port -s S -l store -d 'Select an alternate SELinux Policy Store to manage'
complete -c semanage-port -s C -l locallist -d 'List local customizations'
complete -c semanage-port -s a -l add -d 'Add a record of the specified object type'
complete -c semanage-port -s d -l delete -d 'Delete a record of the specified object type'
complete -c semanage-port -s m -l modify -d 'Modify a record of the specified object type'
complete -c semanage-port -s l -l list -d 'List records of the specified object type'
complete -c semanage-port -s E -l extract -d 'Extract customizable commands, for use within a transaction'
complete -c semanage-port -s D -l deleteall -d 'Remove all local customizations'
complete -c semanage-port -s t -l type -d 'SELinux type for the object'
complete -c semanage-port -s r -l range -d 'MLS/MCS Security Range (MLS/MCS Systems only) SELinux Range for SELinux login…'

