# semanage-module
# Autogenerated from man page /usr/share/man/man8/semanage-module.8.gz
complete -c semanage-module -s h -l help -d 'show this help message and exit'
complete -c semanage-module -s n -l noheading -d 'Do not print heading when listing the specified object type'
complete -c semanage-module -s N -l noreload -d 'Do not reload policy after commit'
complete -c semanage-module -s S -l store -d 'Select an alternate SELinux Policy Store to manage'
complete -c semanage-module -s a -l add -d 'Install specified module'
complete -c semanage-module -s r -l remove -d 'Remove specified module'
complete -c semanage-module -s d -l disable -d 'Disable specified module'
complete -c semanage-module -s e -l enable -d 'Enable specified module'
complete -c semanage-module -s E -l extract -d 'Extract customizable commands, for use within a transaction'
complete -c semanage-module -s l -l list -d 'List records of the specified object type'

