# semanage-permissive
# Autogenerated from man page /usr/share/man/man8/semanage-permissive.8.gz
complete -c semanage-permissive -s h -l help -d 'show this help message and exit'
complete -c semanage-permissive -s a -l add -d 'Add a record of the specified object type'
complete -c semanage-permissive -s d -l delete -d 'Delete a record of the specified object type'
complete -c semanage-permissive -s D -l deleteall -d 'Remove all local customizations of permissive domains'
complete -c semanage-permissive -s l -l list -d 'List records of the specified object type'
complete -c semanage-permissive -s E -l extract -d 'Extract customizable commands, for use within a transaction'
complete -c semanage-permissive -s n -l noheading -d 'Do not print heading when listing the specified object type'
complete -c semanage-permissive -s N -l noreload -d 'Do not reload the policy after commit'

