# semanage-user
# Autogenerated from man page /usr/share/man/man8/semanage-user.8.gz
complete -c semanage-user -s h -l help -d 'show this help message and exit'
complete -c semanage-user -s n -l noheading -d 'Do not print heading when listing the specified object type'
complete -c semanage-user -s N -l noreload -d 'Do not reload policy after commit'
complete -c semanage-user -s S -l store -d 'Select an alternate SELinux Policy Store to manage'
complete -c semanage-user -s C -l locallist -d 'List local customizations'
complete -c semanage-user -s a -l add -d 'Add a record of the specified object type'
complete -c semanage-user -s d -l delete -d 'Delete a record of the specified object type'
complete -c semanage-user -s m -l modify -d 'Modify a record of the specified object type'
complete -c semanage-user -s l -l list -d 'List records of the specified object type'
complete -c semanage-user -s E -l extract -d 'Extract customizable commands, for use within a transaction'
complete -c semanage-user -s D -l deleteall -d 'Remove all local customizations'
complete -c semanage-user -s L -l level -d 'Default SELinux Level for SELinux user, s0 Default.  (MLS/MCS Systems only)'
complete -c semanage-user -s r -l range -d 'MLS/MCS Security Range (MLS/MCS Systems only) SELinux Range for SELinux login…'

