# semanage-login
# Autogenerated from man page /usr/share/man/man8/semanage-login.8.gz
complete -c semanage-login -s h -l help -d 'show this help message and exit'
complete -c semanage-login -s n -l noheading -d 'Do not print heading when listing the specified object type'
complete -c semanage-login -s N -l noreload -d 'Do not reload policy after commit'
complete -c semanage-login -s C -l locallist -d 'List local customizations'
complete -c semanage-login -s S -l store -d 'Select an alternate SELinux Policy Store to manage'
complete -c semanage-login -s a -l add -d 'Add a record of the specified object type'
complete -c semanage-login -s d -l delete -d 'Delete a record of the specified object type'
complete -c semanage-login -s m -l modify -d 'Modify a record of the specified object type'
complete -c semanage-login -s l -l list -d 'List records of the specified object type'
complete -c semanage-login -s E -l extract -d 'Extract customizable commands, for use within a transaction'
complete -c semanage-login -s D -l deleteall -d 'Remove all local customizations'
complete -c semanage-login -s s -l seuser -d 'SELinux user name'

