# semanage-dontaudit
# Autogenerated from man page /usr/share/man/man8/semanage-dontaudit.8.gz
complete -c semanage-dontaudit -s h -l help -d 'show this help message and exit'
complete -c semanage-dontaudit -s S -l store -d 'Select an alternate SELinux Policy Store to manage'

