# semanage-interface
# Autogenerated from man page /usr/share/man/man8/semanage-interface.8.gz
complete -c semanage-interface -s h -l help -d 'show this help message and exit'
complete -c semanage-interface -s n -l noheading -d 'Do not print heading when listing the specified object type'
complete -c semanage-interface -s N -l noreload -d 'Do not reload policy after commit'
complete -c semanage-interface -s S -l store -d 'Select an alternate SELinux Policy Store to manage'
complete -c semanage-interface -s C -l locallist -d 'List local customizations'
complete -c semanage-interface -s a -l add -d 'Add a record of the specified object type'
complete -c semanage-interface -s d -l delete -d 'Delete a record of the specified object type'
complete -c semanage-interface -s m -l modify -d 'Modify a record of the specified object type'
complete -c semanage-interface -s l -l list -d 'List records of the specified object type'
complete -c semanage-interface -s E -l extract -d 'Extract customizable commands, for use within a transaction'
complete -c semanage-interface -s D -l deleteall -d 'Remove all local customizations'
complete -c semanage-interface -s t -l type -d 'SELinux type for the object'

