# semanage-import
# Autogenerated from man page /usr/share/man/man8/semanage-import.8.gz
complete -c semanage-import -s h -l help -d 'show this help message and exit'
complete -c semanage-import -s N -l noreload -d 'Do not reload policy after commit'
complete -c semanage-import -s S -l store -d 'Select an alternate SELinux Policy Store to manage'

