# setquota
# Autogenerated from man page /usr/share/man/man8/setquota.8.gz
complete -c setquota -s r -l remote -d 'Edit also remote quota use rpc. rquotad on remote server to set quota'
complete -c setquota -s m -l no-mixed-pathnames -d 'Currently, pathnames of NFSv4 mountpoints are sent without leading slash in t…'
complete -c setquota -s F -l format -d 'Perform setting for specified format (ie'
complete -c setquota -s u -l user -d 'Set user quotas for named user.  This is the default'
complete -c setquota -s g -l group -d 'Set group quotas for named group'
complete -c setquota -s P -l project -d 'Set project quotas for named project'
complete -c setquota -s p -l prototype -d 'Use quota settings of user, group or project  protoname to set the quota for …'
complete -c setquota -l always-resolve -d 'Always try to translate user / group / project name to uid / gid / project ID…'
complete -c setquota -s b -l batch -d 'Read information to set from stdin (input format is  name block-softlimit blo…'
complete -c setquota -s c -l continue-batch -d 'If parsing of an input line in batch mode fails, continue with processing the…'
complete -c setquota -s t -l edit-period -d 'Set grace times for users/groups/projects'
complete -c setquota -s T -l edit-times -d 'Alter times for individual user/group/project when softlimit is enforced'
complete -c setquota -s a -l all -d 'Go through all filesystems with quota in /etc/mtab and perform setting'

