# sgen
# Autogenerated from man page /usr/share/man/man1/sgen.1.gz
complete -c sgen -l assembly -s a -d 'Specifies the assembly filename to process'
complete -c sgen -l type -s t -d 'Explicitly specifies the runtime type to process'
complete -c sgen -l reference -s r -d 'Specifies an assembly filename, which is referenced by the target assembly an…'
complete -c sgen -l compiler -s c -d 'Specifies compiler options'
complete -c sgen -l proxytypes -s p -d '(Not supported yet. )'
complete -c sgen -l debug -s d -d 'Indicates the compiler to generate debug information'
complete -c sgen -l keep -s k -d 'Indicates the compiler to keep generated temporary source files'
complete -c sgen -l force -s f -d 'Indicates the generator to force overwriting existing assembly'
complete -c sgen -l out -s o -d 'Specifies the output directory for resulting files'
complete -c sgen -l nologo -s n -d 'Indicates to not print the logo for this tool'
complete -c sgen -l silent -s s -d 'Indicates the tool to run silently'
complete -c sgen -l verbose -s v -d 'Indicates the tool to be more verbose on its progress'
complete -c sgen -l help -s '?' -d 'Display command line help.  FEATURES'

