# sgpio
# Autogenerated from man page /usr/share/man/man1/sgpio.1.gz
complete -c sgpio -s h -l help -d 'displays a short help text'
complete -c sgpio -s V -l version -d 'displays the utility and AHCI SGPIO specification'
complete -c sgpio -s d -l disk -d 'disk name of LED location.   Names are sda,sdb,sdc,'
complete -c sgpio -s p -l port -d 'SATA port number of LED location, can be used if a disk name is no  longer va…'
complete -c sgpio -s s -l status -d 'status of the LED to set.   LED status is: locate, fault, rebuild, off'
complete -c sgpio -s f -l freq -d 'Set the frequency at which the LED should blink (in Hz)'

