# shar
# Autogenerated from man page /usr/share/man/man1/shar.1.gz
complete -c shar -l whole-size-limit
complete -c shar -l input-file-list -d 'NOTE: THIS OPTION IS DEPRECATED Controlling the shar headers use name to docu…'
complete -c shar -l submitter
complete -c shar -l archive-name -d '(/) character, then the /part## is omitted.   Thus'
complete -c shar -s n
complete -c shar -l query-user -d 'overwrite pre-existing files.   In all cases, however, if'
complete -c shar -l cut-mark -d 'unpacking, then existing files will be overwritten unconditionally'
complete -c shar -l no-timestamp -l force-prefix -d 'get you occasional complaints.   Put these options into your ~/. sharrc file'

