# signcode
# Autogenerated from man page /usr/share/man/man1/signcode.1.gz
complete -c signcode -o spc -d 'The Software Publisher File (spc) that contains the X'
complete -c signcode -s v -d 'The Private Key File (pvk) that contains the private key used to digitally  s…'
complete -c signcode -s a -d 'The hash algorithm used in the digital signature of the PE executable'
complete -c signcode -s '$' -d 'Add information about the publisher, i. e'
complete -c signcode -s n -d 'Add a textual description of the signed file'
complete -c signcode -s i -d 'Add a URL associated to the publisher or the signed file'
complete -c signcode -s t -d 'URL to a timestamp service to countersign the PE executable'
complete -c signcode -o tr -d 'Number of retries to get a timestamp for the countersignature'
complete -c signcode -o tw -d 'Delay (in seconds) between the retries to get a timestamp for the countersign…'
complete -c signcode -s k -d 'CryptoAPI key container name (when not using -v)'
complete -c signcode -s p -d 'CryptoAPI provider name (when not using -v)'
complete -c signcode -s y -d 'CryptoAPI provider type (when not using -v or -p)'
complete -c signcode -o ky -d 'CryptoAPI key type (when not using -v)'
complete -c signcode -s r -d 'CryptoAPI key location (when not using -v)'
complete -c signcode -o help -s h -s '?' -d 'Display help about this tool'

