# soelim.groff
# Autogenerated from man page /usr/share/man/man1/soelim.groff.1.gz
complete -c 'soelim.groff' -s C -d 'Recognize  . so even when followed by a character other than space or newline'
complete -c 'soelim.groff' -s I -d 'This option may be used to add a directory to the search path for files (both…'
complete -c 'soelim.groff' -s r -d 'Do not add  . lf requests (for general use, with non-groff files)'
complete -c 'soelim.groff' -s t -d 'Don\'t emit  '
complete -c 'soelim.groff' -s s -d 'option of groff '
complete -c 'soelim.groff' -s v -d 'Print the version number'

