# spectacle
# Autogenerated from man page /usr/share/man/man1/spectacle.1.gz
complete -c spectacle -s f -l fullscreen
complete -c spectacle -s m -l current
complete -c spectacle -s a -l activewindow
complete -c spectacle -s u -l windowundercursor
complete -c spectacle -s t -l transientonly
complete -c spectacle -s r -l region
complete -c spectacle -s l -l launchonly
complete -c spectacle -s g -l gui
complete -c spectacle -s b -l background
complete -c spectacle -s s -l dbus
complete -c spectacle -s n -l nonotify
complete -c spectacle -s o -l output
complete -c spectacle -s d -l delay
complete -c spectacle -s c -l copy-image
complete -c spectacle -s C -l copy-path
complete -c spectacle -s w -l onclick
complete -c spectacle -s i -l new-instance
complete -c spectacle -l pointer
complete -c spectacle -s e -l no-decoration

