# sshpass
# Autogenerated from man page /usr/share/man/man1/sshpass.1.gz
complete -c sshpass -o ppassword -d 'The password is given on the command line'
complete -c sshpass -o ffilename -d 'The password is the first line of the file filename'
complete -c sshpass -o dnumber -d 'number is a file descriptor inherited by sshpass from the runner'
complete -c sshpass -s e -d 'The password is taken from the environment variable "SSHPASS"'
complete -c sshpass -s P -d 'Set the password prompt'
complete -c sshpass -s v -d 'Be verbose'

