# star_sym
# Autogenerated from man page /usr/share/man/man1/star_sym.1.gz
complete -c star_sym -o help -d 'Prints a short summary of the   star_sym (1) options and exists'
complete -c star_sym -o version -d 'Prints the  star_sym (1) version number string and exists'

