# start-stop-daemon
# Autogenerated from man page /usr/share/man/man8/start-stop-daemon.8.gz
complete -c start-stop-daemon -l pid -d 'X Item "--pid pid" Check for a process with the specified pid (since version 1'
complete -c start-stop-daemon -l ppid -d 'X Item "--ppid ppid" Check for a process with the specified parent pid ppid (…'
complete -c start-stop-daemon -s p -l pidfile -d 'X Item "-p, --pidfile pidfile" Check whether a process has created the file p…'
complete -c start-stop-daemon -s x -l exec -d 'X Item "-x, --exec executable" Check for processes that are instances of this…'
complete -c start-stop-daemon -s n -l name -d 'X Item "-n, --name process-name" Check for processes with the name process-na…'
complete -c start-stop-daemon -s u -l user -d 'X Item "-u, --user username|uid" Check for processes owned by the user specif…'
complete -c start-stop-daemon -s g -l group -d 'X Item "-g, --group group|gid" Change to group or gid when starting the proce…'
complete -c start-stop-daemon -s s -l signal -d 'X Item "-s, --signal signal" With --stop, specifies the signal to send to pro…'
complete -c start-stop-daemon -s R -l retry -d 'X Item "-R, --retry timeout|schedule" With --stop, specifies that start-stop-…'
complete -c start-stop-daemon -s a -l startas -d 'X Item "-a, --startas pathname" With --start, start the process specified by …'
complete -c start-stop-daemon -s t -l test -d 'X Item "-t, --test" Print actions that would be taken and set appropriate ret…'
complete -c start-stop-daemon -s o -l oknodo -d 'X Item "-o, --oknodo" Return exit status 0 instead of 1 if no actions are (wo…'
complete -c start-stop-daemon -s q -l quiet -d 'X Item "-q, --quiet" Do not print informational messages; only display error …'
complete -c start-stop-daemon -s c -l chuid -d 'X Item "-c, --chuid username|uid[:group|gid]" Change to this username/uid bef…'
complete -c start-stop-daemon -s r -l chroot -d 'X Item "-r, --chroot root" Change directory and chroot to root before startin…'
complete -c start-stop-daemon -s d -l chdir -d 'X Item "-d, --chdir path" Change directory to path before starting the process'
complete -c start-stop-daemon -s b -l background -d 'X Item "-b, --background" Typically used with programs that don\'t detach on t…'
complete -c start-stop-daemon -l notify-await -d 'X Item "--notify-await" Wait for the background process to send a readiness n…'
complete -c start-stop-daemon -l notify-timeout -d 'X Item "--notify-timeout timeout" Set a timeout for the --notify-await option…'
complete -c start-stop-daemon -s C -l no-close -d 'X Item "-C, --no-close" Do not close any file descriptor when forcing the dae…'
complete -c start-stop-daemon -s O -l output -d 'X Item "-O, --output pathname" Redirect stdout and stderr to pathname when fo…'
complete -c start-stop-daemon -s N -l nicelevel -d 'X Item "-N, --nicelevel int" This alters the priority of the process before s…'
complete -c start-stop-daemon -s P -l procsched -d 'X Item "-P, --procsched policy:priority" This alters the process scheduler po…'
complete -c start-stop-daemon -s I -l iosched -d 'X Item "-I, --iosched class:priority" This alters the IO scheduler class and …'
complete -c start-stop-daemon -s k -l umask -d 'X Item "-k, --umask mask" This sets the umask of the process before starting …'
complete -c start-stop-daemon -s m -l make-pidfile -d 'X Item "-m, --make-pidfile" Used when starting a program that does not create…'
complete -c start-stop-daemon -l remove-pidfile -d 'X Item "--remove-pidfile" Used when stopping a program that does not remove i…'
complete -c start-stop-daemon -l start -d 'from starting the daemon'
complete -c start-stop-daemon -l stop -d 'is specified'
complete -c start-stop-daemon -s S
complete -c start-stop-daemon -s K
complete -c start-stop-daemon -s T -l status
complete -c start-stop-daemon -s H -l help
complete -c start-stop-daemon -s V -l version
complete -c start-stop-daemon -o signal-number -d 'or [-]signal-name, which means to send that signal, or timeout, which means t…'
complete -c start-stop-daemon -s v -l verbose

