# streamzip
# Autogenerated from man page /usr/share/man/man1/streamzip.1.gz
complete -c streamzip -o zip64
complete -c streamzip -o zipfile
complete -c streamzip -o member-name
complete -c streamzip -o stream
complete -c streamzip -o method
complete -c streamzip -s 0 -s 1 -s 2 -s 3 -s 4 -s 5 -s 6 -s 7 -s 8 -s 9
complete -c streamzip -o version
complete -c streamzip -o help

