# swtpm
# Autogenerated from man page /usr/share/man/man8/swtpm.8.gz
complete -c swtpm -s p -l port
complete -c swtpm -s t -l terminate
complete -c swtpm -l server
complete -c swtpm -s c -l chardev
complete -c swtpm -l vtpm-proxy
complete -c swtpm -s n -l name
complete -c swtpm -s M -l maj
complete -c swtpm -s m -l min
complete -c swtpm -s f -l fd
complete -c swtpm -s d -l daemon
complete -c swtpm -l ctrl
complete -c swtpm -l tpmstate
complete -c swtpm -l tpm2
complete -c swtpm -l log
complete -c swtpm -l locality
complete -c swtpm -l key
complete -c swtpm -l migration-key
complete -c swtpm -l pid
complete -c swtpm -s r -l runas
complete -c swtpm -s R -l chroot
complete -c swtpm -l seccomp
complete -c swtpm -l flags
complete -c swtpm -l print-capabilities
complete -c swtpm -l print-states
complete -c swtpm -l migration
complete -c swtpm -s h -l help

