# swtpm_localca
# Autogenerated from man page /usr/share/man/man8/swtpm_localca.8.gz
complete -c swtpm_localca -l type
complete -c swtpm_localca -l dir
complete -c swtpm_localca -l ek
complete -c swtpm_localca -l vmid
complete -c swtpm_localca -l logfile
complete -c swtpm_localca -l configfile
complete -c swtpm_localca -l optsfile
complete -c swtpm_localca -l tpm-spec-family -l tpm-spec-revision -l tpm-spec-level
complete -c swtpm_localca -l tpm2
complete -c swtpm_localca -l allow-signing
complete -c swtpm_localca -l decryption

