# swtpm_ioctl
# Autogenerated from man page /usr/share/man/man8/swtpm_ioctl.8.gz
complete -c swtpm_ioctl -l tpm-device
complete -c swtpm_ioctl -l tcp
complete -c swtpm_ioctl -l unix
complete -c swtpm_ioctl -s c
complete -c swtpm_ioctl -s i
complete -c swtpm_ioctl -s s
complete -c swtpm_ioctl -l stop
complete -c swtpm_ioctl -s e
complete -c swtpm_ioctl -s r
complete -c swtpm_ioctl -s l
complete -c swtpm_ioctl -s v
complete -c swtpm_ioctl -s C
complete -c swtpm_ioctl -s h
complete -c swtpm_ioctl -l save
complete -c swtpm_ioctl -l load
complete -c swtpm_ioctl -s g
complete -c swtpm_ioctl -l info
complete -c swtpm_ioctl -l lock-storage

