# swtpm_setup
# Autogenerated from man page /usr/share/man/man8/swtpm_setup.8.gz
complete -c swtpm_setup -l runas
complete -c swtpm_setup -l config
complete -c swtpm_setup -l tpm-state -l tpmstate
complete -c swtpm_setup -l tpm
complete -c swtpm_setup -l tpm2
complete -c swtpm_setup -l createek
complete -c swtpm_setup -l allow-signing
complete -c swtpm_setup -l decryption
complete -c swtpm_setup -l ecc
complete -c swtpm_setup -l take-ownership
complete -c swtpm_setup -l ownerpass
complete -c swtpm_setup -l owner-well-known
complete -c swtpm_setup -l srkpass
complete -c swtpm_setup -l srk-well-known
complete -c swtpm_setup -l create-ek-cert
complete -c swtpm_setup -l create-platform-cert
complete -c swtpm_setup -l lock-nvram
complete -c swtpm_setup -l display
complete -c swtpm_setup -l logfile
complete -c swtpm_setup -l keyfile
complete -c swtpm_setup -l keyfile-fd
complete -c swtpm_setup -l pwdfile
complete -c swtpm_setup -l pwdfile-fd
complete -c swtpm_setup -l ciper
complete -c swtpm_setup -l overwrite
complete -c swtpm_setup -l not-overwrite
complete -c swtpm_setup -l vmid
complete -c swtpm_setup -l pcr-banks
complete -c swtpm_setup -l swtpm_ioctl
complete -c swtpm_setup -l tcsd-system-ps-file
complete -c swtpm_setup -l rsa-keysize
complete -c swtpm_setup -l reconfigure
complete -c swtpm_setup -l print-capabilities
complete -c swtpm_setup -l write-ek-cert-files
complete -c swtpm_setup -l create-config-files
complete -c swtpm_setup -l help -s h

