# swtpm_bios
# Autogenerated from man page /usr/share/man/man8/swtpm_bios.8.gz
complete -c swtpm_bios -l tpm-device
complete -c swtpm_bios -l tcp
complete -c swtpm_bios -l unix
complete -c swtpm_bios -o tpm2
complete -c swtpm_bios -s c
complete -c swtpm_bios -s s
complete -c swtpm_bios -s d
complete -c swtpm_bios -s n
complete -c swtpm_bios -s o
complete -c swtpm_bios -o ea
complete -c swtpm_bios -o cs
complete -c swtpm_bios -s u
complete -c swtpm_bios -s v
complete -c swtpm_bios -s h

