# swtpm_cert
# Autogenerated from man page /usr/share/man/man8/swtpm_cert.8.gz
complete -c swtpm_cert -l type
complete -c swtpm_cert -l pubkey
complete -c swtpm_cert -l modulus
complete -c swtpm_cert -l ecc-x
complete -c swtpm_cert -l ecc-y
complete -c swtpm_cert -l ecc-curveid
complete -c swtpm_cert -l exponent
complete -c swtpm_cert -l signkey
complete -c swtpm_cert -l signkey-password
complete -c swtpm_cert -l signkey-pwd
complete -c swtpm_cert -l parentkey-password
complete -c swtpm_cert -l parentkey-pwd
complete -c swtpm_cert -l issuercert
complete -c swtpm_cert -l out-cert
complete -c swtpm_cert -l serial
complete -c swtpm_cert -l days
complete -c swtpm_cert -l pem
complete -c swtpm_cert -l tpm-manufacturer
complete -c swtpm_cert -l tpm-model
complete -c swtpm_cert -l tpm-version
complete -c swtpm_cert -l platform-manufacturer
complete -c swtpm_cert -l platform-model
complete -c swtpm_cert -l platform-version
complete -c swtpm_cert -l subject
complete -c swtpm_cert -l tpm2
complete -c swtpm_cert -l allow-signing
complete -c swtpm_cert -l decryption
complete -c swtpm_cert -l print-capabilities
complete -c swtpm_cert -l help -s h

