# symlinks
# Autogenerated from man page /usr/share/man/man1/symlinks.1.gz
complete -c symlinks -s c -d 'convert absolute links (within the same filesystem) to relative links'
complete -c symlinks -s d -d 'causes  dangling links to be removed'
complete -c symlinks -s o -d 'fix links on other filesystems encountered while recursing'
complete -c symlinks -s r -d 'recursively operate on subdirectories within the same filesystem'
complete -c symlinks -s s -d 'causes  lengthy links to be detected'
complete -c symlinks -s t -d 'is used to test for what  symlinks would do if  -c were specified, but withou…'
complete -c symlinks -s v -d 'show all symbolic links'
complete -c symlinks -s C -d 'chroot to current directory before looking at dirlist'

