# tcpslice
# Autogenerated from man page /usr/share/man/man8/tcpslice.8.gz
complete -c tcpslice -s D -d 'Do not discard duplicate packets seen when merging multiple trace files'
complete -c tcpslice -s d -d 'Dump the start and end times specified by the given range and exit'
complete -c tcpslice -s e -d 'Specify a number of  seconds to wait after the last packet was seen before co…'
complete -c tcpslice -s f -d 'Specify the name  format of PCAP files to which each session will be extracte…'
complete -c tcpslice -s h -d 'Print the tcpslice and libpcap version strings, print a usage message, and ex…'
complete -c tcpslice -s l -d 'When merging more than one file, merge on the basis of relative time, rather …'
complete -c tcpslice -s R -d 'Dump the timestamps of the first and last packets in each input file as raw t…'
complete -c tcpslice -s r -d 'Same as  -R except the timestamps are dumped in human-readable format, simila…'
complete -c tcpslice -s s -d 'Enable session tracking for the specified  types which is a comma-separated l…'
complete -c tcpslice -s t -d 'Same as  -R except the timestamps are dumped in  tcpslice format, i. e'
complete -c tcpslice -s v -d 'Turn on verbose mode'
complete -c tcpslice -s w -d flag
complete -c tcpslice -o tt -d 'flag).  For example, 654321098'

