# tcsd
# Autogenerated from man page /usr/share/man/man8/tcsd.8.gz
complete -c tcsd -s f -l foreground -d 'run the daemon in the foreground'
complete -c tcsd -s e -d 'attempt to connect to software TPMs over TCP'
complete -c tcsd -s c -l config -d 'use the provided configuration file rather than the default configuration file'
complete -c tcsd -s h -l help -d 'display help message'

