# tesseract
# Autogenerated from man page /usr/share/man/man1/tesseract.1.gz
complete -c tesseract -s c -d 'Set value for parameter CONFIGVAR to VALUE'
complete -c tesseract -l dpi -d 'Specify the resolution N in DPI for the input image(s)'
complete -c tesseract -s l -s l -d 'The language or script to use'
complete -c tesseract -l psm -d 'Set Tesseract to only run a subset of layout analysis and assume a certain fo…'
complete -c tesseract -l oem -d 'Specify OCR Engine mode.  The options for N are: . sp . if n \\{\\'
complete -c tesseract -l tessdata-dir -d 'Specify the location of tessdata path'
complete -c tesseract -l user-patterns -d 'Specify the location of user patterns file'
complete -c tesseract -l user-words -d 'Specify the location of user words file'
complete -c tesseract -s h -l help
complete -c tesseract -l help-extra
complete -c tesseract -l help-psm
complete -c tesseract -l help-oem
complete -c tesseract -s v -l version
complete -c tesseract -l list-langs
complete -c tesseract -l print-parameters

