# thin_metadata_pack
# Autogenerated from man page /usr/share/man/man8/thin_metadata_pack.8.gz
complete -c thin_metadata_pack -s h -l help -d 'Print help and exit'
complete -c thin_metadata_pack -s V -l version -d 'Print version information and exit'
complete -c thin_metadata_pack -s i -l input -d 'Input file or device with binary data'
complete -c thin_metadata_pack -s o -l output -d 'Output file or device for binary data'

