# thin_metadata_unpack
# Autogenerated from man page /usr/share/man/man8/thin_metadata_unpack.8.gz
complete -c thin_metadata_unpack -s h -l help -d 'Print help and exit'
complete -c thin_metadata_unpack -s V -l version -d 'Print version information and exit'
complete -c thin_metadata_unpack -s i -l input -d 'Input file or device with binary data'
complete -c thin_metadata_unpack -s o -l output -d 'Output file or device for binary data'

