# totem
# Autogenerated from man page /usr/share/man/man1/totem.1.gz
complete -c totem -s '?' -l help -d 'Output a longer help message then quit'
complete -c totem -l version -d 'Output version information then quit'
complete -c totem -l play-pause -d 'Tell an already-running instance of   Videos to toggle between play and pause'
complete -c totem -l play -d 'Tell an already-running instance of  Videos to play (has no effect if already…'
complete -c totem -l pause -d 'Tell an already-running instance of  Videos to pause (has no effect if alread…'
complete -c totem -l next -d 'Tell an already-running instance of   Videos to skip to the next movie or cha…'
complete -c totem -l previous -d 'Tell an already-running instance of   Videos to return to the previous movie …'
complete -c totem -l seek-fwd -d 'Tell an already-running instance of   Videos to seek forwards 15 seconds in t…'
complete -c totem -l seek-bwd -d 'Tell an already-running instance of   Videos to seek backwards 15 seconds in …'
complete -c totem -l volume-up -d 'Tell an already-running instance of   Videos to raise the volume by 8%'
complete -c totem -l volume-down -d 'Tell an already-running instance of   Videos to lower the volume by 8%'
complete -c totem -l mute -d 'Tell an already-running instance of   Videos to toggle between muted and unmu…'
complete -c totem -l fullscreen -d 'Tell an already-running instance of   Videos to toggle fullscreen mode'
complete -c totem -l quit -d 'Tell an already-running instance of  Videos to quit'
complete -c totem -l enqueue -d 'Tell an already-running instance of  Videos to add a new stream to the playli…'
complete -c totem -l replace -d 'Tell an already-running instance of Videos to play from the playlist'

