# totem-video-thumbnailer
# Autogenerated from man page /usr/share/man/man1/totem-video-thumbnailer.1.gz
complete -c totem-video-thumbnailer -s j -l jpeg -d 'X Item "-j --jpeg" Switch the output format to JPEG.  The default is PNG'
complete -c totem-video-thumbnailer -s l -l no-limit -d 'X Item "-l --no-limit" Don\'t limit the thumbnailing time to 30 seconds'
complete -c totem-video-thumbnailer -s s

