# tracepath6
# Autogenerated from man page /usr/share/man/man8/tracepath6.8.gz
complete -c tracepath6 -s 4 -d 'Use IPv4 only'
complete -c tracepath6 -s 6 -d 'Use IPv6 only'
complete -c tracepath6 -s n -d 'Print primarily IP addresses numerically'
complete -c tracepath6 -s b -d 'Print both: Host names and IP addresses'
complete -c tracepath6 -s l -d 'Sets the initial packet length to pktlen instead of 65535 for IPv4 or 128000 …'
complete -c tracepath6 -s m -d 'Set maximum hops (or maximum TTLs) to max_hops instead of 30'
complete -c tracepath6 -s p -d 'Sets the initial destination port to use'
complete -c tracepath6 -s V -d 'Print version and exit'

