# trash-put
# Autogenerated from man page /usr/share/man/man1/trash-put.1.gz
complete -c trash-put -s f -d 'br Silently ignore any files or directories that do not exist'
complete -c trash-put -s h -l help -d 'Show help message and exit'
complete -c trash-put -l trash-dir -d 'Use TRASHDIR as trash folder'
complete -c trash-put -s v -l verbose -d 'Explain what is being done'

