# trash-list
# Autogenerated from man page /usr/share/man/man1/trash-list.1.gz
complete -c trash-list -s h -l help -d 'Show help message and exit'
complete -c trash-list -l trash-dir -d 'Use TRASHDIR as trash folder.  Can be used multiple times'

