# trash
# Autogenerated from man page /usr/share/man/man1/trash.1.gz
complete -c trash -s f -d 'br Silently ignore any files or directories that do not exist'
complete -c trash -s h -l help -d 'Show help message and exit'
complete -c trash -l trash-dir -d 'Use TRASHDIR as trash folder'
complete -c trash -s v -l verbose -d 'Explain what is being done'

