# tunefs.ocfs2
# Autogenerated from man page /usr/share/man/man8/tunefs.ocfs2.8.gz
complete -c 'tunefs.ocfs2' -l cloned-volume -d 'Change the volume UUID (auto-generated) and the label, if provided, of a clon…'
complete -c 'tunefs.ocfs2' -l fs-features -d 'Turn specific file system features on or off.  tunefs'
complete -c 'tunefs.ocfs2' -s J -l journal-options -d 'Modify the journal using options specified on the command-line'
complete -c 'tunefs.ocfs2' -s L -l label -d 'Change the volume label of the file system'
complete -c 'tunefs.ocfs2' -s N -l node-slots -d 'Valid number ranges from 1 to 255'
complete -c 'tunefs.ocfs2' -s S -l volume-size -d 'Grow the size of the OCFS2 file system'
complete -c 'tunefs.ocfs2' -s Q -l query -d 'Query the file system for its attributes like block size, label, etc'
complete -c 'tunefs.ocfs2' -s q -l quiet -d 'Quiet mode'
complete -c 'tunefs.ocfs2' -s U -l uuid-reset -d 'Reset the volume UUID of the file system'
complete -c 'tunefs.ocfs2' -s v -l verbose -d 'Verbose mode'
complete -c 'tunefs.ocfs2' -s V -l version -d 'Show version and exit'
complete -c 'tunefs.ocfs2' -s y -l yes -d 'Always answer Yes in interactive command line'
complete -c 'tunefs.ocfs2' -s n -l no -d 'Always answer No in interactive command line'
complete -c 'tunefs.ocfs2' -l backup-super -d 'Backs up the superblock to fixed offsets (1G, 4G, 16G, 64G, 256G and 1T) on d…'
complete -c 'tunefs.ocfs2' -l list-sparse -d 'Lists the files having holes'
complete -c 'tunefs.ocfs2' -l update-cluster-stack -d 'Updating on-disk cluster information to match the running cluster'

