# tunegfs2
# Autogenerated from man page /usr/share/man/man8/tunegfs2.8.gz
complete -c tunegfs2 -s h -d 'Prints out usage information for this command'
complete -c tunegfs2 -s l -d 'List contents of the filesystem superblock'
complete -c tunegfs2 -s L -d 'Change the filesystem label'
complete -c tunegfs2 -s o -d 'Set mount options'
complete -c tunegfs2 -s U -d 'Set the filesystem UUID'
complete -c tunegfs2 -s V -d 'Print out the information on the version of the tool'
complete -c tunegfs2 -s r

