# unar
# Autogenerated from man page /usr/share/man/man1/unar.1.gz
complete -c unar -s o -o output-directory -d 'The directory to write the contents of the archive to'
complete -c unar -s f -o force-overwrite -d 'Always overwrite files when a file to be unpacked already exists on disk'
complete -c unar -s r -o force-rename -d 'Always rename files when a file to be unpacked already exists on disk'
complete -c unar -s s -o force-skip -d 'Always skip files when a file to be unpacked already exists on disk'
complete -c unar -s d -o force-directory -d 'Always create a containing directory for the contents of the unpacked archive'
complete -c unar -s D -o no-directory -d 'Never create a containing directory for the contents of the unpacked archive'
complete -c unar -s p -o password -d 'The password to use for decrypting protected archives'
complete -c unar -s e -o encoding -d 'The encoding to use for filenames in the archive, when it is not known'
complete -c unar -s E -o password-encoding -d 'The encoding to use for the password for the archive, when it is not known'
complete -c unar -s i -o indexes -d 'Instead of specifying the files to list as filenames or wildcard patterns, sp…'
complete -c unar -o nr -o no-recursion -d 'Do not attempt to extract archives contained in other archives'
complete -c unar -s t -o copy-time -d 'Copy the file modification time from the archive file to the containing direc…'
complete -c unar -s k -o forks -d 'How to handle Mac OS resource forks'
complete -c unar -s q -o quiet -d 'Run in quiet mode'
complete -c unar -s v -o version -d 'Print version and exit'
complete -c unar -s h -o help -d 'Display help information.  SEE ALSO lsar (1)'

