# uncompress
# Autogenerated from man page /usr/share/man/man1/uncompress.1.gz
complete -c uncompress -s f -d 'flag is given'
complete -c uncompress -s k -d 'option makes compress/uncompress keep the input files instead of automaticall…'
complete -c uncompress -s c -d 'option makes compress/uncompress write to the standard output; no files are c…'
complete -c uncompress -s r -d 'flag is specified,  compress will operate recursively'
complete -c uncompress -s V -d 'flag tells each of these programs to print its version and patchlevel, along …'
complete -c uncompress -s b -d 'flag is reached (default 16).  Bits must be between 9 and 16'
complete -c uncompress -s v -d 'option, a message is printed yielding the percentage of reduction for each fi…'

