# userhelper
# Autogenerated from man page /usr/share/man/man8/userhelper.8.gz
complete -c userhelper -s t -d 'Use text mode authentication instead of the numbered message types just descr…'
complete -c userhelper -s w -d 'Specify a program name to be run and arguments to be passed to it'
complete -c userhelper -s c -d 'Change the current user\'s password'
complete -c userhelper -s f -d 'Specify a new Full Name'
complete -c userhelper -s o -d 'Specify a new Office'
complete -c userhelper -s p -d 'Specify a new Office Phone'
complete -c userhelper -s h -d 'Specify a new Home Phone'
complete -c userhelper -s s -d 'Specify a new shell'

