# usleep
# Autogenerated from man page /usr/share/man/man1/usleep.1.gz
complete -c usleep -l help -s '?' -d 'Print help information'
complete -c usleep -l usage -d 'Show short usage message'
complete -c usleep -s v -l version -d 'Print version information'

