# virsh
# Autogenerated from man page /usr/share/man/man1/virsh.1.gz
complete -c virsh -s c -l connect
complete -c virsh -s d -l debug
complete -c virsh -s e -l escape -d 'Set alternative escape sequence for console command'
complete -c virsh -s h -l help -d 'Ignore all other arguments, and behave as if the help command were given inst…'
complete -c virsh -s k -l keepalive-interval -d 'Set an INTERVAL (in seconds) for sending keepalive messages to check whether …'
complete -c virsh -s K -l keepalive-count -d 'Set a number of times keepalive message can be sent without getting an answer…'
complete -c virsh -s l -l log -d 'Output logging details to FILE'
complete -c virsh -s q -l quiet -d 'Avoid extra informational messages'
complete -c virsh -s r -l readonly -d 'Make the initial connection read-only, as if by the --readonly option of the …'
complete -c virsh -s t -l timing -d 'Output elapsed time information for each command'
complete -c virsh -s v -l version -d 'Ignore all other arguments, and prints the version of the libvirt library vir…'
complete -c virsh -s V -d 'Ignore all other arguments, and prints the version of the libvirt library vir…'
complete -c virsh -l -------------------------------------------------- -d '  0     Domain-0                       running   2     fedora                …'
complete -c virsh -l inactive -l all
complete -c virsh -l with-managed-save -d 'specify --without-managed-save.  Domain state'
complete -c virsh -l state-running -l state-paused
complete -c virsh -l state-shutoff -l state-other -d 'other states as a fallback.  Autostarting domains'
complete -c virsh -l name -l uuid -l id -d printing
complete -c virsh -l table
complete -c virsh -l add -d pool
complete -c virsh -l total-bytes-sec -d 'default being bytes per second if no suffix is specified'
complete -c virsh -l read-bytes-sec -d 'default being bytes per second if no suffix is specified'
complete -c virsh -l write-bytes-sec -d 'default being bytes per second if no suffix is specified'
complete -c virsh -l total-iops-sec
complete -c virsh -l read-iops-sec
complete -c virsh -l write-iops-sec
complete -c virsh -l total-bytes-sec-max -d 'integer, the default being bytes per second if no suffix is specified'
complete -c virsh -l read-bytes-sec-max -d 'integer, the default being bytes per second if no suffix is specified'
complete -c virsh -l write-bytes-sec-max -d 'integer, the default being bytes per second if no suffix is specified'
complete -c virsh -l total-iops-sec-max
complete -c virsh -l read-iops-sec-max
complete -c virsh -l write-iops-sec-max
complete -c virsh -l total-bytes-sec-max-length -d 'total throughput limit'
complete -c virsh -l read-bytes-sec-max-length -d 'read throughput limit'
complete -c virsh -l write-bytes-sec-max-length -d 'write throughput limit'
complete -c virsh -l total-iops-sec-max-length -d 'total I/O operations limit'
complete -c virsh -l read-iops-sec-max-length -d 'read I/O operations limit'
complete -c virsh -l write-iops-sec-max-length -d 'write I/O operations limit'
complete -c virsh -l size-iops-sec
complete -c virsh -l group-name -d 'For a QEMU domain, if no name is provided, then the default is to have a sing…'
complete -c virsh -l config -d 'When setting the disk io parameters both --live and --config flags may be giv…'
complete -c virsh -l current -d 'is different depending on hypervisor.  blkiotune'
complete -c virsh -l weight -d 'could be in the range [10, 1000]'
complete -c virsh -l shallow -d 'backing file of the resulting top image to be committed'
complete -c virsh -l keep-relative
complete -c virsh -l 'pivot;' -l keep-overlay
complete -c virsh -l active -l wait -l abort
complete -c virsh -l format -d 'file unless --blockdev is used to signal that it is a block device'
complete -c virsh -l transient-job -d 'be recovered if the VM crashes or is turned off before the job completes'
complete -c virsh -l info -l async -l pivot -d 'abort mode; --raw implies info mode; and if no mode was given, --info mode is…'
complete -c virsh -l raw
complete -c virsh -l bytes -d 'not supply bytes/s resolution; when omitting the flag, raw output is listed i…'
complete -c virsh -l total -d 'stats of the CPUs from start, count for only count CPUs\' stats.  create'
complete -c virsh -l include-password -d 'included in the URI'
complete -c virsh -l persistent -d 'interface-device can be the interface\'s target name or the MAC address'
complete -c virsh -l keep-completed
complete -c virsh -l anystats
complete -c virsh -l secrethdr -d 'The header includes artifacts needed by the hypervisor firmware to recover th…'
complete -c virsh -l vcpu -l interface -l block -l perf -l iothread -l memory
complete -c virsh -l dirtyrate -l vm
complete -c virsh -l cpu-total
complete -c virsh -l balloon
complete -c virsh -l nowait -d 'some statistics might be missing for such domain.  domtime'
complete -c virsh -l pretty -d 'readable form'
complete -c virsh -l domain -d 'The xml and --domain arguments are mutually exclusive'
complete -c virsh -s 2 -l timeout -d 'o 2'
complete -c virsh -s 1 -d 'libvirt daemon), o 2 0 - do not wait at all,'
complete -c virsh -l timezone -l hostname -l filesystem -l disk -d 'If an explicitly requested information type is not supported by the guest age…'
complete -c virsh -l os
complete -c virsh -l security-info
complete -c virsh -l min-guarantee -d 'limits are scaled integers (see NOTES above), with a default of kibibytes (bl…'
complete -c virsh -l hard-limit
complete -c virsh -l soft-limit
complete -c virsh -l swap-hard-limit
complete -c virsh -l undefinesource -l suspend -d 'leaves the domain paused on the destination host'
complete -c virsh -l copy-storage-all -d 'disk copy, --copy-storage-inc indicates migration with non-shared storage wit…'
complete -c virsh -l copy-storage- -d 'images on source host to the images found at the same place on the destinatio…'
complete -c virsh -l migrate-disks -d 'transfer via the comma separated disk-list argument'
complete -c virsh -l change-protection -d 'be made to the domain while the migration is underway; this flag is implicitl…'
complete -c virsh -l verbose
complete -c virsh -l abort-on-error -d 'happens during the migration'
complete -c virsh -l postcopy -d 'post-copy, i. e. , migration is started in pre-copy mode'
complete -c virsh -l postcopy-after-precopy -d 'automatically switch to post-copy after the first pass of pre-copy is finished'
complete -c virsh -l postcopy-bandwidth -d 'may be limited using --bandwidth'
complete -c virsh -l auto-converge -d 'guest CPU throttling rate can be set with auto-converge-initial'
complete -c virsh -l rdma-pin-all -d 'starts with rdma://) to tell the hypervisor to pin all domain\'s memory at onc…'
complete -c virsh -l zerocopy -d 'For QEMU/KVM this means QEMU will be temporarily allowed to lock all guest pa…'
complete -c virsh -l compressed -d 'with --comp-methods'
complete -c virsh -l parallel -d 'parallel connections.  The number of such connections can be set using'
complete -c virsh -l parallel-connections -d 'network link between the source and the target and thus speeding up the migra…'
complete -c virsh -l xml -d 'alternative XML file for use on the restored guest with changes only in the h…'
complete -c virsh -l running -l paused -d 'domain should be started in'
complete -c virsh -l nvram -l keep-nvram -d '(/domain/os/nvram/) file'
complete -c virsh -l remove-all-storage -d 'support this option, presently only rbd'
complete -c virsh -l tpm -l keep-tpm -d 'persistent state directory structure and files'
complete -c virsh -l maximum -d 'domain can add via setvcpus, while --active shows the current usage; these tw…'
complete -c virsh -l source-host-name -l source-host-transport -l source-host-socket -d 'which respectively denote the name of the host, the host\'s transport method, …'
complete -c virsh -l target -d 'connect the domain to the source'
complete -c virsh -l mac -d 'address is not given, a new address will be automatically generated (and stor…'
complete -c virsh -l script -d 'while attaching to a bridge - this will be called instead of the default scri…'
complete -c virsh -l model -d domain
complete -c virsh -l inbound -l outbound -d 'interface.   At least one from the average, floor pair must be specified'
complete -c virsh -l managed -d 'that the interface should be managed, which means detached and reattached fro…'
complete -c virsh -l source-mode -d 'server and client that control whether hypervisor waits for the other process…'
complete -c virsh -l alias -l node
complete -c virsh -l eject
complete -c virsh -l insert -d 'If the device has source (e. g'
complete -c virsh -l no-autostart
complete -c virsh -l overwrite -d 'volume devices prior to initializing and formatting each device'
complete -c virsh -l no-overwrite -d 'just --build is provided, then pool-build is called with no flags'
complete -c virsh -l print-xml -d 'without creating the pool.   Otherwise, the pool has the specified type'
complete -c virsh -l adapter-parent-wwnn
complete -c virsh -l adapter-parent-fabric-wwn -d 'defines the wwnn and wwpn to be used for the fc_host adapter type pool'
complete -c virsh -l autostart -d 'with autostarting disabled'
complete -c virsh -l inputpool -d 'source volume is in'
complete -c virsh -l allocation -d 'also as a scaled integer defaulting to bytes'
complete -c virsh -l backing-vol -d 'volume to be used if taking a snapshot of an existing volume'
complete -c virsh -l backing-vol-format -d 'raw, bochs, qcow, qcow2, qed, vmdk, host_device'
complete -c virsh -l pool -d 'that contains the source volume and will contain the new volume'
complete -c virsh -l offset -d 'the data.  The value must be 0 or larger'
complete -c virsh -l length -d 'A negative value is interpreted as an unsigned long long value to essentially…'
complete -c virsh -l no-private -d 'SNAPSHOT COMMANDS'
complete -c virsh -l disk-only -d 'ignored, and automatically filled in by libvirt'
complete -c virsh -l diskspec
complete -c virsh -l topological -d 'ancestors (although there may be more than one possible ordering with this pr…'
complete -c virsh -l parent
complete -c virsh -l descendants -l tree -d 'use of --descendants is implied.   This option is not compatible with --roots'
complete -c virsh -l roots -l from -d 'is not included in the list unless the --tree option is also present'
complete -c virsh -l size

