# virtinterfaced
# Autogenerated from man page /usr/share/man/man8/virtinterfaced.8.gz
complete -c virtinterfaced -s h -l help
complete -c virtinterfaced -s d -l daemon
complete -c virtinterfaced -s f -l config
complete -c virtinterfaced -s p -l pid-file
complete -c virtinterfaced -s t -l timeout
complete -c virtinterfaced -s v -l verbose
complete -c virtinterfaced -l version
complete -c virtinterfaced -o rw-r--r--

