# virt-host-validate
# Autogenerated from man page /usr/share/man/man1/virt-host-validate.1.gz
complete -c virt-host-validate -s v -l version
complete -c virt-host-validate -s h -l help
complete -c virt-host-validate -s q -l quiet

