# virtqemud
# Autogenerated from man page /usr/share/man/man8/virtqemud.8.gz
complete -c virtqemud -s h -l help
complete -c virtqemud -s d -l daemon
complete -c virtqemud -s f -l config
complete -c virtqemud -s p -l pid-file
complete -c virtqemud -s t -l timeout
complete -c virtqemud -s v -l verbose
complete -c virtqemud -l version
complete -c virtqemud -o rw-r--r--

