# virtnwfilterd
# Autogenerated from man page /usr/share/man/man8/virtnwfilterd.8.gz
complete -c virtnwfilterd -s h -l help
complete -c virtnwfilterd -s d -l daemon
complete -c virtnwfilterd -s f -l config
complete -c virtnwfilterd -s p -l pid-file
complete -c virtnwfilterd -s t -l timeout
complete -c virtnwfilterd -s v -l verbose
complete -c virtnwfilterd -l version
complete -c virtnwfilterd -o rw-r--r--

