# virtlogd
# Autogenerated from man page /usr/share/man/man8/virtlogd.8.gz
complete -c virtlogd -s h -l help
complete -c virtlogd -s d -l daemon
complete -c virtlogd -s f -l config
complete -c virtlogd -s t -l timeout
complete -c virtlogd -s p -l pid-file
complete -c virtlogd -s v -l verbose
complete -c virtlogd -s V -l version
complete -c virtlogd -o rw-r--r--

