# virtsecretd
# Autogenerated from man page /usr/share/man/man8/virtsecretd.8.gz
complete -c virtsecretd -s h -l help
complete -c virtsecretd -s d -l daemon
complete -c virtsecretd -s f -l config
complete -c virtsecretd -s p -l pid-file
complete -c virtsecretd -s t -l timeout
complete -c virtsecretd -s v -l verbose
complete -c virtsecretd -l version
complete -c virtsecretd -o rw-r--r--

