# virtnodedevd
# Autogenerated from man page /usr/share/man/man8/virtnodedevd.8.gz
complete -c virtnodedevd -s h -l help
complete -c virtnodedevd -s d -l daemon
complete -c virtnodedevd -s f -l config
complete -c virtnodedevd -s p -l pid-file
complete -c virtnodedevd -s t -l timeout
complete -c virtnodedevd -s v -l verbose
complete -c virtnodedevd -l version
complete -c virtnodedevd -o rw-r--r--

