# virtnetworkd
# Autogenerated from man page /usr/share/man/man8/virtnetworkd.8.gz
complete -c virtnetworkd -s h -l help
complete -c virtnetworkd -s d -l daemon
complete -c virtnetworkd -s f -l config
complete -c virtnetworkd -s p -l pid-file
complete -c virtnetworkd -s t -l timeout
complete -c virtnetworkd -s v -l verbose
complete -c virtnetworkd -l version
complete -c virtnetworkd -o rw-r--r--

