# virtproxyd
# Autogenerated from man page /usr/share/man/man8/virtproxyd.8.gz
complete -c virtproxyd -s h -l help
complete -c virtproxyd -s d -l daemon
complete -c virtproxyd -s f -l config
complete -c virtproxyd -s p -l pid-file
complete -c virtproxyd -s t -l timeout
complete -c virtproxyd -s v -l verbose
complete -c virtproxyd -l version
complete -c virtproxyd -o rw-r--r--

