# virtstoraged
# Autogenerated from man page /usr/share/man/man8/virtstoraged.8.gz
complete -c virtstoraged -s h -l help
complete -c virtstoraged -s d -l daemon
complete -c virtstoraged -s f -l config
complete -c virtstoraged -s p -l pid-file
complete -c virtstoraged -s t -l timeout
complete -c virtstoraged -s v -l verbose
complete -c virtstoraged -l version
complete -c virtstoraged -o rw-r--r--

