# virtlockd
# Autogenerated from man page /usr/share/man/man8/virtlockd.8.gz
complete -c virtlockd -s h -l help
complete -c virtlockd -s d -l daemon
complete -c virtlockd -s f -l config
complete -c virtlockd -s t -l timeout
complete -c virtlockd -s p -l pid-file
complete -c virtlockd -s v -l verbose
complete -c virtlockd -s V -l version
complete -c virtlockd -o rw-r--r--

