# virt-admin
# Autogenerated from man page /usr/share/man/man1/virt-admin.1.gz
complete -c virt-admin -s c -l connect
complete -c virt-admin -s d -l debug
complete -c virt-admin -s h -l help
complete -c virt-admin -s l -l log
complete -c virt-admin -s q -l quiet
complete -c virt-admin -s v -l version
complete -c virt-admin -s V
complete -c virt-admin -o c/--connect -d 'controlled daemon e. g. : virtqemud:///system, libvirtd:///system'
complete -c virt-admin -l filters -d 'Define a new set of logging filters where multiple filters are delimited by s…'
complete -c virt-admin -l outputs -d 'Define a new set of logging outputs where multiple outputs are delimited by s…'
complete -c virt-admin -l min-workers
complete -c virt-admin -l max-workers
complete -c virt-admin -l priority-workers
complete -c virt-admin -l max-clients
complete -c virt-admin -l max-unauth-clients

