# vncconfig
# Autogenerated from man page /usr/share/man/man1/vncconfig.1.gz
complete -c vncconfig -o connect -d 'Tells an Xvnc server to make a "reverse" connection to a listening VNC viewer…'
complete -c vncconfig -o disconnect -d 'This causes Xvnc to disconnect from all viewers so that the VNC desktop is no…'
complete -c vncconfig -o list -d 'Lists all the parameters supported by Xvnc'
complete -c vncconfig -o get -d 'Prints the current value of the given Xvnc parameter'
complete -c vncconfig -o nowin -d 'wish to clutter the desktop with the settings window - alternatively the'
complete -c vncconfig -o iconic
complete -c vncconfig -o desc -d 'Prints a short description of the given Xvnc parameter'
complete -c vncconfig -o set
complete -c vncconfig -l param
complete -c vncconfig -o display -d 'Specifies the Xvnc server to control'

