# wayland-info
# Autogenerated from man page /usr/share/man/man1/wayland-info.1.gz
complete -c wayland-info -s h -l help -d 'Print a summary of command line options, and quit'
complete -c wayland-info -s i -l interface -d 'Only print information about the Wayland globals containing the string interf…'

