# westcos-tool
# Autogenerated from man page /usr/share/man/man1/westcos-tool.1.gz
complete -c westcos-tool -l change-pin -s n -d 'Changes a PIN stored on the card'
complete -c westcos-tool -l certificate -s t -d 'Write certificate file file in PEM format to the card'
complete -c westcos-tool -l finalize -s f -d 'Finalize the card'
complete -c westcos-tool -l generate-key -s g -d 'Generate a private key on the card'
complete -c westcos-tool -l help -s h -d 'Print help message on screen'
complete -c westcos-tool -l install-pin -s i -d 'Install PIN file in on the card.  You must provide a PIN value with -x'
complete -c westcos-tool -l key-length -s l -d 'Change the length of private key.  Use with -g'
complete -c westcos-tool -l overwrite-key -s o -d 'Overwrite the key if there is already a key on the card'
complete -c westcos-tool -l pin-value -s x -l puk-value -s y -d 'These options can be used to specify the PIN/PUK values on the command line'
complete -c westcos-tool -l read-file -s j -d 'Read the file filename from the card'
complete -c westcos-tool -l reader -s r -d 'Number of the reader to use'
complete -c westcos-tool -l unblock-pin -s u -d 'Unblocks a PIN stored on the card'
complete -c westcos-tool -l verbose -s v -d 'Causes westcos-tool to be more verbose'
complete -c westcos-tool -l wait -s w -d 'Wait for a card to be inserted'
complete -c westcos-tool -l write-file -s k -d 'Put the file with name filename from disk to card'

