# winecfg
# Autogenerated from man page /usr/share/man/man1/winecfg.1.gz
complete -c winecfg -s v -d 'Set global Windows version to  version and exit'
complete -c winecfg -s '?' -d 'Display help, valid versions for version and exit'

