# wine
# Autogenerated from man page /usr/share/man/man1/wine.1.gz
complete -c wine -l help -d or
complete -c wine -l version -d 'as the only argument, wine will simply print a small help message or its vers…'

