# wineboot
# Autogenerated from man page /usr/share/man/man1/wineboot.1.gz
complete -c wineboot -s h -l help -d 'Display help message'
complete -c wineboot -s e -l end-session -d 'End the current session cleanly'
complete -c wineboot -s f -l force -d 'Force exit for processes that don\'t exit cleanly'
complete -c wineboot -s i -l init -d 'Initialize the WINEPREFIX'
complete -c wineboot -s k -l kill -d 'Kill running processes without any cleanup'
complete -c wineboot -s r -l restart -d 'Restart only, don\'t do normal startup operations'
complete -c wineboot -s s -l shutdown -d 'Shutdown only, don\'t reboot'

