# winpr-makecert
# Autogenerated from man page /usr/share/man/man1/winpr-makecert.1.gz
complete -c winpr-makecert -o rdp -d 'Dummy parameter'
complete -c winpr-makecert -o silent -d 'Don\'t print the generated certificate to stdout'
complete -c winpr-makecert -s f -d 'Three formats are supported: crt, pem and pfx'
complete -c winpr-makecert -s p -d 'Password to use if the pfx format is used as format'
complete -c winpr-makecert -o live -d 'Don\'t write the key/certificate to disk'
complete -c winpr-makecert -s n -d 'The common name to use in the certificate'
complete -c winpr-makecert -s m -d 'Validity period in months'
complete -c winpr-makecert -s y -d 'Validity period in years'
complete -c winpr-makecert -o len -d 'Key length in bits to use'
complete -c winpr-makecert -s a -d 'The hashing algorithm to use'
complete -c winpr-makecert -s '#' -d 'The serial number to use for the certificate'
complete -c winpr-makecert -o path -d 'A directory where the certificate should be created in'

