# winpr-hash
# Autogenerated from man page /usr/share/man/man1/winpr-hash.1.gz
complete -c winpr-hash -s u -d 'The username to use'
complete -c winpr-hash -s p -d 'Password to use'
complete -c winpr-hash -s d -d 'A optional parameter to specify the domain of the user'
complete -c winpr-hash -s f -d 'Specify the output format.  The default outputs only the plain NTLM hash'
complete -c winpr-hash -s v -d 'Version allows it to specify the NTLM version to use'

