# wrestool
# Autogenerated from man page /usr/share/man/man1/wrestool.1.gz
complete -c wrestool -s x -l extract -d 'Extract resources'
complete -c wrestool -s l -l list -d 'Output list of resources (default)'
complete -c wrestool -s t -l type -o ']ID' -d 'Resource type identifier of affected resources'
complete -c wrestool -s n -l name -d 'Resource name identifier of affected resources'
complete -c wrestool -s L -l language -d 'Resource language identifier.  Has no effect when processing 16-bit libraries'
complete -c wrestool -s a -l all -d 'Perform operation on all resource (default)'
complete -c wrestool -s o -l output -d 'Where to place extracted resources'
complete -c wrestool -s R -l raw -d 'Do not parse resource contents - extract raw data'
complete -c wrestool -s v -l verbose -d 'Explain what is being done'
complete -c wrestool -l help -d 'Display a help message and exit'
complete -c wrestool -l version -d 'Output version information and exit'

