# wsdl
# Autogenerated from man page /usr/share/man/man1/wsdl.1.gz
complete -c wsdl -o appsettingurlkey:key -o urlkey:key -d 'Specifies that the url for the services should be read from the <appsettings>…'
complete -c wsdl -o appsettingbaseurl:url -o baseurl:url -d 'Specifies a base URL for the service'
complete -c wsdl -o language:language -s l -d 'Language of the code to generate'
complete -c wsdl -o namespace:name -o n:name -d 'The namespace of the generated classes'
complete -c wsdl -o out:filename -o o:filename -d 'The target file for generated code'
complete -c wsdl -o protocol:protocol -o p:protocol -d 'The protocol for which to generate code'
complete -c wsdl -o sample:METHOD -d 'This will display XML request and reply of the sample invocations to that SOA…'
complete -c wsdl -o server -d 'Generate a server skeleton instead of a client proxy'
complete -c wsdl -o nologo -d 'Supress the startup logo'
complete -c wsdl -o u:username -o user:username -d 'The user name to use when connecting to the server'
complete -c wsdl -o p:password -o password:password -d 'The password to use when connecting to the server'
complete -c wsdl -o appsettingurlkey -d 'option, and the '
complete -c wsdl -o type:typename -d 'Generate a proxy for a compiled web service class'
complete -c wsdl -o d:domain -o domain:domain -d 'The domain to use when connecting to the server'

