# xdms
# Autogenerated from man page /usr/share/man/man1/xdms.1.gz
complete -c xdms -s d -d 'Unpack to a separate destination directory'
complete -c xdms -s f -d 'Override errors.  Useful for desperate data salvaging'
complete -c xdms -s p -d 'Decrypt with a password'
complete -c xdms -s q -d 'Be quiet'
complete -c xdms -s v -d 'Be verbose.  Examples To unpack a DMS file, do:'

