# zfs-fuse
# Autogenerated from man page /usr/share/man/man8/zfs-fuse.8.gz
complete -c zfs-fuse -s h -l help -d 'Show summary of options'
complete -c zfs-fuse -s p -l pidfile -d 'Write the daemon\\*(Aqs PID to filename after daemonizing'
complete -c zfs-fuse -s n -l no-daemon -d 'Stay in foreground, don\\*(Aqt daemonize'
complete -c zfs-fuse -l no-kstat-mount -d 'Do not mount kstats in /zfs-kstat'
complete -c zfs-fuse -l disable-block-cache -d 'Enable direct I/O for disk operations'
complete -c zfs-fuse -l disable-page-cache -d '(obsolete; option no longer has any effect)'
complete -c zfs-fuse -s a -l fuse-attr-timeout -d 'Sets timeout for caching FUSE attributes in kernel.  Defaults to 0. 0'
complete -c zfs-fuse -s e -l fuse-entry-timeout -d 'Sets timeout for caching FUSE entries in kernel.  Defaults to 0. 0'
complete -c zfs-fuse -l log-uberblocks -d 'Logs uberblocks of any mounted filesystem to syslog'
complete -c zfs-fuse -s m -l max-arc-size -d 'Forces the maximum ARC size (in megabytes).  Range: 16 to 16384'
complete -c zfs-fuse -s o -l fuse-mount-options -d 'Sets FUSE mount options for all filesystems'
complete -c zfs-fuse -s u -l min-uberblock-txg -d 'Skips uberblocks with a TXG < MIN when mounting any fs'
complete -c zfs-fuse -s v -l vdev-cache-size -d 'adjust the size of the vdev cache.  Default : 10'
complete -c zfs-fuse -l zfs-prefetch-disable -d 'Disable the high level prefetch cache in zfs'
complete -c zfs-fuse -l stack-size -d 'Limit the stack size of threads (in kb).  default : no limit (8 Mb for linux)'
complete -c zfs-fuse -s x -l enable-xattr -d 'Enable support for extended attributes'

