# zipdetails
# Autogenerated from man page /usr/share/man/man1/zipdetails.1.gz
complete -c zipdetails -s h
complete -c zipdetails -l redact
complete -c zipdetails -l scan
complete -c zipdetails -l utc
complete -c zipdetails -s v
complete -c zipdetails -l version

