# zpaq
# Autogenerated from man page /usr/share/man/man1/zpaq.1.gz
complete -c zpaq -o all -d 'X Item "-all [N]" With \\f(CW\\*(C`list\\*(C\', list all saved versions and not j…'
complete -c zpaq -s f -d 'X Item "-f"'
complete -c zpaq -o force -d 'X Item "-force" '
complete -c zpaq -o fragment -d 'X Item "-fragment N" Set the dedupe fragment size range from 64 2^N to 8128 2…'
complete -c zpaq -o index -d 'X Item "-index indexfile" With \\f(CW\\*(C`add\\*(C\', create archive\\f(CW\\*(C`'
complete -c zpaq -o key -d 'X Item "-key password" This option is required for all commands operating on …'
complete -c zpaq -o mtype -d 'X Item "-mtype[Blocksize[. pre[. arg][comp[. arg]]. ]]"'
complete -c zpaq -o method -d 'X Item "-method type[Blocksize[. pre[. arg][comp[. arg]]. ]]" '
complete -c zpaq -o noattributes -d 'X Item "-noattributes" With \\f(CW\\*(C`add\\*(C\', do not save Windows attribute…'
complete -c zpaq -o not -d 'X Item "-not [file]. "'
complete -c zpaq -o only -d 'X Item "-only file'
complete -c zpaq -o repack -d 'X Item "-repack new_archive [new_password]" With \\f(CW\\*(C`extract\\*(C\', stor…'
complete -c zpaq -o sN -d 'X Item "-sN"'
complete -c zpaq -o summary -d 'X Item "-summary N" '
complete -c zpaq -o test -d 'X Item "-test" With \\f(CW\\*(C`extract\\*(C\', do not write to disk, but perform…'
complete -c zpaq -o tN -d 'X Item "-tN"'
complete -c zpaq -o threads -d 'X Item "-threads N" . PD Add or extract at most N blocks in parallel'
complete -c zpaq -o to -d 'X Item "-to name'
complete -c zpaq -o until

