# zpool
# Autogenerated from man page /usr/share/man/man8/zpool.8.gz
complete -c zpool -s f -d 'Forces use of vdevs, even if they appear in use or specify a conflicting repl…'
complete -c zpool -s n -d 'Displays the configuration that would be used without actually adding the vde…'
complete -c zpool -s o -d 'Sets the given pool properties'
complete -c zpool -s F -d 'Initiates recovery mode for an unopenable pool'
complete -c zpool -s O -d '[-O file-system-property=value] '
complete -c zpool -s R -d 'Equivalent to "-o cachefile=none,altroot=root"'
complete -c zpool -s m -d 'Sets the mount point for the root dataset'
complete -c zpool -s i -d 'Displays internally logged ZFS events in addition to user initiated events'
complete -c zpool -s l -d 'Displays log records in long format, which in addition to standard format inc…'
complete -c zpool -s c -d 'Reads configuration from the given cachefile that was created with the "cache…'
complete -c zpool -s d -d 'Searches for devices or files in dir'
complete -c zpool -s D -d 'Lists destroyed pools only.  zpool import [-o mntopts] [ -o property=value] '
complete -c zpool -s a -d 'Searches for and imports all pools found'
complete -c zpool -s T -d 'Display a time stamp'
complete -c zpool -s v -d 'Verbose statistics'
complete -c zpool -s H -d 'Scripted mode'
complete -c zpool -s t -d Temporary
complete -c zpool -s e -d 'Expand the device to use all available space'
complete -c zpool -s s -d 'Stop scrubbing'
complete -c zpool -s x -d 'Only display status for pools that are exhibiting errors or are otherwise una…'
complete -c zpool -s V -d 'Upgrade to the specified version'

