# zstreamdump
# Autogenerated from man page /usr/share/man/man8/zstreamdump.8.gz
complete -c zstreamdump -s C -d 'Suppress the validation of checksums'
complete -c zstreamdump -s v -d 'Verbose.  Dump all headers, not only begin and end headers'

